### ISSUE TITLE
TASK: [ora | syncdb and migrate]

### ISSUE THREAD

**Issue by bys** [openedx-unsupported/configuration#1026]
when i start this Task there is a error : 
failed: [localhost] => {"changed": true, "cmd": "SERVICE_VARIANT=ora /edx/app/ora/venvs/ora/bin/django-admin.py syncdb --migrate --noinput --settings=edx_ora.aws --pythonpath=/edx/app/ora/ora ", "delta": "0:00:00.009473", "end": "2014-04-20 20:39:37.957858", "item": "", "rc": 127, "start": "2014-04-20 20:39:37.948385"}
stderr: /bin/sh: 1: /edx/app/ora/venvs/ora/bin/django-admin.py: not found

i know there is no this file , but how can i change to correct [where to check edx_configuration files]

**Comment by bys** [comment]
@JAAkana @Lyla-Fischer @Slater-Victoroff @TeppoJouttenus @VikParuchuri

**Comment by hkim823** [comment]
Where does this error happen? In which enviorment?  What command was run?

**Comment by juanmanueluma** [comment]
I obtained the same error when I execute the folllowing command:
cd /var/tmp/configuration/playbooks && sudo ansible-playbook -c local ./edx_sandbox.yml -i "localhost,"

I'm trying to update the edx plattform. the full output is as follows:
TASK: [ora | syncdb and migrate] **********************************************
failed: [localhost] => {"changed": true, "cmd": "SERVICE_VARIANT=ora /edx/app/ora/venvs/ora/bin/django-admin.py syncdb --migrate --noinput --settings=edx_ora.aws --pythonpath=/edx/app/ora/ora ", "delta": "0:00:00.311660", "end": "2014-06-27 11:32:49.509431", "item": "", "rc": 1, "start": "2014-06-27 11:32:49.197771"}
stderr: Traceback (most recent call last):
  File "/edx/app/ora/venvs/ora/bin/django-admin.py", line 5, in <module>
    management.execute_from_command_line()
  File "/edx/app/ora/venvs/ora/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 443, in execute_from_command_line
    utility.execute()
  File "/edx/app/ora/venvs/ora/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/edx/app/ora/venvs/ora/local/lib/python2.7/site-packages/django/core/management/base.py", line 196, in run_from_argv
    self.execute(_args, *_options.**dict**)
  File "/edx/app/ora/venvs/ora/local/lib/python2.7/site-packages/django/core/management/base.py", line 231, in execute
    self.validate()
  File "/edx/app/ora/venvs/ora/local/lib/python2.7/site-packages/django/core/management/base.py", line 266, in validate
    num_errors = get_validation_errors(s, app)
  File "/edx/app/ora/venvs/ora/local/lib/python2.7/site-packages/django/core/management/validation.py", line 30, in get_validation_errors
    for (app_name, error) in get_app_errors().items():
  File "/edx/app/ora/venvs/ora/local/lib/python2.7/site-packages/django/db/models/loading.py", line 158, in get_app_errors
    self._populate()
  File "/edx/app/ora/venvs/ora/local/lib/python2.7/site-packages/django/db/models/loading.py", line 67, in _populate
    self.load_app(app_name)
  File "/edx/app/ora/venvs/ora/local/lib/python2.7/site-packages/django/db/models/loading.py", line 88, in load_app
    models = import_module('.models', app_name)
  File "/edx/app/ora/venvs/ora/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/edx/app/ora/venvs/ora/local/lib/python2.7/site-packages/djcelery/models.py", line 11, in <module>
    from celery import schedules
  File "/edx/app/ora/venvs/ora/local/lib/python2.7/site-packages/celery/schedules.py", line 16, in <module>
    from dateutil.relativedelta import relativedelta
ImportError: No module named dateutil.relativedelta

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/root/edx_sandbox.retry

localhost                  : ok=342  changed=78   unreachable=0    failed=1
