### ISSUE TITLE
TASK: [ora | syncdb and migrate] 

### ISSUE THREAD

**Issue by adxsin** [openedx-unsupported/configuration#1061]
When I run "sudo ansible-playbook -c local --limit "localhost:127.0.0.1" ../edx_sandbox.yml -i "localhost," -e 'EDXAPP_PREVIEW_LMS_BASE=preview.example.com EDXAPP_LMS_BASE=example.com EDXAPP_LMS_PREVIEW_NGINX_PORT=80 EDXAPP_CMS_NGINX_PORT=80 EDXAPP_LMS_NGINX_PORT=80 edx_platform_version=master ' " to override default web ports and make example.com and studio.example.com point to the same server.

TASK: [ora | syncdb and migrate] **********************************************
failed: [localhost] => {"changed": true, "cmd": "SERVICE_VARIANT=ora /edx/app/ora/venvs/ora/bin/django-admin.py syncdb --migrate --noinput --settings=edx_ora.aws --pythonpath=/edx/app/ora/ora ", "delta": "0:00:03.769543", "end": "2014-04-30 03:35:12.854256", "item": "", "rc": 1, "start": "2014-04-30 03:35:09.084713"}
stderr: Traceback (most recent call last):
  File "/edx/app/ora/venvs/ora/bin/django-admin.py", line 5, in <module>
    management.execute_from_command_line()
  File "/edx/app/ora/venvs/ora/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 443, in execute_from_command_line
    utility.execute()
  File "/edx/app/ora/venvs/ora/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/edx/app/ora/venvs/ora/local/lib/python2.7/site-packages/django/core/management/base.py", line 196, in run_from_argv
    self.execute(_args, *_options.**dict**)
  File "/edx/app/ora/venvs/ora/local/lib/python2.7/site-packages/django/core/management/base.py", line 231, in execute
    self.validate()
  File "/edx/app/ora/venvs/ora/local/lib/python2.7/site-packages/django/core/management/base.py", line 266, in validate
    num_errors = get_validation_errors(s, app)
  File "/edx/app/ora/venvs/ora/local/lib/python2.7/site-packages/django/core/management/validation.py", line 30, in get_validation_errors
    for (app_name, error) in get_app_errors().items():
  File "/edx/app/ora/venvs/ora/local/lib/python2.7/site-packages/django/db/models/loading.py", line 158, in get_app_errors
    self._populate()
  File "/edx/app/ora/venvs/ora/local/lib/python2.7/site-packages/django/db/models/loading.py", line 67, in _populate
    self.load_app(app_name)
  File "/edx/app/ora/venvs/ora/local/lib/python2.7/site-packages/django/db/models/loading.py", line 88, in load_app
    models = import_module('.models', app_name)
  File "/edx/app/ora/venvs/ora/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/edx/app/ora/venvs/ora/local/lib/python2.7/site-packages/djcelery/models.py", line 11, in <module>
    from celery import schedules
  File "/edx/app/ora/venvs/ora/local/lib/python2.7/site-packages/celery/schedules.py", line 16, in <module>
    from dateutil.relativedelta import relativedelta
ImportError: No module named dateutil.relativedelta

FATAL: all hosts have already failed -- aborting
ok=263  changed=69   unreachable=0    failed=1

**Comment by adxsin** [comment]
I have installed python-dateutil 2.2, but it didn't work.

**Comment by hkim823** [comment]
is python-dateutil installed in the virtualenv?  Do you have a /edx/bin directory and is there a pip.ora link in there?

**Comment by adxsin** [comment]
@hkim823  which virtualenv should i use? is it /edx/app/ora/venvs/ora/ ? In this virtualenv,  i run "pip install python-dateutil":
Requirement already satisfied (use --upgrade to upgrade): python-dateutil in ./ora/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): six in ./ora/lib/python2.7/site-packages (from python-dateutil)
i test again and it didn't work.
there is  a pip.ora in /edx/bin.

**Comment by louyihua** [comment]
@Administratorsin 
I've also encountered this problem before and the problem is caused by an incomplele installation of `python-dateutil` in the ora's virtualenv. As a solution, you should first unistall `python-dateutil` by running `pip uninstall python-dateutil` and then reinstall it with `pip install python-dateutil` in the ora's virtualenv.

**Comment by hkim823** [comment]
Thank you @louyihua for pointing that out.
