### ISSUE TITLE
TASK: [demo | add test users to the certificate whitelist]  failed:

### ISSUE THREAD

**Issue by PaoloC68** [openedx-unsupported/configuration#1117]
Hi I was following the  edX devstack installation procedure, all went fine until I stumbled in this error:

```
TASK: [demo | add test users to the certificate whitelist] ******************** 
failed: [localhost] => (item={'password': 'edx', 'email': 'honor@example.com', 'mode': 'honor'}) => {"changed": true, "cmd": "/edx/app/edxapp/venvs/edxapp/bin/python ./manage.py lms --settings=aws --service-variant lms cert_whitelist -a honor@example.com -c edX/Open_DemoX/edx_demo_course ", "delta": "0:00:01.642538", "end": "2014-05-24 19:41:57.129277", "item": {"email": "honor@example.com", "mode": "honor", "password": "edx"}, "rc": 1, "start": "2014-05-24 19:41:55.486739"}
stderr: 2014-05-24 15:41:56,235 INFO 8178 [dd.dogapi] dog_stats_api.py:66 - Initializing dog api to use statsd: localhost, 8125
Traceback (most recent call last):
  File "./manage.py", line 95, in <module>
    execute_from_command_line([sys.argv[0]] + django_args)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 443, in execute_from_command_line
    utility.execute()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/base.py", line 196, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/base.py", line 232, in execute
    output = self.handle(*args, **options)
  File "/edx/app/edxapp/edx-platform/lms/djangoapps/certificates/management/commands/cert_whitelist.py", line 59, in handle
    log.warning("Course id %s could not be parsed as a CourseKey; falling back to SSCK.from_dep_str", course_id)
NameError: global name 'log' is not defined
failed: [localhost] => (item={'password': 'edx', 'email': 'audit@example.com', 'mode': 'audit'}) => {"changed": true, "cmd": "/edx/app/edxapp/venvs/edxapp/bin/python ./manage.py lms --settings=aws --service-variant lms cert_whitelist -a audit@example.com -c edX/Open_DemoX/edx_demo_course ", "delta": "0:00:01.473785", "end": "2014-05-24 19:41:58.682348", "item": {"email": "audit@example.com", "mode": "audit", "password": "edx"}, "rc": 1, "start": "2014-05-24 19:41:57.208563"}
stderr: 2014-05-24 15:41:57,914 INFO 8197 [dd.dogapi] dog_stats_api.py:66 - Initializing dog api to use statsd: localhost, 8125
Traceback (most recent call last):
  File "./manage.py", line 95, in <module>
    execute_from_command_line([sys.argv[0]] + django_args)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 443, in execute_from_command_line
    utility.execute()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/base.py", line 196, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/base.py", line 232, in execute
    output = self.handle(*args, **options)
  File "/edx/app/edxapp/edx-platform/lms/djangoapps/certificates/management/commands/cert_whitelist.py", line 59, in handle
    log.warning("Course id %s could not be parsed as a CourseKey; falling back to SSCK.from_dep_str", course_id)
NameError: global name 'log' is not defined
failed: [localhost] => (item={'password': 'edx', 'email': 'verified@example.com', 'mode': 'verified'}) => {"changed": true, "cmd": "/edx/app/edxapp/venvs/edxapp/bin/python ./manage.py lms --settings=aws --service-variant lms cert_whitelist -a verified@example.com -c edX/Open_DemoX/edx_demo_course ", "delta": "0:00:01.485221", "end": "2014-05-24 19:42:00.230929", "item": {"email": "verified@example.com", "mode": "verified", "password": "edx"}, "rc": 1, "start": "2014-05-24 19:41:58.745708"}
stderr: 2014-05-24 15:41:59,435 INFO 8216 [dd.dogapi] dog_stats_api.py:66 - Initializing dog api to use statsd: localhost, 8125
Traceback (most recent call last):
  File "./manage.py", line 95, in <module>
    execute_from_command_line([sys.argv[0]] + django_args)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 443, in execute_from_command_line
    utility.execute()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/base.py", line 196, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/base.py", line 232, in execute
    output = self.handle(*args, **options)
  File "/edx/app/edxapp/edx-platform/lms/djangoapps/certificates/management/commands/cert_whitelist.py", line 59, in handle
    log.warning("Course id %s could not be parsed as a CourseKey; falling back to SSCK.from_dep_str", course_id)
NameError: global name 'log' is not defined

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/root/vagrant-devstack.retry

localhost                  : ok=240  changed=80   unreachable=0    failed=1   



Stderr from the command:

stdin: is not a tty
```

What can I do to fix it? Thanks

**Comment by PaoloC68** [comment]
I have set a pull request for that in edx/edx-platform

**Comment by PaoloC68** [comment]
Please, how can I continue the stopped configuration?

**Comment by feanil** [comment]
What is the edX platform PR number?

**Comment by singingwolfboy** [comment]
This has already been fixed in https://github.com/edx/edx-platform/pull/3874.
