### ISSUE TITLE
EDX Install error 

### ISSUE THREAD

**Issue by isural** [openedx-unsupported/configuration#1230]
Hi All,

I have problem while installing EDX on Ubuntu 12.04 64 bit server.
Error is bellow;

Obtaining pika from git+git://github.com/pika/pika.git@a731347fc0#egg=pika (from -r /edx/app/xqueue/xqueue/requirements.txt (line 14))
  Found command 'git' at '/usr/bin/git'
  Running command /usr/bin/git config remote.origin.url
  https://github.com/pika/pika.git
  git clone in /edx/app/xqueue/venvs/xqueue/src/pika exists with URL https://github.com/pika/pika.git
  The plan is to install the git repository git://github.com/pika/pika.git
Cleaning up...
  Removing temporary dir /edx/app/xqueue/venvs/xqueue/build...
Exception:
Traceback (most recent call last):
  File "/edx/app/xqueue/venvs/xqueue/local/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/edx/app/xqueue/venvs/xqueue/local/lib/python2.7/site-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/edx/app/xqueue/venvs/xqueue/local/lib/python2.7/site-packages/pip/req.py", line 1140, in prepare_files
    req_to_install.update_editable(not self.is_download)
  File "/edx/app/xqueue/venvs/xqueue/local/lib/python2.7/site-packages/pip/req.py", line 483, in update_editable
    vcs_backend.obtain(self.source_dir)
  File "/edx/app/xqueue/venvs/xqueue/local/lib/python2.7/site-packages/pip/vcs/git.py", line 109, in obtain
    if self.check_destination(dest, url, rev_options, rev_display):
  File "/edx/app/xqueue/venvs/xqueue/local/lib/python2.7/site-packages/pip/vcs/**init**.py", line 215, in check_destination
    prompt[1])
  File "/edx/app/xqueue/venvs/xqueue/local/lib/python2.7/site-packages/pip/util.py", line 124, in ask_path_exists
    return ask(message, options)
  File "/edx/app/xqueue/venvs/xqueue/local/lib/python2.7/site-packages/pip/util.py", line 132, in ask
    response = raw_input(message)
EOFError: EOF when reading a line

**Comment by hkim823** [comment]
Can you tell us what you were doing to get this error?
