### ISSUE TITLE
edx update

### ISSUE THREAD

**Issue by juanmanueluma** [openedx-unsupported/configuration#1253]
I'm trying to update an edx platform and when I execute the following command receive errors:

cd /var/tmp/configuration/playbooks && sudo ansible-playbook -c local ./edx_sandbox.yml -i "localhost,"

Now I copy the output:

TASK: [ora | syncdb and migrate] **********************************************
failed: [localhost] => {"changed": true, "cmd": "SERVICE_VARIANT=ora /edx/app/ora/venvs/ora/bin/django-admin.py syncdb --migrate --noinput --settings=edx_ora.aws --pythonpath=/edx/app/ora/ora ", "delta": "0:00:00.311660", "end": "2014-06-27 11:32:49.509431", "item": "", "rc": 1, "start": "2014-06-27 11:32:49.197771"}
stderr: Traceback (most recent call last):
  File "/edx/app/ora/venvs/ora/bin/django-admin.py", line 5, in <module>
    management.execute_from_command_line()
  File "/edx/app/ora/venvs/ora/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 443, in execute_from_command_line
    utility.execute()
  File "/edx/app/ora/venvs/ora/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/edx/app/ora/venvs/ora/local/lib/python2.7/site-packages/django/core/management/base.py", line 196, in run_from_argv
    self.execute(_args, *_options.**dict**)
  File "/edx/app/ora/venvs/ora/local/lib/python2.7/site-packages/django/core/management/base.py", line 231, in execute
    self.validate()
  File "/edx/app/ora/venvs/ora/local/lib/python2.7/site-packages/django/core/management/base.py", line 266, in validate
    num_errors = get_validation_errors(s, app)
  File "/edx/app/ora/venvs/ora/local/lib/python2.7/site-packages/django/core/management/validation.py", line 30, in get_validation_errors
    for (app_name, error) in get_app_errors().items():
  File "/edx/app/ora/venvs/ora/local/lib/python2.7/site-packages/django/db/models/loading.py", line 158, in get_app_errors
    self._populate()
  File "/edx/app/ora/venvs/ora/local/lib/python2.7/site-packages/django/db/models/loading.py", line 67, in _populate
    self.load_app(app_name)
  File "/edx/app/ora/venvs/ora/local/lib/python2.7/site-packages/django/db/models/loading.py", line 88, in load_app
    models = import_module('.models', app_name)
  File "/edx/app/ora/venvs/ora/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/edx/app/ora/venvs/ora/local/lib/python2.7/site-packages/djcelery/models.py", line 11, in <module>
    from celery import schedules
  File "/edx/app/ora/venvs/ora/local/lib/python2.7/site-packages/celery/schedules.py", line 16, in <module>
    from dateutil.relativedelta import relativedelta
ImportError: No module named dateutil.relativedelta

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/root/edx_sandbox.retry

localhost                  : ok=342  changed=78   unreachable=0    failed=1

**Comment by hkim823** [comment]
That's a relatively old bug that I haven't seen in a while, can you describe your enviorment, and what branch of configuration and edx-platform you are building from?

**Comment by juanmanueluma** [comment]
This edx-platform was instaled on a Ubuntu 12.04 32 bits Vmware virtual machine with 2GB of RAM and 50GB of disk space following the instructions in https://github.com/edx/configuration/wiki/edX-Ubuntu-12.04-Installation without Vagrant.

Now I see that actually the recomended OS is Ubuntu 64 bits, Do yo recommend me to migrate tu Ubuntu 64 bits or can we make changes to solve the problem?

Thanks!!!

**Comment by hkim823** [comment]
32 is definitely a no no, it does not work.

**Comment by juanmanueluma** [comment]
We are now working on 64 plattform.
Thanks.
