### ISSUE TITLE
Not Able to Login into the EDX Dashboard

### ISSUE THREAD

**Issue by Jalpal** [openedx-unsupported/configuration#1507]
Hi Team,

Once i launch the EDX platform using the prebaked AMI (ami-0d393848) 
sudo /edx/bin/update configuration master 
sudo /edx/bin/update edx-platform master
sudo /edx/bin/update edx-platform release

Once the update is complete, I can connect to the LMS on port 80 and Studio on port 18010
Basic auth for the site is username: edx password: edx

Once i login with default login user: staff@example.com password: edx
Then am having following error

There has been a 500 error on the Your Platform Name Here servers 

And also how can i host my course on EDX platform

Regards,
Nagaraju J

**Comment by e0d** [comment]
What do you see in /edx/var/log/lms/edx.log?

**Comment by Jalpal** [comment]
==> /edx/var/log/lms/edx.log <==
Sep  1 12:11:21 ip-172-31-4-221
[service_variant=lms][celery.worker.consumer][env:sandbox] ERROR
[ip-172-31-4-221  4464] [consumer.py:796] - consumer: Cannot connect to
amqp://celery@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 26.00 seconds...
Sep  1 12:11:50 ip-172-31-4-221
[service_variant=lms][celery.worker.consumer][env:sandbox] ERROR
[ip-172-31-4-221  4446] [consumer.py:796] - consumer: Cannot connect to
amqp://celery@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 28.00 seconds...
Sep  1 12:11:50 ip-172-31-4-221
[service_variant=lms][celery.worker.consumer][env:sandbox] ERROR
[ip-172-31-4-221  4454] [consumer.py:796] - consumer: Cannot connect to
amqp://celery@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 28.00 seconds...
Sep  1 12:11:50 ip-172-31-4-221
[service_variant=lms][celery.worker.consumer][env:sandbox] ERROR
[ip-172-31-4-221  4448] [consumer.py:796] - consumer: Cannot connect to
amqp://celery@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 28.00 seconds...
Sep  1 12:11:50 ip-172-31-4-221
[service_variant=lms][celery.worker.consumer][env:sandbox] ERROR
[ip-172-31-4-221  4464] [consumer.py:796] - consumer: Cannot connect to
amqp://celery@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 28.00 seconds...

Thanks...

**Comment by e0d** [comment]
Those celery disconnect errors are not what is causing your issue. Can you tail the log and go to the page that results in the 500.

**Comment by Jalpal** [comment]
I have logged in again and here are the logs of the 

sudo tailf /edx/var/log/lms/edx.log
Sep  1 12:17:35 ip-172-31-4-221 [service_variant=lms][celery.worker.consumer][env:sandbox] ERROR [ip-172-31-4-221  4464] [consumer.py:796] - consumer: Cannot connect to amqp://celery@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...
Sep  1 12:18:09 ip-172-31-4-221 [service_variant=lms][celery.worker.consumer][env:sandbox] ERROR [ip-172-31-4-221  4446] [consumer.py:796] - consumer: Cannot connect to amqp://celery@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...
Sep  1 12:18:09 ip-172-31-4-221 [service_variant=lms][celery.worker.consumer][env:sandbox] ERROR [ip-172-31-4-221  4454] [consumer.py:796] - consumer: Cannot connect to amqp://celery@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...
Sep  1 12:18:10 ip-172-31-4-221 [service_variant=lms][celery.worker.consumer][env:sandbox] ERROR [ip-172-31-4-221  4448] [consumer.py:796] - consumer: Cannot connect to amqp://celery@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...
Sep  1 12:18:10 ip-172-31-4-221 [service_variant=lms][celery.worker.consumer][env:sandbox] ERROR [ip-172-31-4-221  4464] [consumer.py:796] - consumer: Cannot connect to amqp://celery@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...
Sep  1 12:18:44 ip-172-31-4-221 [service_variant=lms][celery.worker.consumer][env:sandbox] ERROR [ip-172-31-4-221  4446] [consumer.py:796] - consumer: Cannot connect to amqp://celery@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...
Sep  1 12:18:44 ip-172-31-4-221 [service_variant=lms][celery.worker.consumer][env:sandbox] ERROR [ip-172-31-4-221  4454] [consumer.py:796] - consumer: Cannot connect to amqp://celery@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...
Sep  1 12:18:45 ip-172-31-4-221 [service_variant=lms][celery.worker.consumer][env:sandbox] ERROR [ip-172-31-4-221  4448] [consumer.py:796] - consumer: Cannot connect to amqp://celery@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...
Sep  1 12:18:45 ip-172-31-4-221 [service_variant=lms][celery.worker.consumer][env:sandbox] ERROR [ip-172-31-4-221  4464] [consumer.py:796] - consumer: Cannot connect to amqp://celery@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...
Sep  1 12:18:51 ip-172-31-4-221 [service_variant=lms][root][env:sandbox] ERROR [ip-172-31-4-221  6541] [exceptions.py:9] - Uncaught exception from <class 'django.core.handlers.wsgi.WSGIHandler'>
Traceback (most recent call last):
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, _callback_args, *_callback_kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
    return view_func(request, _args, *_kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, _args, *_kwargs)
  File "/edx/app/edxapp/edx-platform/common/djangoapps/student/views.py", line 468, in dashboard
    course_modes = {course.id: complete_course_mode_info(course.id, enrollment) for course, enrollment in course_enrollment_pairs}
  File "/edx/app/edxapp/edx-platform/common/djangoapps/student/views.py", line 468, in <dictcomp>
    course_modes = {course.id: complete_course_mode_info(course.id, enrollment) for course, enrollment in course_enrollment_pairs}
  File "/edx/app/edxapp/edx-platform/common/djangoapps/student/views.py", line 415, in complete_course_mode_info
    modes = CourseMode.modes_for_course_dict(course_id)
  File "/edx/app/edxapp/edx-platform/common/djangoapps/course_modes/models.py", line 96, in modes_for_course_dict
    return {mode.slug: mode for mode in cls.modes_for_course(course_id)}
  File "/edx/app/edxapp/edx-platform/common/djangoapps/course_modes/models.py", line 85, in modes_for_course
    ) for mode in found_course_modes])
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/models/query.py", line 118, in _result_iter
    self._fill_cache()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/models/query.py", line 892, in _fill_cache
    self._result_cache.append(self._iter.next())
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/models/query.py", line 291, in iterator
    for row in compiler.results_iter():
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 763, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 818, in execute_sql
    cursor.execute(sql, params)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 114, in execute
    return self.cursor.execute(query, args)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 201, in execute
    self.errorhandler(self, exc, value)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
DatabaseError: (1054, "Unknown column 'course_modes_coursemode.description' in 'field list'")
Sep  1 12:18:51 ip-172-31-4-221 [service_variant=lms][django.request][env:sandbox] ERROR [ip-172-31-4-221  6541] [base.py:215] - Internal Server Error: /dashboard
Traceback (most recent call last):
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, _callback_args, *_callback_kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
    return view_func(request, _args, *_kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, _args, *_kwargs)
  File "/edx/app/edxapp/edx-platform/common/djangoapps/student/views.py", line 468, in dashboard
    course_modes = {course.id: complete_course_mode_info(course.id, enrollment) for course, enrollment in course_enrollment_pairs}
  File "/edx/app/edxapp/edx-platform/common/djangoapps/student/views.py", line 468, in <dictcomp>
    course_modes = {course.id: complete_course_mode_info(course.id, enrollment) for course, enrollment in course_enrollment_pairs}
  File "/edx/app/edxapp/edx-platform/common/djangoapps/student/views.py", line 415, in complete_course_mode_info
    modes = CourseMode.modes_for_course_dict(course_id)
  File "/edx/app/edxapp/edx-platform/common/djangoapps/course_modes/models.py", line 96, in modes_for_course_dict
    return {mode.slug: mode for mode in cls.modes_for_course(course_id)}
  File "/edx/app/edxapp/edx-platform/common/djangoapps/course_modes/models.py", line 85, in modes_for_course
    ) for mode in found_course_modes])
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/models/query.py", line 118, in _result_iter
    self._fill_cache()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/models/query.py", line 892, in _fill_cache
    self._result_cache.append(self._iter.next())
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/models/query.py", line 291, in iterator
    for row in compiler.results_iter():
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 763, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 818, in execute_sql
    cursor.execute(sql, params)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 114, in execute
    return self.cursor.execute(query, args)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 201, in execute
    self.errorhandler(self, exc, value)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
DatabaseError: (1054, "Unknown column 'course_modes_coursemode.description' in 'field list'")
Sep  1 12:18:55 ip-172-31-4-221 [service_variant=lms][audit][env:sandbox] INFO [ip-172-31-4-221  6541] [models.py:1218] - Logout - staff
Sep  1 12:19:07 ip-172-31-4-221 [service_variant=lms][audit][env:sandbox] INFO [ip-172-31-4-221  6529] [models.py:1209] - Login success - staff (staff@example.com)
Sep  1 12:19:08 ip-172-31-4-221 [service_variant=lms][root][env:sandbox] ERROR [ip-172-31-4-221  6541] [exceptions.py:9] - Uncaught exception from <class 'django.core.handlers.wsgi.WSGIHandler'>
Traceback (most recent call last):
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, _callback_args, *_callback_kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
    return view_func(request, _args, *_kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, _args, *_kwargs)
  File "/edx/app/edxapp/edx-platform/common/djangoapps/student/views.py", line 468, in dashboard
    course_modes = {course.id: complete_course_mode_info(course.id, enrollment) for course, enrollment in course_enrollment_pairs}
  File "/edx/app/edxapp/edx-platform/common/djangoapps/student/views.py", line 468, in <dictcomp>
    course_modes = {course.id: complete_course_mode_info(course.id, enrollment) for course, enrollment in course_enrollment_pairs}
  File "/edx/app/edxapp/edx-platform/common/djangoapps/student/views.py", line 415, in complete_course_mode_info
    modes = CourseMode.modes_for_course_dict(course_id)
  File "/edx/app/edxapp/edx-platform/common/djangoapps/course_modes/models.py", line 96, in modes_for_course_dict
    return {mode.slug: mode for mode in cls.modes_for_course(course_id)}
  File "/edx/app/edxapp/edx-platform/common/djangoapps/course_modes/models.py", line 85, in modes_for_course
    ) for mode in found_course_modes])
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/models/query.py", line 118, in _result_iter
    self._fill_cache()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/models/query.py", line 892, in _fill_cache
    self._result_cache.append(self._iter.next())
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/models/query.py", line 291, in iterator
    for row in compiler.results_iter():
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 763, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 818, in execute_sql
    cursor.execute(sql, params)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 114, in execute
    return self.cursor.execute(query, args)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 201, in execute
    self.errorhandler(self, exc, value)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
DatabaseError: (1054, "Unknown column 'course_modes_coursemode.description' in 'field list'")
Sep  1 12:19:08 ip-172-31-4-221 [service_variant=lms][django.request][env:sandbox] ERROR [ip-172-31-4-221  6541] [base.py:215] - Internal Server Error: /dashboard
Traceback (most recent call last):
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, _callback_args, *_callback_kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
    return view_func(request, _args, *_kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, _args, *_kwargs)
  File "/edx/app/edxapp/edx-platform/common/djangoapps/student/views.py", line 468, in dashboard
    course_modes = {course.id: complete_course_mode_info(course.id, enrollment) for course, enrollment in course_enrollment_pairs}
  File "/edx/app/edxapp/edx-platform/common/djangoapps/student/views.py", line 468, in <dictcomp>
    course_modes = {course.id: complete_course_mode_info(course.id, enrollment) for course, enrollment in course_enrollment_pairs}
  File "/edx/app/edxapp/edx-platform/common/djangoapps/student/views.py", line 415, in complete_course_mode_info
    modes = CourseMode.modes_for_course_dict(course_id)
  File "/edx/app/edxapp/edx-platform/common/djangoapps/course_modes/models.py", line 96, in modes_for_course_dict
    return {mode.slug: mode for mode in cls.modes_for_course(course_id)}
  File "/edx/app/edxapp/edx-platform/common/djangoapps/course_modes/models.py", line 85, in modes_for_course
    ) for mode in found_course_modes])
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/models/query.py", line 118, in _result_iter
    self._fill_cache()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/models/query.py", line 892, in _fill_cache
    self._result_cache.append(self._iter.next())
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/models/query.py", line 291, in iterator
    for row in compiler.results_iter():
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 763, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 818, in execute_sql
    cursor.execute(sql, params)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 114, in execute
    return self.cursor.execute(query, args)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 201, in execute
    self.errorhandler(self, exc, value)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
DatabaseError: (1054, "Unknown column 'course_modes_coursemode.description' in 'field list'")
Sep  1 12:19:19 ip-172-31-4-221 [service_variant=lms][celery.worker.consumer][env:sandbox] ERROR [ip-172-31-4-221  4446] [consumer.py:796] - consumer: Cannot connect to amqp://celery@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...
Sep  1 12:19:20 ip-172-31-4-221 [service_variant=lms][celery.worker.consumer][env:sandbox] ERROR [ip-172-31-4-221  4454] [consumer.py:796] - consumer: Cannot connect to amqp://celery@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...
Sep  1 12:19:20 ip-172-31-4-221 [service_variant=lms][celery.worker.consumer][env:sandbox] ERROR [ip-172-31-4-221  4448] [consumer.py:796] - consumer: Cannot connect to amqp://celery@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...
Sep  1 12:19:20 ip-172-31-4-221 [service_variant=lms][celery.worker.consumer][env:sandbox] ERROR [ip-172-31-4-221  4464] [consumer.py:796] - consumer: Cannot connect to amqp://celery@127.0.0.1:5672//: [Errno 104] Connection reset by peer.

**Comment by Jalpal** [comment]
Any help on the above issue is very much appreciated

**Comment by feanil** [comment]
Looks like you need to run migrations.
