### ISSUE TITLE
libatlas.so.3gf: cannot open shared object file

### ISSUE THREAD

**Issue by dbrgn** [openedx-unsupported/configuration#1652]
I used the current AMI image and then upgraded to `openedx/rc/aspen-2014-09-10`. Now I'm getting HTTP500 errors.

In the lms log I found the following error:

``` python
Oct 22 09:33:46 ip-172-31-12-197 [service_variant=lms][gunicorn.error][env:sandbox] ERROR [ip-172-31-12-197  1948] [glogging.py:219] - Error handling request
Traceback (most recent call last):
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 126, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 219, in __call__
    self.load_middleware()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 47, in load_middleware
    raise exceptions.ImproperlyConfigured('Error importing middleware %s: "%s"' % (mw_module, e))
ImproperlyConfigured: Error importing middleware course_wiki.middleware: "libatlas.so.3gf: cannot open shared object file: No such file or directory"
```

Any ideas?

**Comment by dbrgn** [comment]
This did the trick:

I created a file `/etc/ld.so.conf.d/atlas-lib.conf` with the following content, followed by a `sudo ldconfig`:

```
/usr/lib/atlas-base
/usr/lib/atlas-base/atlas
/usr/lib/libblas
```

Maybe there's some issue with the SciPy library path?

**Comment by hkim823** [comment]
Between the the kifli AMI and the aspen release, there is a different in the version of matplotlib which caused this error, the fix is what you did above.

**Comment by reroes** [comment]
It's ok for me. Thank.
