### ISSUE TITLE
Error during installation with ansible

### ISSUE THREAD

**Issue by Odrec** [openedx-unsupported/configuration#1663]
Hi I used the instructions here https://github.com/edx/configuration/wiki/edX-Ubuntu-12.04-64-bit-Installation to install the edx platform. Everything was running fine but then I get this error when I get to the ansible-playbook part of the script when trying to download nltk data. After the script failed I deleted the configurations folder in /var/tmp and tried the manual installation but it failed with the same error.

This part is weird: invalid output was: SUDO-SUCCESS-eugxpxjcwpnpwcgahpavlcaiklhdevfk

Here is all the output of the error:

TASK: [nltk | create the nltk data directory and subdirectories] **************
ok: [localhost] => (item={'url': 'http://nltk.github.com/nltk_data/packages/taggers/maxent_treebank_pos_tagger.zip', 'path': 'taggers/maxent_treebank_pos_tagger'})
ok: [localhost] => (item={'url': 'http://nltk.github.com/nltk_data/packages/corpora/stopwords.zip', 'path': 'corpora/stopwords'})
ok: [localhost] => (item={'url': 'http://nltk.github.com/nltk_data/packages/corpora/wordnet.zip', 'path': 'corpora/wordnet'})

TASK: [nltk | download nltk data] *********************************************
failed: [localhost] => (item={'url': 'http://nltk.github.com/nltk_data/packages/taggers/maxent_treebank_pos_tagger.zip', 'path': 'taggers/maxent_treebank_pos_tagger'}) => {"failed": true, "item": {"path": "taggers/maxent_treebank_pos_tagger", "url": "http://nltk.github.com/nltk_data/packages/taggers/maxent_treebank_pos_tagger.zip"}, "parsed": false}
invalid output was: SUDO-SUCCESS-eugxpxjcwpnpwcgahpavlcaiklhdevfk
Traceback (most recent call last):
  File "/home/renato/.ansible/tmp/ansible-tmp-1414174942.59-37669901510453/get_url", line 1664, in <module>
    main()
  File "/home/renato/.ansible/tmp/ansible-tmp-1414174942.59-37669901510453/get_url", line 209, in main
    tmpsrc, info = url_get(module, url, dest, use_proxy, last_mod_time, force)
  File "/home/renato/.ansible/tmp/ansible-tmp-1414174942.59-37669901510453/get_url", line 134, in url_get
    rsp, info = fetch_url(module, url, use_proxy=use_proxy, force=force, last_mod_time=last_mod_time)
  File "/home/renato/.ansible/tmp/ansible-tmp-1414174942.59-37669901510453/get_url", line 1652, in fetch_url
    r = urllib2.urlopen(request, None, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 406, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 519, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 438, in error
    result = self._call_chain(_args)
  File "/usr/lib/python2.7/urllib2.py", line 378, in _call_chain
    result = func(_args)
  File "/usr/lib/python2.7/urllib2.py", line 625, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 406, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 519, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 438, in error
    result = self._call_chain(_args)
  File "/usr/lib/python2.7/urllib2.py", line 378, in _call_chain
    result = func(_args)
  File "/usr/lib/python2.7/urllib2.py", line 625, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 400, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 418, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1207, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1180, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1030, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 407, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 365, in _read_status
    line = self.fp.readline()
  File "/usr/lib/python2.7/socket.py", line 447, in readline
    data = self._sock.recv(self._rbufsize)
socket.timeout: timed out

ok: [localhost] => (item={'url': 'http://nltk.github.com/nltk_data/packages/corpora/stopwords.zip', 'path': 'corpora/stopwords'})
ok: [localhost] => (item={'url': 'http://nltk.github.com/nltk_data/packages/corpora/wordnet.zip', 'path': 'corpora/wordnet'})

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/home/renato/edx_sandbox.retry

localhost                  : ok=116  changed=19   unreachable=0    failed=1

**Comment by e0d** [comment]
This may be an ephermal network error or an issue with your network configuration.  From the host, does

```
wget http://nltk.github.com/nltk_data/packages/taggers/maxent_treebank_pos_tagger.zip
```

work?

**Comment by Odrec** [comment]
Hey thanks for the quick answer. Sorry I was away for the weekend so I just saw this. I tried to get that file with wget from the server I'm trying to install edx on and it worked but I still get the strange error when trying to do it with ansible.

I think the problem has to do with this line 

invalid output was: SUDO-SUCCESS-ayydittugqheohxmgbuleolvrldefefm

Any other ideas?

**Comment by Odrec** [comment]
So I updated the version of ansible to see if the problem will go away and now I get this error before I get to the nltk part. Is there a simple way to get everything back to how it was at the start?

Really getting frustrated now... so any help is welcomed

TASK: [mongo | install mongo server and recommends] ***************************
failed: [localhost] => {"cmd": ["DEBIAN_FRONTEND=noninteractive", "DEBIAN_PRIORITY=critical", "/usr/bin/apt-get", "-y", "-o", "Dpkg::Options::=--force-confdef", "-o", "Dpkg::Options::=--force-confold", "--force-yes", "install", "mongodb-10gen=2.4.7"], "failed": true, "item": "", "rc": 2}
msg: [Errno 2] No such file or directory

FATAL: all hosts have already failed -- aborting

**Comment by Odrec** [comment]
I managed to solve the problem with mongo. It somehow couldn't find the right version of mongodb-10gen so I installed it with apt. Then I got another error which had to do with the ansible version. The ansible version was supposed to be 1.5.5 according to the command ansible --version but it was actually 1.4.4. I have no idea why that was happening but I installed the right version and now I'm back to the original error which is still there.

**Comment by Odrec** [comment]
So I edited edx_sanbox.yml where it said Sudo: Yes and changed it to Sudo: No. I ran the command with the root user and now the error changed at least the SUDO-SUCCESS part but it now says invalid output was: Traceback (most recent call last):

TASK: [nltk | download nltk data] *********************************************
failed: [localhost] => (item={'url': 'http://nltk.github.com/nltk_data/packages/taggers/maxent_treebank_pos_tagger.zip', 'path': 'taggers/maxent_treebank_pos_tagger'}) => {"failed": true, "item": {"path": "taggers/maxent_treebank_pos_tagger", "url": "http://nltk.github.com/nltk_data/packages/taggers/maxent_treebank_pos_tagger.zip"}, "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1414442030.55-214362256086908/get_url", line 1664, in <module>
    main()
  File "/root/.ansible/tmp/ansible-tmp-1414442030.55-214362256086908/get_url", line 209, in main
    tmpsrc, info = url_get(module, url, dest, use_proxy, last_mod_time, force)
  File "/root/.ansible/tmp/ansible-tmp-1414442030.55-214362256086908/get_url", line 134, in url_get
    rsp, info = fetch_url(module, url, use_proxy=use_proxy, force=force, last_mod_time=last_mod_time)
  File "/root/.ansible/tmp/ansible-tmp-1414442030.55-214362256086908/get_url", line 1652, in fetch_url
    r = urllib2.urlopen(request, None, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 406, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 519, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 438, in error
    result = self._call_chain(_args)
  File "/usr/lib/python2.7/urllib2.py", line 378, in _call_chain
    result = func(_args)
  File "/usr/lib/python2.7/urllib2.py", line 625, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 406, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 519, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 438, in error
    result = self._call_chain(_args)
  File "/usr/lib/python2.7/urllib2.py", line 378, in _call_chain
    result = func(_args)
  File "/usr/lib/python2.7/urllib2.py", line 625, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 400, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 418, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1207, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1180, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1030, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 407, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 365, in _read_status
    line = self.fp.readline()
  File "/usr/lib/python2.7/socket.py", line 447, in readline
    data = self._sock.recv(self._rbufsize)
socket.timeout: timed out

ok: [localhost] => (item={'url': 'http://nltk.github.com/nltk_data/packages/corpora/stopwords.zip', 'path': 'corpora/stopwords'})
ok: [localhost] => (item={'url': 'http://nltk.github.com/nltk_data/packages/corpora/wordnet.zip', 'path': 'corpora/wordnet'})

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/root/edx_sandbox.retry

localhost                  : ok=116  changed=16   unreachable=0    failed=1

**Comment by feanil** [comment]
Are you able to download that file from github directly?  It looks like a
connectivity issue from the machine where you're running ansible.

**Comment by Odrec** [comment]
Yes I am able to download that file from the machine I'm installing ansible on.

**Comment by Odrec** [comment]
Ok I finally just downloaded the file manually and that seems to have solved the problem. So yeah it was a connection error but only with that file... weird.

**Comment by praneethkumarpidugu** [comment]
After manually installing three github packages like below
$wget http://nltk.github.com/nltk_data/packages/taggers/maxent_treebank_pos_tagger.zip
$wget http://nltk.github.com/nltk_data/packages/corpora/stopwords.zip
$wget http://nltk.github.com/nltk_data/packages/corpora/wordnet.zip

After succesfully performing the above steps you have to again configure the requirements.txt and sandbox in the configuration directory like below

$cd /var/tmp/configuration
$sudo pip install -r requirements.txt
after the above command is succesfully installed. execute the below command again:
$cd /var/tmp/configuration/playbooks && sudo ansible-playbook -c local ./edx_sandbox.yml -i "localhost,"
