### ISSUE TITLE
Email function with "Installing edX on a single Ubuntu 12.04 (Precise) server" documentation

### ISSUE THREAD

**Issue by patrickshan** [openedx-unsupported/configuration#182]
Hi there,
I have tried the new documentation "Installing edX on a single Ubuntu 12.04 (Precise) server" on an EC2 instance. But the email function (by AWS SES) doesn't work. I have already added the AWS keys information in the auth file and also checked the configuration under /opt/wwc/edx-platform/{cms,lms}/{common.py, aws.py} to use SES backend. But the email function doesn't work.

I used the same method on the other server with an old version of edx-configuration, it worked then. Any new changes for the email configuration ?

Any suggestion is appreciated. 

Thanks

**Comment by patrickshan** [comment]
Traceback (most recent call last):
  File "/opt/wwc/edx-platform/common/djangoapps/student/views.py", line 687, in create_account
    res = user.email_user(subject, message, settings.DEFAULT_FROM_EMAIL)
  File "/opt/edx/local/lib/python2.7/site-packages/django/contrib/auth/models.py", line 374, in email_user
    send_mail(subject, message, from_email, [self.email])
  File "/opt/edx/local/lib/python2.7/site-packages/django/core/mail/**init**.py", line 61, in send_mail
    connection=connection).send()
  File "/opt/edx/local/lib/python2.7/site-packages/django/core/mail/message.py", line 248, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/opt/edx/local/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 85, in send_messages
    new_conn_created = self.open()
  File "/opt/edx/local/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 48, in open
    local_hostname=DNS_NAME.get_fqdn())
  File "/usr/lib/python2.7/smtplib.py", line 249, in **init**
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python2.7/smtplib.py", line 309, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python2.7/smtplib.py", line 284, in _get_socket
    return socket.create_connection((port, host), timeout)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 111] Connection refused

It seems that it tried to use smtp to send email.

**Comment by patrickshan** [comment]
I found the solution. The new configuration has been migrated to /opt/wwc/lms.env.json (was in /opt/wwc/edx-platform/lms/envs/aws.py)
change from
"EMAIL_BACKEND": "django.core.mail.backends.smtp.EmailBackend",
to
"EMAIL_BACKEND": "django_ses.SESBackend",

**Comment by fcgravalos** [comment]
Hi,

I'm just installing edx and I found an issue with EMAIL_BACKEND, I used bok_choy configuration, because is the only one provided.

Should I recompile assets with aws settings? If so, How it will find the "aws.envs.json"? Do I have to rename bok_choy.envs.json?

Thanks.
