### ISSUE TITLE
Building a new devstack base box fails at TASK: [edxapp | syncdb and migrate]

### ISSUE THREAD

**Issue by axilleas** [openedx-unsupported/configuration#1883]
For some reason I needed an image with no lvm., so I built a new ubuntu 12.04 vagrant box using [this template](https://github.com/shiguredo/packer-templates/tree/develop/ubuntu-12.04) where I removed all the lvm entries in `pressed.cfg` and replaced with:

```
d-i partman-auto/method string regular
```

So, after a successful build, I edited the Vagrantfile to use my box and ran `vagrant up` in `vagrant/base/devstack` which after an hour or so, stopped at the edxapp migrations.

Among  the lines I saw this error:

```
stderr: warning: unable to access '/root/.config/git/attributes': Permission denied
```

which I believe is why it fails. Full stacktrace below:

``` bash
TASK: [edxapp | syncdb and migrate] ******************************************* 
<127.0.0.1> 
<127.0.0.1> 
<127.0.0.1> IdentityFile=/home/axil/ellak/edx/configuration/vagrant/base/devstack/.vagrant/machines/default/virtualbox/private_key ConnectTimeout=10 KbdInteractiveAuthe
ntication=no PasswordAuthentication=no UserKnownHostsFile=/dev/null User=vagrant ControlPath=/home/axil/.ansible/cp/ansible-ssh-%h-%p-%r PreferredAuthentications=gssapi
-with-mic,gssapi-keyex,hostbased,publickey StrictHostKeyChecking=no ControlMaster=auto Port=2222 ControlPersist=60s
<127.0.0.1> 
<127.0.0.1> IdentityFile=/home/axil/ellak/edx/configuration/vagrant/base/devstack/.vagrant/machines/default/virtualbox/private_key ConnectTimeout=10 KbdInteractiveAuthe
ntication=no 'sudo -k && sudo -H -S -p "[sudo via ansible, key=rupdbexqlfkrgirrnvnflwjnfzaivruv] password: " -u root /bin/sh -c '"'"'echo SUDO-SUCCESS-rupdbexqlfkrgirrn
vnflwjnfzaivruv; LANG=en_US.UTF-8 DB_MIGRATION_PASS=password EDX_PLATFORM_SETTINGS_OVERRIDE=aws_migrate LC_CTYPE=en_US.UTF-8 DB_MIGRATION_USER=migrate /usr/bin/python /
home/vagrant/.ansible/tmp/ansible-tmp-1425553423.34-186017865741906/command; rm -rf /home/vagrant/.ansible/tmp/ansible-tmp-1425553423.34-186017865741906/ >/dev/null 2>&
1'"'"'' PasswordAuthentication=no UserKnownHostsFile=/dev/null User=vagrant ControlPath=/home/axil/.ansible/cp/ansible-ssh-%h-%p-%r PreferredAuthentications=gssapi-with
-mic,gssapi-keyex,hostbased,publickey StrictHostKeyChecking=no ControlMaster=auto Port=2222 ControlPersist=60s


failed: [default] => (item=lms) => {"changed": true, "cmd": ["/edx/bin/edxapp-syncdb-lms"], "delta": "0:00:02.366175", "end": "2015-03-05 11:03:45.955291", "item": "lms
", "rc": 1, "start": "2015-03-05 11:03:43.589116", "warnings": []}
stderr: warning: unable to access '/root/.config/git/attributes': Permission denied
Traceback (most recent call last):
  File "manage.py", line 111, in <module>
    startup = importlib.import_module(edx_args.startup)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/edx/app/edxapp/edx-platform/lms/startup.py", line 17, in <module>
    from util import keyword_substitution
  File "/edx/app/edxapp/edx-platform/common/djangoapps/util/keyword_substitution.py", line 24, in <module>
    from xmodule.modulestore.django import modulestore
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/modulestore/django.py", line 27, in <module>
    import xblock.reference.plugins
  File "/edx/app/edxapp/venvs/edxapp/src/xblock/xblock/reference/plugins.py", line 11, in <module>
    from djpyfs import djpyfs  # pylint: disable=import-error
  File "/edx/app/edxapp/venvs/edxapp/src/djpyfs/djpyfs/djpyfs.py", line 31, in <module>
    if djfs_settings['type'] == 'osfs':
TypeError: string indices must be integers

<127.0.0.1> 
<127.0.0.1> IdentityFile=/home/axil/ellak/edx/configuration/vagrant/base/devstack/.vagrant/machines/default/virtualbox/private_key ConnectTimeout=10 KbdInteractiveAuth$
ntication=no PasswordAuthentication=no UserKnownHostsFile=/dev/null User=vagrant ControlPath=/home/axil/.ansible/cp/ansible-ssh-%h-%p-%r PreferredAuthentications=gssap$
-with-mic,gssapi-keyex,hostbased,publickey StrictHostKeyChecking=no ControlMaster=auto Port=2222 ControlPersist=60s
<127.0.0.1> 
<127.0.0.1> IdentityFile=/home/axil/ellak/edx/configuration/vagrant/base/devstack/.vagrant/machines/default/virtualbox/private_key ConnectTimeout=10 KbdInteractiveAuth$
ntication=no 'sudo -k && sudo -H -S -p "[sudo via ansible, key=fcdfrtsepulirmzapteskmhimdgsfdag] password: " -u root /bin/sh -c '"'"'echo SUDO-SUCCESS-fcdfrtsepulirmza$
teskmhimdgsfdag; LANG=en_US.UTF-8 DB_MIGRATION_PASS=password EDX_PLATFORM_SETTINGS_OVERRIDE=aws_migrate LC_CTYPE=en_US.UTF-8 DB_MIGRATION_USER=migrate /usr/bin/python $
home/vagrant/.ansible/tmp/ansible-tmp-1425553426.01-157827929557459/command; rm -rf /home/vagrant/.ansible/tmp/ansible-tmp-1425553426.01-157827929557459/ >/dev/null 2>$
1'"'"'' PasswordAuthentication=no UserKnownHostsFile=/dev/null User=vagrant ControlPath=/home/axil/.ansible/cp/ansible-ssh-%h-%p-%r PreferredAuthentications=gssapi-wit$
-mic,gssapi-keyex,hostbased,publickey StrictHostKeyChecking=no ControlMaster=auto Port=2222 ControlPersist=60s


failed: [default] => (item=cms) => {"changed": true, "cmd": ["/edx/bin/edxapp-syncdb-cms"], "delta": "0:00:02.303600", "end": "2015-03-05 11:03:48.561125", "item": "cm$
", "rc": 1, "start": "2015-03-05 11:03:46.257525", "warnings": []}
stderr: 2015-03-05 06:03:48,316 INFO 19130 [dd.dogapi] dog_stats_api.py:66 - Initializing dog api to use statsd: localhost, 8125
Traceback (most recent call last):
  File "manage.py", line 112, in <module>
    startup.run()
  File "/edx/app/edxapp/edx-platform/cms/startup.py", line 20, in run
    autostartup()
  File "/edx/app/edxapp/edx-platform/common/lib/django_startup.py", line 16, in autostartup
    mod = import_module(app + '.startup')
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/edx/app/edxapp/edx-platform/common/djangoapps/static_replace/__init__.py", line 8, in <module>
    from xmodule.modulestore.django import modulestore
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/modulestore/django.py", line 27, in <module>
    import xblock.reference.plugins
  File "/edx/app/edxapp/venvs/edxapp/src/xblock/xblock/reference/plugins.py", line 11, in <module>
    from djpyfs import djpyfs  # pylint: disable=import-error
  File "/edx/app/edxapp/venvs/edxapp/src/djpyfs/djpyfs/djpyfs.py", line 31, in <module>
    if djfs_settings['type'] == 'osfs':
TypeError: string indices must be integers

FATAL: all hosts have already failed -- aborting
```

**Comment by feanil** [comment]
The issues is probably with what the value of 'djfs_settings' is set to in
your environment.  It looks like django has pulled in a string instead of a
dictionary which is what it is expecting.

**Comment by axilleas** [comment]
Thanks! Any clue how to fix this?

**Comment by feanil** [comment]
You'll have to look at the overrides you're using for the djfs_settings, the defaults are set here: https://github.com/edx/configuration/blob/master/playbooks/roles/edxapp/defaults/main.yml#L21

**Comment by axilleas** [comment]
I wasn't using any overrides, just ran `ansible-playbook vagrant-devstack.yml`.

I was running the playbooks remotely. I tried to run it locally and it worked eventually! I guess it was something wrong with the path, since the [edxapp-syncdb-cms](https://github.com/edx/configuration/blob/master/playbooks/roles/edxapp/templates/edx/bin/edxapp-syncdb-cms.j2) was calling it.

**Comment by lvnilesh** [comment]
What fixed the issue?

I am running into this and can't find a way to resolve.

```
python /edx/app/edxapp/edx-platform/manage.py lms syncdb --migrate --settings aws
Traceback (most recent call last):
  File "/edx/app/edxapp/edx-platform/manage.py", line 111, in <module>
    startup = importlib.import_module(edx_args.startup)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/edx/app/edxapp/edx-platform/lms/startup.py", line 17, in <module>
    from util import keyword_substitution
  File "/edx/app/edxapp/edx-platform/common/djangoapps/util/keyword_substitution.py", line 24, in <module>
    from xmodule.modulestore.django import modulestore
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/modulestore/django.py", line 27, in <module>
    import xblock.reference.plugins
  File "/edx/app/edxapp/venvs/edxapp/src/xblock/xblock/reference/plugins.py", line 11, in <module>
    from djpyfs import djpyfs  # pylint: disable=import-error
  File "/edx/app/edxapp/venvs/edxapp/src/djpyfs/djpyfs/djpyfs.py", line 31, in <module>
    if djfs_settings['type'] == 'osfs':
TypeError: string indices must be integers
```

**Comment by axilleas** [comment]
@lvnilesh I ssh'ed in the VM and ran ansible from there locally.

**Comment by brucellino** [comment]
Hi, just wanted to add my voice to this (@ricceri and @mtorrisi) - we are using the Ansible playbooks to configure the host locally, and are having the same error : 

``` python
     if djfs_settings['type'] == 'osfs':
     TypeError: string indices must be integers
```

We think this has something to do with "storage" ... ie it can't migrate something from somewhere to somewhere else.

Sorry to be so vague, we're still trying to understand this, but the solution of logging into the machine and setting things up locally is not working for us.

**Comment by brucellino** [comment]
Ok, I think that the issue is that the tasks to get the S3 url and initial data are being skipped, because we don't set these variables. In fact, we're running the configuration on a standalone machine. So, we have no demo data to create the demo course.

The question is then - how do we get the demo data ?

**Comment by FremanZhang** [comment]
Is there any solution could share to us on fixing this issue?
