### ISSUE TITLE
syncdb and migrate fails

### ISSUE THREAD

**Issue by brucellino** [openedx-unsupported/configuration#2066]
Hello, 

Using the Ansible playbooks for a standalone  Ubuntu sandbox installation, we get 

```
TASK: [edxapp | syncdb and migrate] ******************************************* 
failed: [localhost] => (item=lms) => {"changed": true, "cmd": ["/edx/bin/edxapp-syncdb-lms"], "delta": "0:00:01.142734", "end": "2015-05-29 11:42:14.129612", "item": "lms", "rc": 1, "start": "2015-05-29 11:42:12.986878", "warnings": []}
stderr: Traceback (most recent call last):
  File "manage.py", line 111, in <module>
    startup = importlib.import_module(edx_args.startup)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/edx/app/edxapp/edx-platform/lms/startup.py", line 10, in <module>
    settings.INSTALLED_APPS  # pylint: disable=pointless-statement
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/functional.py", line 184, in inner
    self._setup()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/conf/__init__.py", line 42, in _setup
    self._wrapped = Settings(settings_module)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/conf/__init__.py", line 135, in __init__
    logging_config_func(self.LOGGING)
  File "/usr/lib/python2.7/logging/config.py", line 794, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/lib/python2.7/logging/config.py", line 576, in configure
    '%r: %s' % (name, e))
ValueError: Unable to configure handler 'local': [Errno 2] No such file or directory
failed: [localhost] => (item=cms) => {"changed": true, "cmd": ["/edx/bin/edxapp-syncdb-cms"], "delta": "0:00:01.394784", "end": "2015-05-29 11:42:15.593045", "item": "cms", "rc": 1, "start": "2015-05-29 11:42:14.198261", "warnings": []}
stderr: Traceback (most recent call last):
  File "manage.py", line 111, in <module>
    startup = importlib.import_module(edx_args.startup)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/edx/app/edxapp/edx-platform/cms/startup.py", line 8, in <module>
    settings.INSTALLED_APPS  # pylint: disable=pointless-statement
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/functional.py", line 184, in inner
    self._setup()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/conf/__init__.py", line 42, in _setup
    self._wrapped = Settings(settings_module)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/conf/__init__.py", line 135, in __init__
    logging_config_func(self.LOGGING)
  File "/usr/lib/python2.7/logging/config.py", line 794, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/lib/python2.7/logging/config.py", line 576, in configure
    '%r: %s' % (name, e))
ValueError: Unable to configure handler 'local': [Errno 2] No such file or directory
```

Where can I find or set the local settings ?

**Comment by feanil** [comment]
Hello, what was the actual command you ran?  The logging handlers are here if you need to debug it more: https://github.com/edx/edx-platform/blob/master/openedx/core/lib/logsettings.py

**Comment by chenshuchuan** [comment]
When I run 

```
sudo ansible-playbook -c local ./edx_sandbox.yml -i "localhost," $EXTRA_VARS
```

I also encountered this problem

**Comment by feanil** [comment]
What is $EXTRA_VARS?  It seems like it's screwing up the logging config?

**Comment by pipisong** [comment]
As I following this guide: https://github.com/edx/configuration/wiki/edX-Ubuntu-12.04-64-bit-Installation
When I run
cd /var/tmp/configuration/playbooks && sudo ansible-playbook -c local ./edx_sandbox.yml -i "localhost,"
I also got this problem.
Does anyone have any clue how to fix this? Thanks.

**Comment by nedbat** [comment]
Sorry we have left this issue untended for so long.  GitHub issues are not meant for support questions.  Please use the [mailing list](https://groups.google.com/forum/#!forum/openedx-ops) or [Slack channels](https://open.edx.org/blog/open-edx-slack) to get help.

**Comment by regisb** [comment]
For the record, in docker images this issue is caused by the fact that `rsyslogd` is not running. As a consequence, `/dev/log` does not exist, and logging configuration fails. Solution is simply to install `rsyslog` (`apt install rsyslog`) and then to run `rsyslogd`.
