### ISSUE TITLE
Error installing edX Ubuntu 12.04 64 bit 

### ISSUE THREAD

**Issue by mtorrisi** [openedx-unsupported/configuration#2069]
Hello everyone,

I'm facing the following problem installing edX on a fresh Ubuntu 12.04:

```
TASK: [edxapp | gather  static assets with paver] ***************************** 
changed: [localhost] => (item=lms)
failed: [localhost] => (item=cms) => {"changed": true, "cmd": "SERVICE_VARIANT=cms paver update_assets cms --settings=aws ", "delta": "0:10:38.009118", "end": "2015-05-29 18:12:41.211295", "item": "cms", "rc": 1, "start": "2015-05-29 18:02:03.202177"}
stderr: 2015-05-29 12:02:40,490 INFO 23968 [dd.dogapi] dog_stats_api.py:66 - Initializing dog api to use statsd: localhost, 8125
DEPRECATION WARNING on line 13 of lms/static/sass/views/_login-register.scss:
Assigning to global variable "$grid-columns" by default is deprecated.
In future versions of Sass, this will create a new local variable.
If you want to assign to the global variable, use "$grid-columns: 12 !global" instead.
Note that this will be incompatible with Sass 3.2.

DEPRECATION WARNING on line 21 of lms/static/sass/views/_homepage.scss:
Assigning to global variable "$layout-direction" by default is deprecated.
In future versions of Sass, this will create a new local variable.
If you want to assign to the global variable, use "$layout-direction: "RTL" !global" instead.
Note that this will be incompatible with Sass 3.2.

DEPRECATION WARNING on line 13 of lms/static/sass/views/_login-register.scss:
Assigning to global variable "$grid-columns" by default is deprecated.
In future versions of Sass, this will create a new local variable.
If you want to assign to the global variable, use "$grid-columns: 12 !global" instead.
Note that this will be incompatible with Sass 3.2.

2015-05-29 12:03:56,366 INFO 24029 [dd.dogapi] dog_stats_api.py:66 - Initializing dog api to use statsd: localhost, 8125
Traceback (most recent call last):
  File "manage.py", line 116, in <module>
    execute_from_command_line([sys.argv[0]] + django_args)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 443, in execute_from_command_line
    utility.execute()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/base.py", line 196, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/base.py", line 232, in execute
    output = self.handle(*args, **options)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/base.py", line 371, in handle
    return self.handle_noargs(**options)
  File "/edx/app/edxapp/venvs/edxapp/src/django-staticfiles/staticfiles/management/commands/collectstatic.py", line 169, in handle_noargs
    collected = self.collect()
  File "/edx/app/edxapp/venvs/edxapp/src/django-staticfiles/staticfiles/management/commands/collectstatic.py", line 126, in collect
    for original_path, processed_path, processed in processor:
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/require/storage.py", line 108, in post_process
    baseUrl = require_settings.REQUIRE_BASE_URL,
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/require/storage.py", line 52, in run_optimizer
    raise OptimizationError("Error while running r.js optimizer.")
require.storage.OptimizationError: Error while running r.js optimizer.
stdout: ---> pavelib.assets.update_assets
---> pavelib.prereqs.install_ruby_prereqs
---> pavelib.prereqs.install_node_prereqs
python manage.py cms --settings=aws preprocess_assets
xmodule_assets common/static/xmodule
---> pavelib.assets.compile_coffeescript
node_modules/.bin/coffee --compile `find /edx/app/edxapp/edx-platform/lms /edx/app/edxapp/edx-platform/cms /edx/app/edxapp/edx-platform/common -type f -name "*.coffee"`
---> pavelib.assets.compile_sass
sass --style compressed  --cache-location /tmp/sass-cache --load-path ./common/static/sass --update -E utf-8 */static/sass common/static
      write lms/static/sass/lms-course-rtl.css
      write lms/static/sass/lms-course.css
      write lms/static/sass/lms-footer-rtl.css
      write lms/static/sass/lms-footer.css
      write lms/static/sass/lms-main-rtl.css
      write lms/static/sass/lms-main.css
python manage.py cms --settings=aws collectstatic --noinput > /dev/null


Captured Task Output:
---------------------

---> pavelib.assets.update_assets
---> pavelib.prereqs.install_ruby_prereqs
---> pavelib.prereqs.install_node_prereqs
python manage.py cms --settings=aws preprocess_assets
xmodule_assets common/static/xmodule
---> pavelib.assets.compile_coffeescript
node_modules/.bin/coffee --compile `find /edx/app/edxapp/edx-platform/lms /edx/app/edxapp/edx-platform/cms /edx/app/edxapp/edx-platform/common -type f -name "*.coffee"`
---> pavelib.assets.compile_sass
sass --style compressed  --cache-location /tmp/sass-cache --load-path ./common/static/sass --update -E utf-8 */static/sass common/static
python manage.py cms --settings=aws collectstatic --noinput > /dev/null

Build failed running pavelib.assets.update_assets: Subprocess return code: 1

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/courses/edx_sandbox.retry

localhost                  : ok=261  changed=133  unreachable=0    failed=1
```

I followed this instructions https://github.com/edx/configuration/wiki/edX-Ubuntu-12.04-64-bit-Installation

Thanks in advance for you help

**Comment by mtorrisi** [comment]
I'm sorry for the previous issue. The problem was related to the machine resources, I had allocated just 1 GB. I increased the RAM and the process went well.

Sorry again. You can close the issue.
