### ISSUE TITLE
[edxapp | syncdb and migrate] failed when installing with Ubuntu-12.04-64-bit-Installation

### ISSUE THREAD

**Issue by pipisong** [openedx-unsupported/configuration#2093]
Hello, I'm following this guide: https://github.com/edx/configuration/wiki/edX-Ubuntu-12.04-64-bit-Installation，and getting the "string indices must be integers" error as follows.

TASK: [edxapp | syncdb and migrate] *******************************************
failed: [localhost] => (item=lms) => {"changed": true, "cmd": "/edx/app/edxapp/venvs/edxapp/bin/python manage.py lms syncdb --migrate --noinput --settings=aws_migrate", "delta": "0:00:01.282551", "end": "2015-06-14 19:20:14.890059", "item": "lms", "rc": 1, "start": "2015-06-14 19:20:13.607508", "warnings": []}
stderr: Traceback (most recent call last):
  File "manage.py", line 112, in <module>
    startup.run()
  File "/edx/app/edxapp/edx-platform/lms/startup.py", line 28, in run
    autostartup()
  File "/edx/app/edxapp/edx-platform/openedx/core/lib/django_startup.py", line 16, in autostartup
    mod = import_module(app + '.startup')
  File "/usr/lib/python2.7/importlib/**init**.py", line 37, in import_module
    **import**(name)
  File "/edx/app/edxapp/edx-platform/common/djangoapps/static_replace/**init**.py", line 8, in <module>
    from xmodule.modulestore.django import modulestore
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/modulestore/django.py", line 29, in <module>
    import xblock.reference.plugins
  File "/edx/app/edxapp/venvs/edxapp/src/xblock/xblock/reference/plugins.py", line 11, in <module>
    from djpyfs import djpyfs  # pylint: disable=import-error
  File "/edx/app/edxapp/venvs/edxapp/src/djpyfs/djpyfs/djpyfs.py", line 31, in <module>
    if djfs_settings['type'] == 'osfs':
TypeError: string indices must be integers
failed: [localhost] => (item=cms) => {"changed": true, "cmd": "/edx/app/edxapp/venvs/edxapp/bin/python manage.py cms syncdb --migrate --noinput --settings=aws_migrate", "delta": "0:00:01.262379", "end": "2015-06-14 19:20:16.341241", "item": "cms", "rc": 1, "start": "2015-06-14 19:20:15.078862", "warnings": []}
stderr: Traceback (most recent call last):
  File "manage.py", line 112, in <module>
    startup.run()
  File "/edx/app/edxapp/edx-platform/cms/startup.py", line 20, in run
    autostartup()
  File "/edx/app/edxapp/edx-platform/openedx/core/lib/django_startup.py", line 16, in autostartup
    mod = import_module(app + '.startup')
  File "/usr/lib/python2.7/importlib/**init**.py", line 37, in import_module
    **import**(name)
  File "/edx/app/edxapp/edx-platform/cms/djangoapps/contentstore/**init**.py", line 2, in <module>
    import contentstore.signals
  File "/edx/app/edxapp/edx-platform/cms/djangoapps/contentstore/signals.py", line 7, in <module>
    from xmodule.modulestore.django import SignalHandler
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/modulestore/django.py", line 29, in <module>
    import xblock.reference.plugins
  File "/edx/app/edxapp/venvs/edxapp/src/xblock/xblock/reference/plugins.py", line 11, in <module>
    from djpyfs import djpyfs  # pylint: disable=import-error
  File "/edx/app/edxapp/venvs/edxapp/src/djpyfs/djpyfs/djpyfs.py", line 31, in <module>
    if djfs_settings['type'] == 'osfs':
TypeError: string indices must be integers

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/home/edx/edx_sandbox.retry

localhost                  : ok=191  changed=40   unreachable=0    failed=1  

Does anyone have any clue how to fix this? Thanks.

**Comment by nedbat** [comment]
Sorry we have left this issue untended for so long.  GitHub issues are not meant for support questions.  Please use the [mailing list](https://groups.google.com/forum/#!forum/openedx-ops) or [Slack channels](https://open.edx.org/blog/open-edx-slack) to get help.
