### ISSUE TITLE
Doesn't work upload profile images.

### ISSUE THREAD

**Issue by eemirtekin** [openedx-unsupported/configuration#2181]
Hello All

I installed edx on ubuntu 12.04 succesfully.
I try upload profile image but got error.

Thanks in advance.

![screen shot 2015-08-03 at 13 29 25](https://cloud.githubusercontent.com/assets/1687805/9035792/d4ce2ee8-39e3-11e5-9fbe-31cdffc58c63.png)

``` python
Aug  3 13:20:54 dom [service_variant=lms][root][env:sandbox] ERROR [dom  23258] [exceptions.py:9] - Uncaught exception from <class 'django.core.handlers.wsgi.WSGIHandler'>
Traceback (most recent call last):
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 109, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/rest_framework/compat.py", line 137, in view
    return self.dispatch(request, *args, **kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 77, in wrapped_view
    return view_func(*args, **kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/rest_framework/views.py", line 400, in dispatch
    response = self.handle_exception(exc)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/rest_framework/views.py", line 397, in dispatch
    response = handler(request, *args, **kwargs)
  File "/edx/app/edxapp/edx-platform/openedx/core/djangoapps/profile_images/views.py", line 111, in post
    create_profile_images(uploaded_file, profile_image_names)
  File "/edx/app/edxapp/edx-platform/openedx/core/djangoapps/profile_images/images.py", line 149, in create_profile_images
    storage.save(name, scaled_image_file)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/files/storage.py", line 45, in save
    name = self._save(name, content)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/files/storage.py", line 167, in _save
    os.makedirs(directory)
  File "/edx/app/edxapp/venvs/edxapp/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/edx/var/edxapp/media/profile-images'
Aug  3 13:20:54 dom [service_variant=lms][django.request][env:sandbox] ERROR [dom  23258] [base.py:213] - Internal Server Error: /api/profile_images/v1/eemirtekin/upload
Traceback (most recent call last):
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 109, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/rest_framework/compat.py", line 137, in view
    return self.dispatch(request, *args, **kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 77, in wrapped_view
    return view_func(*args, **kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/rest_framework/views.py", line 400, in dispatch
    response = self.handle_exception(exc)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/rest_framework/views.py", line 397, in dispatch
    response = handler(request, *args, **kwargs)
  File "/edx/app/edxapp/edx-platform/openedx/core/djangoapps/profile_images/views.py", line 111, in post
    create_profile_images(uploaded_file, profile_image_names)
  File "/edx/app/edxapp/edx-platform/openedx/core/djangoapps/profile_images/images.py", line 149, in create_profile_images
    storage.save(name, scaled_image_file)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/files/storage.py", line 45, in save
    name = self._save(name, content)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/files/storage.py", line 167, in _save
    os.makedirs(directory)
  File "/edx/app/edxapp/venvs/edxapp/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/edx/var/edxapp/media/profile-images'
```

**Comment by eemirtekin** [comment]
I have created profile-images folder under this  /edx/var/edxapp/media
Web user (www-data) permission was given for this folder( profile-images)

```
root@dom:/edx/var/edxapp/media# ll
total 84
drwxr-xr-x 3 edxapp   edxapp    4096 Aug  3 13:36 ./
drwxr-xr-x 8 edxapp   www-data  4096 Aug  3 12:16 ../
-rwxr-xr-x 1 edxapp   edxapp   20814 Aug  3 12:16 honor.png*
-rwxr-xr-x 1 edxapp   edxapp   21855 Aug  3 12:16 professional.png*
drwxrwxrwx 2 www-data www-data  4096 Aug  3 13:41 profile-images/
-rwxr-xr-x 1 edxapp   edxapp   21855 Aug  3 12:16 verified.png*
```

After that I got error below:

```
Aug  3 13:38:16 dom [service_variant=lms][django.request][env:sandbox] ERROR [dom  23240] [base.py:213] - Internal Server Error: /api/profile_images/v1/eemirtekin/upload
Traceback (most recent call last):
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 109, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/rest_framework/compat.py", line 137, in view
    return self.dispatch(request, *args, **kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 77, in wrapped_view
    return view_func(*args, **kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/rest_framework/views.py", line 400, in dispatch
    response = self.handle_exception(exc)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/rest_framework/views.py", line 397, in dispatch
    response = handler(request, *args, **kwargs)
  File "/edx/app/edxapp/edx-platform/openedx/core/djangoapps/profile_images/views.py", line 111, in post
    create_profile_images(uploaded_file, profile_image_names)
  File "/edx/app/edxapp/edx-platform/openedx/core/djangoapps/profile_images/images.py", line 149, in create_profile_images
    storage.save(name, scaled_image_file)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/files/storage.py", line 45, in save
    name = self._save(name, content)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/files/storage.py", line 191, in _save
    fd = os.open(full_path, os.O_WRONLY | os.O_CREAT | os.O_EXCL | getattr(os, 'O_BINARY', 0))
OSError: [Errno 13] Permission denied: '/edx/var/edxapp/media/profile-images/4ef36d2a60674a2f51530382868abfa9_120.jpg'
Aug  3 13:41:53 dom [service_variant=lms][openedx.core.djangoapps.profile_images.views][env:sandbox] INFO [dom  23253] [views.py:118] - Generated and uploaded images ['4ef36d2a60674a2f51530382868abfa9_120.jpg', '4ef36d2a60674a2f51530382868abfa9_50.jpg', '4ef36d2a60674a2f51530382868abfa9_500.$
```

![screen shot 2015-08-03 at 13 51 45](https://cloud.githubusercontent.com/assets/1687805/9036213/f790908e-39e7-11e5-99bb-43410d99f9d3.png)

**Comment by RizRiyz** [comment]
I also have same problem, any solution?

**Comment by eemirtekin** [comment]
Hello @ariestiyansyah 
named-release/cypress is a stable, you can use this version.
Have a nice day.

**Comment by RizRiyz** [comment]
I already have birch in production and do some configuration.

Its Ok to update from the birch? If yes how to do that?

Thanks.

**Comment by eemirtekin** [comment]
Hello

Updating Versions using edX repos

Use the /edx/bin/update to update repo versions on the server.

Allowed repo names [edx-platform, xqueue, cs_comments_service, xserver, ease, edx-ora, configuration, read-only-certificate-code]

Examples:

sudo /edx/bin/update edx-platform master - change edx-platform to use the latest on the master branch
sudo /edx/bin/update cs_comments_service master - change the forums service to use the latest on the master branch

**Comment by gilanguling** [comment]
so, i just need update update repo using cypres? usually I use master or release branch but the problem still exist

**Comment by secure4th** [comment]
Hi.

this try.
- cd /edx/app/nginx/sites-available
- vi lms

# Insert

  location ~ ^/media/(?P<file>.*) 
{
    root /edx/var/edxapp;
    try_files /media/$file =404;

# }

save and 
- sudo service nginx restart

it work !!!

![2015-09-15_23-25-04](https://cloud.githubusercontent.com/assets/14260177/9882854/0d81703a-5c01-11e5-91ce-8ba3931c54ee.png)

**Comment by reroes** [comment]
Excellent solution... 
good for me....
 thank.

**Comment by reroes** [comment]
little change:

location ~ ^/media/(?P<file>.*) 
{
root /edx/var/edxapp;
try_files /media/$file =404;

}
