### ISSUE TITLE
Errors in installing Cypress RC4

### ISSUE THREAD

**Issue by ahmadio** [openedx-unsupported/configuration#2202]
I'm having those errors while installing Cypress RC4 on amazon on a 12.04 ubuntu

I retried installing many times with no luck and got two  different errors.

first

```
TASK: [insights | create nodeenv] *********************************************
failed: [localhost] => {"changed": true, "cmd": "/edx/app/insights/venvs/insights/bin/nodeenv /edx/app/insights/nodeenvs/insights", "delta":

 "0:01:38.751620", "end": "2015-08-10 15:50:49.116986", "rc": 1, "start": "2015-08-10 15:49:10.365366", "warnings": []}

stderr:  * Install node.js (0.12.7-RC1) Traceback (most recent call last):

  File "/edx/app/insights/venvs/insights/bin/nodeenv", line 9, in <module>

    load_entry_point('nodeenv==0.11.1', 'console_scripts', 'nodeenv')()

  File "/edx/app/insights/venvs/insights/local/lib/python2.7/site-packages/nodeenv.py", line 765, in main

    create_environment(env_dir, opt)

  File "/edx/app/insights/venvs/insights/local/lib/python2.7/site-packages/nodeenv.py", line 674, in create_environment

    install_node(env_dir, src_dir, opt)

  File "/edx/app/insights/venvs/insights/local/lib/python2.7/site-packages/nodeenv.py", line 556, in install_node

    download_node(node_url, src_dir, env_dir, opt)

  File "/edx/app/insights/venvs/insights/local/lib/python2.7/site-packages/nodeenv.py", line 461, in download_node

    callit(cmd, opt.verbose, True, env_dir)

  File "/edx/app/insights/venvs/insights/local/lib/python2.7/site-packages/nodeenv.py", line 420, in callit

    % (cmd_desc, proc.returncode))

OSError: Command curl --silent -L http://nodejs.org/di...e-v0.12.7-RC1.tar.gz | tar xzf - -C /edx/app/insights/nodeenvs/insights/src --exclu

de ChangeLog --exclude LICENSE --exclude README.md failed with error code 2



FATAL: all hosts have already failed -- aborting



PLAY RECAP ********************************************************************

           to retry, use: --limit @/home/ubuntu/edx_sandbox.retry



localhost                  : ok=376  changed=255  unreachable=0    failed=1
```

and this one

```

TASK: [xqwatcher | update supervisor configuration] *************************** 

changed: [localhost]



TASK: [xqwatcher | restart xqwatcher] ***************************************** 

failed: [localhost] => {"failed": true}

msg: xqwatcher: stopped

xqwatcher: ERROR (abnormal termination)





FATAL: all hosts have already failed -- aborting



PLAY RECAP ******************************************************************** 

           to retry, use: --limit @/home/ubuntu/edx_sandbox.retry



localhost                  : ok=571  changed=396  unreachable=0    failed=1   
```

I'm installing on single m3.2xlarge instance

**Comment by eemirtekin** [comment]
Hello
I have same problem

TASK: [insights | create nodeenv] ********************************************\* 
failed: [localhost] => {"changed": true, "cmd": "/edx/app/insights/venvs/insights/bin/nodeenv /edx/app/insights/nodeenvs/insights", "delta": "0:04:26.258789", "end": "2015-08-19 18:04:33.045417", "rc": 1, "start": "2015-08-19 18:00:06.786628", "warnings": []}
stderr:  \* Install node.js (-RC1) Traceback (most recent call last):
  File "/edx/app/insights/venvs/insights/bin/nodeenv", line 9, in <module>
    load_entry_point('nodeenv==0.11.1', 'console_scripts', 'nodeenv')()
  File "/edx/app/insights/venvs/insights/local/lib/python2.7/site-packages/nodeenv.py", line 765, in main
    create_environment(env_dir, opt)
  File "/edx/app/insights/venvs/insights/local/lib/python2.7/site-packages/nodeenv.py", line 674, in create_environment
    install_node(env_dir, src_dir, opt)
  File "/edx/app/insights/venvs/insights/local/lib/python2.7/site-packages/nodeenv.py", line 556, in install_node
    download_node(node_url, src_dir, env_dir, opt)
  File "/edx/app/insights/venvs/insights/local/lib/python2.7/site-packages/nodeenv.py", line 461, in download_node
    callit(cmd, opt.verbose, True, env_dir)
  File "/edx/app/insights/venvs/insights/local/lib/python2.7/site-packages/nodeenv.py", line 420, in callit
    % (cmd_desc, proc.returncode))
OSError: Command curl --silent -L http://nodejs.org/dist/node-v-RC1.tar.gz | tar xzf - -C /edx/app/insights/nodeenvs/insights/src --exclude ChangeLog --exclude LICENSE --exclude README.md failed with error code 2

FATAL: all hosts have already failed -- aborting

PLAY RECAP *******************************************************************\* 
           to retry, use: --limit @/root/edx_sandbox.retry

localhost                  : ok=378  changed=258  unreachable=0    failed=1

**Comment by nedbat** [comment]
Sorry we have left this issue untended for so long.  GitHub issues are not meant for support questions.  Please use the [mailing list](https://groups.google.com/forum/#!forum/openedx-ops) or [Slack channels](https://open.edx.org/blog/open-edx-slack) to get help.
