### ISSUE TITLE
AWS ami-3486a266 got error on [install python pre-requirements]

### ISSUE THREAD

**Issue by caosbad** [openedx-unsupported/configuration#2249]
Hi:
I got a error named `ImportError: No module named _markerlib` when I was install Edx in a AWS (ami-3486a266) ,then I used pip to install the setuptools  again, couldnot resolve the problem.

**Comment by nrichand** [comment]
Same for me with the AMI ami-aa76d0dd , here is the stacktrace : 

TASK: [edxapp | install python pre-requirements] *****************************\* 
failed: [localhost] => {"cmd": "/edx/app/edxapp/venvs/edxapp/bin/pip install -i https://pypi.python.org/simple -r /edx/app/edxapp/edx-platform/requirements/edx/pre.txt", "failed": true, "item": ""}
msg: stdout: Downloading/unpacking setuptools==18.0.1 (from -r /edx/app/edxapp/edx-platform/requirements/edx/pre.txt (line 9))
Requirement already satisfied (use --upgrade to upgrade): numpy==1.6.2 in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from -r /edx/app/edxapp/edx-platform/requirements/edx/pre.txt (line 13))
Downloading/unpacking pip==6.0.8 (from -r /edx/app/edxapp/edx-platform/requirements/edx/pre.txt (line 16))
Downloading/unpacking Cython==0.21.2 (from -r /edx/app/edxapp/edx-platform/requirements/edx/pre.txt (line 19))
  Running setup.py (path:/edx/app/edxapp/venvs/edxapp/build/Cython/setup.py) egg_info for package Cython
    Compiling module Cython.Plex.Scanners ...
    Compiling module Cython.Plex.Actions ...
    Compiling module Cython.Compiler.Lexicon ...
    Compiling module Cython.Compiler.Scanning ...
    Compiling module Cython.Compiler.Parsing ...
    Compiling module Cython.Compiler.Visitor ...
    Compiling module Cython.Compiler.FlowControl ...
    Compiling module Cython.Compiler.Code ...
    Compiling module Cython.Runtime.refnanny ...
    Compiling module Cython.Tempita._tempita ...

```
warning: no files found matching '*.pyx' under directory 'Cython/Debugger/Tests'
warning: no files found matching '*.pxd' under directory 'Cython/Debugger/Tests'
warning: no files found matching '*.h' under directory 'Cython/Debugger/Tests'
warning: no files found matching '*.pxd' under directory 'Cython/Utility'
```

Installing collected packages: setuptools, pip, Cython
  Found existing installation: distribute 0.6.49
    Uninstalling distribute:
      Successfully uninstalled distribute
  Rolling back uninstall of distribute
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pip/commands/install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pip/req.py", line 1435, in install
    requirement.install(install_options, global_options, _args, *_kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pip/req.py", line 671, in install
    self.move_wheel_files(self.source_dir, root=root)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pip/req.py", line 901, in move_wheel_files
    pycompile=self.pycompile,
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pip/wheel.py", line 141, in move_wheel_files
    scheme = distutils_scheme(name, user=user, home=home, root=root)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pip/locations.py", line 146, in distutils_scheme
    d = Distribution({'name': dist_name})
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/setuptools/dist.py", line 225, in **init**
    _Distribution.__init__(self,attrs)
  File "/usr/lib/python2.7/distutils/dist.py", line 287, in **init**
    self.finalize_options()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/setuptools/dist.py", line 257, in finalize_options
    ep.require(installer=self.fetch_build_egg)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pkg_resources.py", line 2099, in require
    working_set.resolve(self.dist.requires(self.extras),env,installer))
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pkg_resources.py", line 2309, in requires
    dm = self._dep_map
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pkg_resources.py", line 2538, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pkg_resources.py", line 2555, in _compute_dependencies
    from _markerlib import compile as compile_marker
ImportError: No module named _markerlib

Storing debug log for failure in /edx/app/edxapp/.pip/pip.log

**Comment by fisharebest** [comment]
@ImCaos and @nrichand
Did you find a solution to this?

**Comment by nrichand** [comment]
@fisharebest nope sorry :(

**Comment by fisharebest** [comment]
I've found a workaround (appears to work for me).

```
sudo -u edxapp rm -rf /edx/app/edxapp/venvs/edxapp
```

It is actually documented here https://openedx.atlassian.net/wiki/display/OpenOPS/Potential+Problems+Migrating+from+Birch+to+Cypress but it is not obvious from the error message that this is the same issue.

**Comment by DivyaMangotra** [comment]
I am getting the same error. Were you able to resolve it?

**Comment by fisharebest** [comment]
> I am getting the same error. Were you able to resolve it?

Yes - as I posted above.  Delete the virtual environment and allow the script to recreate it.

`sudo -u edxapp rm -rf /edx/app/edxapp/venvs/edxapp`

As explained in the link, the problem comes when the installer replaces `distribute` with `setuptools`.

**Comment by michalmikolajczyk** [comment]
bumped into the same issue today, us-east-1 AMI

the solution worked! +1

**Comment by nedbat** [comment]
Sorry we have left this issue untended for so long.  GitHub issues are not meant for support questions.  Please use the [mailing list](https://groups.google.com/forum/#!forum/openedx-ops) or [Slack channels](https://open.edx.org/blog/open-edx-slack) to get help.
