### ISSUE TITLE
Ubuntu 12.04 full stack edX server installation issue

### ISSUE THREAD

**Issue by SuperBobby** [openedx-unsupported/configuration#2330]
#### This is my server information

```
 $  cat /etc/*-release | uniq
 DISTRIB_ID=Ubuntu
 DISTRIB_RELEASE=12.04
 DISTRIB_CODENAME=precise
 DISTRIB_DESCRIPTION="Ubuntu 12.04.5 LTS"
 NAME="Ubuntu"
 VERSION="12.04.5 LTS, Precise Pangolin"
 ID=ubuntu
 ID_LIKE=debian
 PRETTY_NAME="Ubuntu precise (12.04.5 LTS)"
 VERSION_ID="12.04"
```
#### Here's the commands I used

```
 $ sudo apt-get update -y
 $ sudo apt-get upgrade -y
 $ sudo reboot
 $ sudo wget https://raw.githubusercontent.com/edx/configuration/master/util/install/sandbox.sh -O - | bash
```
#### I've tried to installation process several times but I failed with following error messages.(Every time I got the same error message.)

TASK: [insights | install bower dependencies] *********************************
failed: [localhost] => {"changed": true, "cmd": ". /edx/app/insights/nodeenvs/insigh   ts/bin/activate && /edx/app/insights/edx_analytics_dashboard/node_modules/.bin/bower    install --production --config.interactive=false", "delta": "0:02:17.808216", "end":    "2015-10-06 14:13:50.907822", "rc": 1, "start": "2015-10-06 14:11:33.099606", "warn   ings": []}
stderr: bower natural-sort#dbf4ca259b327a488bd1d7897fd46d80c414a7e0     invalid-meta    natural-sort is missing "main" entry in bower.json
bower natural-sort#dbf4ca259b327a488bd1d7897fd46d80c414a7e0     invalid-meta natural   -sort is missing "ignore" entry in bower.json
bower cldr-data#26.0.3                                          invalid-meta cldr-da   ta is missing "ignore" entry in bower.json
bower bootstrapaccessibilityplugin#~1.0.3                           mismatch Version    declared in the json (1.0.2) is different than the resolved one (1.0.4)
bower globalize#1.0.0-alpha.17                                  invalid-meta globali   ze is missing "main" entry in bower.json
bower jasmine#~2.0.4                                            invalid-meta jasmine    is missing "main" entry in bower.json
bower jasmine#~2.0.4                                            invalid-meta jasmine    is missing "ignore" entry in bower.json
bower cldrjs#0.4.0                                              invalid-meta cldrjs    is missing "main" entry in bower.json
bower cldrjs#0.4.0                                              invalid-meta cldrjs    is missing "ignore" entry in bower.json
bower datamaps#~0.3.4                                               mismatch Version    declared in the json (0.3.4) is different than the resolved one (0.3.7)
bower cldrjs                                                extra-resolution Unneces   sary resolution: cldrjs#0.4.0
bower                                                                ECMDERR Failed    to execute "./bower-post-install.sh", exit code of #1 /edx/app/insights/edx_analytic   s_dashboard/node_modules/cldr-data-downloader/lib/download.js:59       throw error;          ^  Error: connect ETIMEDOUT 216.97.88.9:80     at Object.exports._errnoExcepti   on (util.js:849:11)     at exports._exceptionWithHostPort (util.js:872:20)     at TC   PConnectWrap.afterConnect [as oncomplete](net.js:1060:14)

Additional error details:
/edx/app/insights/edx_analytics_dashboard/node_modules/cldr-data-downloader/lib/down   load.js:59
      throw error;
      ^

Error: connect ETIMEDOUT 216.97.88.9:80
    at Object.exports._errnoException (util.js:849:11)
    at exports._exceptionWithHostPort (util.js:872:20)
    at TCPConnectWrap.afterConnect [as oncomplete](net.js:1060:14)
stdout: bower natural-sort#dbf4ca259b327a488bd1d7897fd46d80c414a7e0       not-cached    git://github.com/overset/javascript-natural-sort.git#dbf4ca259b327a488bd1d7897fd46d   80c414a7e0

**Comment by SuperBobby** [comment]
#### I got this error messages, too.

TASK: [insights | migrate] ****************************************************
failed: [localhost] => {"changed": true, "cmd": "DB_MIGRATION_USER=migrate DB_MIGR                            ATION_PASS=password /edx/app/insights/venvs/insights/bin/python /edx/app/insights/                            edx_analytics_dashboard/manage.py migrate --noinput", "delta": "0:00:00.249575", "                            end": "2015-10-06 16:39:43.025915", "rc": 1, "start": "2015-10-06 16:39:42.776340"                            , "warnings": []}
stderr: System check identified some issues:

WARNINGS:
?: (1_6.W001) Some project unittests may not execute as expected.
        HINT: Django 1.6 introduced a new default test runner. It looks like this                             project was generated using Django 1.5 or earlier. You should ensure your tests ar                            e all running & behaving as expected. See https://docs.djangoproject.com/en/dev/re                            leases/1.6/#new-test-runner for more information.
Traceback (most recent call last):
  File "/edx/app/insights/edx_analytics_dashboard/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/edx/app/insights/venvs/insights/local/lib/python2.7/site-packages/django/                            core/management/**init**.py", line 385, in execute_from_command_line
    utility.execute()
  File "/edx/app/insights/venvs/insights/local/lib/python2.7/site-packages/django/                            core/management/**init**.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/edx/app/insights/venvs/insights/local/lib/python2.7/site-packages/django/                            core/management/base.py", line 288, in run_from_argv
    self.execute(_args, *_options.**dict**)
  File "/edx/app/insights/venvs/insights/local/lib/python2.7/site-packages/django/                            core/management/base.py", line 338, in execute
    output = self.handle(_args, *_options)
  File "/edx/app/insights/venvs/insights/local/lib/python2.7/site-packages/django/                            core/management/commands/migrate.py", line 63, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/edx/app/insights/venvs/insights/local/lib/python2.7/site-packages/django/                            db/migrations/executor.py", line 17, in **init**
    self.loader = MigrationLoader(self.connection)
  File "/edx/app/insights/venvs/insights/local/lib/python2.7/site-packages/django/                            db/migrations/loader.py", line 49, in **init**
    self.build_graph()
  File "/edx/app/insights/venvs/insights/local/lib/python2.7/site-packages/django/                            db/migrations/loader.py", line 184, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/edx/app/insights/venvs/insights/local/lib/python2.7/site-packages/django/                            db/migrations/recorder.py", line 59, in applied_migrations
    self.ensure_schema()
  File "/edx/app/insights/venvs/insights/local/lib/python2.7/site-packages/django/                            db/migrations/recorder.py", line 49, in ensure_schema
    if self.Migration._meta.db_table in self.connection.introspection.get_table_li                            st(self.connection.cursor()):
  File "/edx/app/insights/venvs/insights/local/lib/python2.7/site-packages/django/                            db/backends/__init__.py", line 167, in cursor
    cursor = utils.CursorWrapper(self._cursor(), self)
  File "/edx/app/insights/venvs/insights/local/lib/python2.7/site-packages/django/                            db/backends/__init__.py", line 138, in _cursor
    self.ensure_connection()
  File "/edx/app/insights/venvs/insights/local/lib/python2.7/site-packages/django/                            db/backends/__init__.py", line 133, in ensure_connection
    self.connect()
  File "/edx/app/insights/venvs/insights/local/lib/python2.7/site-packages/django/                            db/utils.py", line 94, in **exit**
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/edx/app/insights/venvs/insights/local/lib/python2.7/site-packages/django/                            db/backends/**init**.py", line 133, in ensure_connection
    self.connect()
  File "/edx/app/insights/venvs/insights/local/lib/python2.7/site-packages/django/                            db/backends/**init**.py", line 122, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/edx/app/insights/venvs/insights/local/lib/python2.7/site-packages/django/                            db/backends/mysql/base.py", line 472, in get_new_connection
    conn = Database.connect(*_conn_params)
  File "/edx/app/insights/venvs/insights/local/lib/python2.7/site-packages/MySQLdb                            /**init**.py", line 81, in Connect
    return Connection(_args, *_kwargs)
  File "/edx/app/insights/venvs/insights/local/lib/python2.7/site-packages/MySQLdb                            /connections.py", line 193, in **init**
    super(Connection, self).**init**(_args, **kwargs2)
django.db.utils.OperationalError: (1044, "Access denied for user 'migrate'@'localh                            ost' to database 'dashboard'")

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/home/hanjy/edx_sandbox.retry

localhost                  : ok=369  changed=87   unreachable=0    failed=1

**Comment by feanil** [comment]
Yun,

This was a bug in the configuration code that was added in the last week.
A fix was merged in yesterday.  Can you please try again with the latest
configuration code.

-Feanil

**Comment by SuperBobby** [comment]
Feanil, 

Thank you for your comment. 
I tried the 'One step Installation' process again, but it didn't work...
The same error occurred like below.

TASK: [insights | migrate] ****************************************************
failed: [localhost] => {"changed": true, "cmd": "DB_MIGRATION_USER=migrate DB_MIGR ATION_PASS=password /edx/app/insights/venvs/insights/bin/python /edx/app/insights/ edx_analytics_dashboard/manage.py migrate --noinput", "delta": "0:00:00.249575", " end": "2015-10-06 16:39:43.025915", "rc": 1, "start": "2015-10-06 16:39:42.776340" , "warnings": []}
stderr: System check identified some issues:

WARNINGS:
?: (1_6.W001) Some project unittests may not execute as expected.
HINT: Django 1.6 introduced a new default test runner. It looks like this project was generated using Django 1.5 or earlier. You should ensure your tests ar e all running & behaving as expected. See https://docs.djangoproject.com/en/dev/re leases/1.6/#new-test-runner for more information.

It looks like a Django version issue... Is there other ways I would try to solve this problem? I really need edX platform for my research...

**Comment by ivb1960** [comment]
There was a problem with installation Full Stack. The note - such problem wasn't watched till 8.10.2015.

git clone -b release https://github.com/edx/configuration

===========begin=======

TASK: [edxapp | syncdb and migrate] *******************************************
failed: [localhost] => (item=lms) => {"changed": true, "cmd": " /edx/app/edxapp/venvs/edxapp/bin/python manage.py lms syncdb --migrate --noinput --settings=aws_migrate ", "delta": "0:00:02.533670", "end": "2015-10-11 01:25:56.215266", "item": "lms", "rc": 1, "start": "2015-10-11 01:25:53.681596"}
stderr: 2015-10-10 18:25:55,581 INFO 10040 [dd.dogapi] dog_stats_api.py:66 - Initializing dog api to use statsd: localhost, 8125
Traceback (most recent call last):
  File "manage.py", line 116, in <module>
    execute_from_command_line([sys.argv[0]] + django_args)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 443, in execute_from_command_line
    utility.execute()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 261, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 69, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    **import**(name)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/south/management/commands/**init**.py", line 10, in <module>
    import django.template.loaders.app_directories
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/template/loaders/app_directories.py", line 23, in <module>
    raise ImproperlyConfigured('ImportError %s: %s' % (app, e.args[0]))
django.core.exceptions.ImproperlyConfigured: ImportError branding: cannot import name microsite
failed: [localhost] => (item=cms) => {"changed": true, "cmd": " /edx/app/edxapp/venvs/edxapp/bin/python manage.py cms syncdb --migrate --noinput --settings=aws_migrate ", "delta": "0:00:02.001808", "end": "2015-10-11 01:25:58.292048", "item": "cms", "rc": 1, "start": "2015-10-11 01:25:56.290240"}
stderr: 2015-10-10 18:25:57,669 INFO 10086 [dd.dogapi] dog_stats_api.py:66 - Initializing dog api to use statsd: localhost, 8125
Traceback (most recent call last):
  File "manage.py", line 116, in <module>
    execute_from_command_line([sys.argv[0]] + django_args)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 443, in execute_from_command_line
    utility.execute()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 261, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 69, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    **import**(name)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/south/management/commands/**init**.py", line 10, in <module>
    import django.template.loaders.app_directories
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/template/loaders/app_directories.py", line 23, in <module>
    raise ImproperlyConfigured('ImportError %s: %s' % (app, e.args[0]))
django.core.exceptions.ImproperlyConfigured: ImportError contentstore: cannot import name microsite

FATAL: all hosts have already failed -- aborting

===========end========

**Comment by nedbat** [comment]
Sorry we have left this issue untended for so long.  GitHub issues are not meant for support questions.  Please use the [mailing list](https://groups.google.com/forum/#!forum/openedx-ops) or [Slack channels](https://open.edx.org/blog/open-edx-slack) to get help.
