### ISSUE TITLE
edxapp-syncdb-lms

### ISSUE THREAD

**Issue by WoodMath** [openedx-unsupported/configuration#2336]
Hi,

I'm trying to install based on the instructions at [https://github.com/edx/configuration/wiki/edX-Ubuntu-12.04-64-bit-Installation](https://github.com/edx/configuration/wiki/edX-Ubuntu-12.04-64-bit-Installation), but after running the command 

```
cd /var/tmp/configuration/playbooks && sudo ansible-playbook -c local ./edx_sandbox.yml -i "localhost,"
```

I get the following output which I'm not sure how to interpret.

```
failed: [localhost] => (item=lms) => {"changed": true, "cmd": ["/edx/bin/edxapp-syncdb-lms"], "delta": "0:00:03.430135", "end": "2015-10-10 20:39:00.540886", "item": "lms", "rc": 1, "start": "2015-10-10 20:38:57.110751", "warnings": []}
stderr: warning: unable to access '/root/.config/git/attributes': Permission denied
2015-10-10 21:38:59,375 INFO 6544 [dd.dogapi] dog_stats_api.py:66 - Initializing dog api to use statsd: localhost, 8125
Traceback (most recent call last):
  File "manage.py", line 116, in <module>
    execute_from_command_line([sys.argv[0]] + django_args)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 443, in execute_from_command_line
    utility.execute()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 261, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 69, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/south/management/commands/__init__.py", line 10, in <module>
    import django.template.loaders.app_directories
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/template/loaders/app_directories.py", line 23, in <module>
    raise ImproperlyConfigured('ImportError %s: %s' % (app, e.args[0]))
django.core.exceptions.ImproperlyConfigured: ImportError branding: cannot import name microsite
failed: [localhost] => (item=cms) => {"changed": true, "cmd": ["/edx/bin/edxapp-syncdb-cms"], "delta": "0:00:03.149926", "end": "2015-10-10 20:39:03.889524", "item": "cms", "rc": 1, "start": "2015-10-10 20:39:00.739598", "warnings": []}
stderr: 2015-10-10 21:39:02,865 INFO 6588 [dd.dogapi] dog_stats_api.py:66 - Initializing dog api to use statsd: localhost, 8125
Traceback (most recent call last):
  File "manage.py", line 116, in <module>
    execute_from_command_line([sys.argv[0]] + django_args)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 443, in execute_from_command_line
    utility.execute()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 261, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 69, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/south/management/commands/__init__.py", line 10, in <module>
    import django.template.loaders.app_directories
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/template/loaders/app_directories.py", line 23, in <module>
    raise ImproperlyConfigured('ImportError %s: %s' % (app, e.args[0]))
django.core.exceptions.ImproperlyConfigured: ImportError contentstore: cannot import name microsite

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/test/edx_sandbox.retry

localhost                  : ok=202  changed=44   unreachable=0    failed=1
```

**Comment by feanil** [comment]
This is a recently introduced issue.  I filed a bug for it here:
https://openedx.atlassian.net/browse/SOL-1303

**Comment by ivb1960** [comment]
feanil, now we have to wait? I also described the error - https://gist.github.com/ivb1960/e5232db85950571321bf

**Comment by feanil** [comment]
This issues should be resolve now.  The fix was merged in on Wednesday this week.

**Comment by ErikVDW** [comment]
I used the automated integration on the same page as above.  And then from the [Manage OpenEdx Tips and Tricks page](https://openedx.atlassian.net/wiki/display/OpenOPS/Managing+OpenEdX+Tips+and+Tricks), calling:
`sudo -u www-data /edx/bin/python.edxapp ./manage.py lms --settings aws create_user -e user@example.com`

 I get the same error as above using Eucalyptus 2:

`sudo -u www-data /edx/bin/python.edxapp ./manage.py lms --settings aws create_user -e user@example.com
2016-10-07 16:09:18,075 INFO 8118 [dd.dogapi] dog_stats_api.py:66 - Initializing dog api to use statsd: localhost, 8125
Traceback (most recent call last):
  File "./manage.py", line 116, in <module>
    execute_from_command_line([sys.argv[0]] + django_args)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/edx/app/edxapp/edx-platform/common/djangoapps/track/management/tracked_command.py", line 59, in execute
    super(TrackedCommand, self).execute(*args, **options)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/edx/app/edxapp/edx-platform/common/djangoapps/student/management/commands/create_user.py", line 99, in handle
    user, _, reg = _do_create_account(form)
  File "/edx/app/edxapp/edx-platform/common/djangoapps/student/views.py", line 1484, in _do_create_account
    raise ValidationError(errors)
django.core.exceptions.ValidationError: {'password': [u'A valid password is required']}
root@ip-172-31-21-85:/edx/app/edxapp/edx-platform# nano manage.py
root@ip-172-31-21-85:/edx/app/edxapp/edx-platform#`
