### ISSUE TITLE
It is not possible to continue the installation Cypress full stack edX server

### ISSUE THREAD

**Issue by ivb1960** [openedx-unsupported/configuration#2354]
TASK: [insights | migrate] ****************************************************
failed: [localhost] => {"changed": true, "cmd": "DB_MIGRATION_USER=migrate DB_MIGRATION_PASS=password /edx/app/insights/venvs/insights/bin/python /edx/app/insights/edx_analytics_dashboard/manage.py migrate --noinput", "delta": "0:00:00.456245", "end": "2015-10-15 01:21:30.810162", "rc": 1, "start": "2015-10-15 01:21:30.353917", "warnings": []}
stderr: System check identified some issues:

WARNINGS:
?: (1_6.W001) Some project unittests may not execute as expected.
        HINT: Django 1.6 introduced a new default test runner. It looks like this project was generated using Django 1.5 or earlier. You should ensure your tests are all running & behaving as expected. See https://docs.djangoproject.com/en/dev/releases/1.6/#new-test-runner for more information.
Traceback (most recent call last):
  File "/edx/app/insights/edx_analytics_dashboard/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/edx/app/insights/venvs/insights/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 385, in execute_from_command_line
    utility.execute()
  File "/edx/app/insights/venvs/insights/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/edx/app/insights/venvs/insights/local/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(_args, *_options.**dict**)
  File "/edx/app/insights/venvs/insights/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(_args, *_options)
  File "/edx/app/insights/venvs/insights/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 63, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/edx/app/insights/venvs/insights/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 17, in **init**
    self.loader = MigrationLoader(self.connection)
  File "/edx/app/insights/venvs/insights/local/lib/python2.7/site-packages/django/db/migrations/loader.py", line 49, in **init**
    self.build_graph()
  File "/edx/app/insights/venvs/insights/local/lib/python2.7/site-packages/django/db/migrations/loader.py", line 184, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/edx/app/insights/venvs/insights/local/lib/python2.7/site-packages/django/db/migrations/recorder.py", line 59, in applied_migrations
    self.ensure_schema()
  File "/edx/app/insights/venvs/insights/local/lib/python2.7/site-packages/django/db/migrations/recorder.py", line 49, in ensure_schema
    if self.Migration._meta.db_table in self.connection.introspection.get_table_list(self.connection.cursor()):
  File "/edx/app/insights/venvs/insights/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 167, in cursor
    cursor = utils.CursorWrapper(self._cursor(), self)
  File "/edx/app/insights/venvs/insights/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 138, in _cursor
    self.ensure_connection()
  File "/edx/app/insights/venvs/insights/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 133, in ensure_connection
    self.connect()
  File "/edx/app/insights/venvs/insights/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in **exit**
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/edx/app/insights/venvs/insights/local/lib/python2.7/site-packages/django/db/backends/**init**.py", line 133, in ensure_connection
    self.connect()
  File "/edx/app/insights/venvs/insights/local/lib/python2.7/site-packages/django/db/backends/**init**.py", line 122, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/edx/app/insights/venvs/insights/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 472, in get_new_connection
    conn = Database.connect(*_conn_params)
  File "/edx/app/insights/venvs/insights/local/lib/python2.7/site-packages/MySQLdb/**init**.py", line 81, in Connect
    return Connection(_args, *_kwargs)
  File "/edx/app/insights/venvs/insights/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in **init**
    super(Connection, self).**init**(_args, **kwargs2)
django.db.utils.OperationalError: (1044, "Access denied for user 'migrate'@'localhost' to database 'dashboard'")

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/root/edx_sandbox.retry

localhost                  : ok=373  changed=216  unreachable=0    failed=1

**Comment by mulby** [comment]
See https://github.com/edx/configuration/pull/2353

**Comment by ivb1960** [comment]
I am glad. Platform installed.
