### ISSUE TITLE
The certificate button "download" doesn't appear

### ISSUE THREAD

**Issue by sbalde** [openedx-unsupported/configuration#2374]
Hello guys,

I have a Cypress Fullstack installed on Ubuntu 14

While I generate a certificate for a single user, the "download certificate" button doesn't appear onto the dashboard. See the attached screeshot.

I use the following command to generate to certificate for a single user.

"./manage.py lms --settings aws regenerate_user -u honor@example.com -c course-v1:edX+DemoX+Demo_Course --insecure"

Here is what I see inside the "edx.log"

```
template = lookup_template(namespace, template_name)
```

  File "/edx/app/edxapp/edx-platform/common/djangoapps/edxmako/paths.py", line 80, in lookup_template
    return LOOKUP[namespace].get_template(name)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/mako/lookup.py", line 245, in get_template
    return self._load(srcfile, uri)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/mako/lookup.py", line 311, in _load
    **self.template_args)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/mako/template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/mako/template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/mako/compat.py", line 58, in load_module
    fp = open(path, 'rb')
Exception: cannot create LoncapaProblem block-v1:edX+DemoX+Demo_Course+type@problem+block@ex_practice_2: [Errno 13] Permission denied: '/tmp/mako_lms/35b4de82addd2666f931e3dcd3a9da25/textline.html.py'
Oct 19 15:46:48 vps199556 [service_variant=lms][xmodule.x_module][env:sandbox] ERROR [vps199556  4906] [x_module.py:1141] - Error creating xmodule
Traceback (most recent call last):
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/x_module.py", line 1129, in _xmodule
    for_parent=self.get_parent() if self.has_cached_parent else None
  File "/edx/app/edxapp/venvs/edxapp/src/xblock/xblock/runtime.py", line 635, in construct_xblock_from_class
    _args, *_kwargs
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/capa_module.py", line 48, in __init__
    super(CapaModule, self).**init**(_args, *_kwargs)
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/capa_base.py", line 230, in **init**
    self.lcp = self.new_lcp(self.get_state_for_lcp())
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/capa_base.py", line 322, in new_lcp
    capa_module=self,  # njp
  File "/edx/app/edxapp/edx-platform/common/lib/capa/capa/capa_problem.py", line 196, in **init**
    self.extracted_tree = self._extract_html(self.tree)
  File "/edx/app/edxapp/edx-platform/common/lib/capa/capa/capa_problem.py", line 818, in _extract_html
    item_xhtml = self._extract_html(item)
  File "/edx/app/edxapp/edx-platform/common/lib/capa/capa/capa_problem.py", line 818, in _extract_html
    item_xhtml = self._extract_html(item)
  File "/edx/app/edxapp/edx-platform/common/lib/capa/capa/capa_problem.py", line 806, in _extract_html
    self._extract_html, response_msg=overall_msg
  File "/edx/app/edxapp/edx-platform/common/lib/capa/capa/responsetypes.py", line 243, in render_html
    item_xhtml = renderer(item)
  File "/edx/app/edxapp/edx-platform/common/lib/capa/capa/capa_problem.py", line 800, in _extract_html
    return self.inputs[input_id].get_html()
  File "/edx/app/edxapp/edx-platform/common/lib/capa/capa/inputtypes.py", line 345, in get_html
    html = self.capa_system.render_template(self.template, context)
  File "/edx/app/edxapp/edx-platform/common/djangoapps/edxmako/shortcuts.py", line 133, in render_to_string
    template = lookup_template(namespace, template_name)
  File "/edx/app/edxapp/edx-platform/common/djangoapps/edxmako/paths.py", line 80, in lookup_template
    return LOOKUP[namespace].get_template(name)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/mako/lookup.py", line 245, in get_template
    return self._load(srcfile, uri)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/mako/lookup.py", line 311, in _load
    **self.template_args)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/mako/template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/mako/template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/mako/compat.py", line 58, in load_module
    fp = open(path, 'rb')
Exception: cannot create LoncapaProblem block-v1:edX+DemoX+Demo_Course+type@problem+block@Sample_ChemFormula_Problem: [Errno 13] Permission denied: '/tmp/mako_lms/35b4de82addd2666f931e3dcd3a9da25/chemicalequationinput.html.py'
Oct 19 15:46:48 vps199556 [service_variant=lms][xmodule.x_module][env:sandbox] ERROR [vps199556  4906] [x_module.py:1141] - Error creating xmodule
Traceback (most recent call last):
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/x_module.py", line 1129, in _xmodule
    for_parent=self.get_parent() if self.has_cached_parent else None
  File "/edx/app/edxapp/venvs/edxapp/src/xblock/xblock/runtime.py", line 635, in construct_xblock_from_class
    _args, *_kwargs
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/capa_module.py", line 48, in __init__
    super(CapaModule, self).**init**(_args, *_kwargs)
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/capa_base.py", line 230, in **init**
    self.lcp = self.new_lcp(self.get_state_for_lcp())
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/capa_base.py", line 322, in new_lcp
    capa_module=self,  # njp
  File "/edx/app/edxapp/edx-platform/common/lib/capa/capa/capa_problem.py", line 196, in **init**
    self.extracted_tree = self._extract_html(self.tree)
  File "/edx/app/edxapp/edx-platform/common/lib/capa/capa/capa_problem.py", line 818, in _extract_html
    item_xhtml = self._extract_html(item)
  File "/edx/app/edxapp/edx-platform/common/lib/capa/capa/capa_problem.py", line 806, in _extract_html
    self._extract_html, response_msg=overall_msg
  File "/edx/app/edxapp/edx-platform/common/lib/capa/capa/responsetypes.py", line 243, in render_html
    item_xhtml = renderer(item)
  File "/edx/app/edxapp/edx-platform/common/lib/capa/capa/capa_problem.py", line 800, in _extract_html
    return self.inputs[input_id].get_html()
  File "/edx/app/edxapp/edx-platform/common/lib/capa/capa/inputtypes.py", line 345, in get_html
    html = self.capa_system.render_template(self.template, context)
  File "/edx/app/edxapp/edx-platform/common/djangoapps/edxmako/shortcuts.py", line 133, in render_to_string
    template = lookup_template(namespace, template_name)
  File "/edx/app/edxapp/edx-platform/common/djangoapps/edxmako/paths.py", line 80, in lookup_template
    return LOOKUP[namespace].get_template(name)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/mako/lookup.py", line 245, in get_template
    return self._load(srcfile, uri)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/mako/lookup.py", line 311, in _load
    **self.template_args)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/mako/template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/mako/template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/mako/compat.py", line 58, in load_module
    fp = open(path, 'rb')
Exception: cannot create LoncapaProblem block-v1:edX+DemoX+Demo_Course+type@problem+block@c554538a57664fac80783b99d9d6da7c: [Errno 13] Permission denied: '/tmp/mako_lms/35b4de82addd2666f931e3dcd3a9da25/imageinput.html.py'
Oct 19 15:46:48 vps199556 [service_variant=lms][edx.courseware][env:sandbox] INFO [vps199556  4906] [grades.py:143] - Signal fired when student grade is calculated. Receiver: <function listen_for_grade_calculation at 0x7fc64ef765f0>. Response: None
Oct 19 15:46:48 vps199556 [service_variant=lms][certificates.queue][env:sandbox] INFO [vps199556  4906] [queue.py:301] - Student 1 is whitelisted in 'course-v1:edX+DemoX+Demo_Course'
Oct 19 15:46:48 vps199556 [service_variant=lms][requests.packages.urllib3.connectionpool][env:sandbox] INFO [vps199556  4906] [connectionpool.py:180] - Starting new HTTP connection (1): localhost
Oct 19 15:46:49 vps199556 [service_variant=lms][certificates.queue][env:sandbox] INFO [vps199556  4906] [queue.py:367] - The certificate status has been set to 'generating'.  Sent a certificate grading task to the XQueue with the key 'd9c29c2bf3aca9b785c373c4ed292c2b'.
Oct 19 15:46:49 vps199556 [service_variant=lms][certificates.management.commands.regenerate_user][env:sandbox] INFO [vps199556  4906] [regenerate_user.py:131] - Added a certificate regeneration task to the XQueue for student 1 in course 'course-v1:edX+DemoX+Demo_Course'. The new certificate status is '('generating', <GeneratedCertificate: GeneratedCertificate object>)'.
Oct 19 15:46:49 vps199556 [service_variant=lms][certificates.management.commands.regenerate_user][env:sandbox] INFO [vps199556  4906] [regenerate_user.py:151] - Finished regenerating certificates command for user 1 and course 'course-v1:edX+DemoX+Demo_Course'.

And when use the generate certificate report command I have the following lines wich show that the lcertificate has been generated and is downloadable.

 ./manage.py lms --settings aws gen_cert_report -c course-v1:edX+DemoX+Demo_Course
2015-10-19 09:56:18,282 INFO 7624 [dd.dogapi] dog_stats_api.py:66 - Initializing dog api to use statsd: localhost, 8125
Looking up certificate states for course-v1:edX+DemoX+Demo_Course
                 course ID   audit_enrolled     downloadable enrolled_current   enrolled_total            honor   honor_enrolled verified_enrolled
course-v1:edX+DemoX+Demo_Course                0                1                4                4                1                1                0

![certificate_download](https://cloud.githubusercontent.com/assets/11218855/10580358/75a218f4-767d-11e5-8d44-c19c14120904.PNG)

Is there anyone that has alreday faced the same error?

**Comment by sbalde** [comment]
The errors inside the logs where due to permissions restriction. I finally regenerated the certificate with the right user "www-data", this allowed me to avoid the errors. Though the certificate generation went through, the "download" button still doesn't appear.

The only way to currently download the certificate is to copy paste the download link from the database to browser.

I'll keep posting news about this case.

**Comment by j-lorenzo** [comment]
I got the same problem, did you fix it? @sbalde

**Comment by nedbat** [comment]
Sorry we have left this issue untended for so long.  GitHub issues are not meant for support questions.  Please use the [mailing list](https://groups.google.com/forum/#!forum/openedx-ops) or [Slack channels](https://open.edx.org/blog/open-edx-slack) to get help.
