### ISSUE TITLE
Clean cypress ansible playbook install fails

### ISSUE THREAD

**Issue by shaidar** [openedx-unsupported/configuration#2421]
I've had this working fine last week however since yesterday, it consistently fails on two VMs that worked last week. I have clean snapshots of the VM's that I revert to when testing, so I know that's not the issue. 

Below are the details:
- The VM's are running Ubuntu 12.04.5 LTS
- Today I downloaded https://github.com/edx/configuration
- Edited the inventory.ini file with the needed info
- Ran the following command:

```
ansible-playbook ./vagrant-fullstack.yml -i inventory.ini -K -e edx_platform_version=named-release/cypress -e ora2_version=named-release/cypress -e certs_version=named-release/cypress -e forum_version=named-release/cypress -e xqueue_version=named-release/cypress -e configuration_version=named-release/cypress
```
- Error is:

```
TASK: [edxapp | syncdb and migrate] ******************************************* 
failed: [ip_address] => (item=lms) => {"changed": true, "cmd": ["/edx/bin/edxapp-syncdb-lms"], "delta": "0:00:10.826693", "end": "2015-10-28 14:00:06.367756", "item": "lms", "rc": 1, "start": "2015-10-28 13:59:55.541063", "warnings": []}
stderr: warning: unable to access '/root/.config/git/attributes': Permission denied
2015-10-28 13:59:57,458 INFO 84822 [dd.dogapi] dog_stats_api.py:66 - Initializing dog api to use statsd: localhost, 8125
FATAL ERROR - The following SQL query failed: alter table `auth_user` drop `website`, drop `about`, drop `gold`, drop `email_isvalid`, drop `real_name`, drop `location`, drop `reputation`, drop `gravatar`, drop `bronze`, drop `last_seen`, drop `silver`, drop `questions_per_page`, drop `new_response_count`, drop `seen_response_count`;
The error was: (1091, "Can't DROP 'website'; check that column/key exists")
FATAL ERROR - The following SQL query failed: DROP INDEX `student_testcenterregistration_fe557fd4` ON `student_testcenterregistration`
The error was: (1091, "Can't DROP 'student_testcenterregistration_fe557fd4'; check that column/key exists")
Traceback (most recent call last):
  File "manage.py", line 116, in <module>
    execute_from_command_line([sys.argv[0]] + django_args)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 443, in execute_from_command_line
    utility.execute()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/base.py", line 196, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/base.py", line 232, in execute
    output = self.handle(*args, **options)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/base.py", line 371, in handle
    return self.handle_noargs(**options)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/south/management/commands/syncdb.py", line 103, in handle_noargs
    management.call_command('migrate', **options)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 150, in call_command
    return klass.execute(*args, **defaults)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/base.py", line 232, in execute
    output = self.handle(*args, **options)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/south/management/commands/migrate.py", line 111, in handle
    ignore_ghosts = ignore_ghosts,
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/south/migration/__init__.py", line 220, in migrate_app
    success = migrator.migrate_many(target, workplan, database)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/south/migration/migrators.py", line 256, in migrate_many
    result = migrator.__class__.migrate_many(migrator, target, migrations, database)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/south/migration/migrators.py", line 331, in migrate_many
    result = self.migrate(migration, database)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/south/migration/migrators.py", line 133, in migrate
    result = self.run(migration, database)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/south/migration/migrators.py", line 114, in run
    return self.run_migration(migration, database)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/south/migration/migrators.py", line 84, in run_migration
    migration_function()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/south/migration/migrators.py", line 60, in <lambda>
    return (lambda: direction(orm))
  File "/edx/app/edxapp/edx-platform/common/djangoapps/student/migrations/0035_access_roles.py", line 34, in forwards
    store = modulestore()
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/modulestore/django.py", line 202, in modulestore
    contentstore(),
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/contentstore/django.py", line 28, in contentstore
    _CONTENTSTORE[name] = class_(**options)
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/contentstore/mongo.py", line 38, in __init__
    **kwargs
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 241, in __init__
    raise TypeError("port must be an instance of int")
TypeError: port must be an instance of int
stdout: Syncing...
Creating tables ...
Creating table auth_permission
Creating table auth_group_permissions
Creating table auth_group
Creating table auth_user_user_permissions
Creating table auth_user_groups
Creating table auth_user
Creating table django_content_type
Creating table django_session
Creating table django_site
Creating table celery_taskmeta
Creating table celery_tasksetmeta
Creating table djcelery_intervalschedule
Creating table djcelery_crontabschedule
Creating table djcelery_periodictasks
Creating table djcelery_periodictask
Creating table djcelery_workerstate
Creating table djcelery_taskstate
Creating table south_migrationhistory
Creating table circuit_servercircuit
Creating table psychometrics_psychometricdata
Creating table django_openid_auth_nonce
Creating table django_openid_auth_association
Creating table django_openid_auth_useropenid
Creating table django_admin_log
Creating table corsheaders_corsmodel
Installing custom SQL ...
Installing indexes ...
Installed 0 object(s) from 0 fixture(s)
Migrating...
Running migrations for courseware:
 - Migrating forwards to 0013_auto__add_field_studentfieldoverride_created__add_field_studentfieldov.
 > courseware:0001_initial
 > courseware:0002_add_indexes
 > courseware:0003_done_grade_cache
 > courseware:0004_add_field_studentmodule_course_id
 > courseware:0005_auto__add_offlinecomputedgrade__add_unique_offlinecomputedgrade_user_c
 > courseware:0006_create_student_module_history
 > courseware:0007_allow_null_version_in_history
 > courseware:0008_add_xmodule_storage
 > courseware:0009_add_field_default
 > courseware:0010_rename_xblock_field_content_to_user_state_summary
 > courseware:0011_add_model_StudentFieldOverride
 > courseware:0012_auto__del_unique_studentfieldoverride_course_id_location_student__add_
 > courseware:0013_auto__add_field_studentfieldoverride_created__add_field_studentfieldov
 - Loading initial data for courseware.
Installed 0 object(s) from 0 fixture(s)
Running migrations for student:
 - Migrating forwards to 0051_auto__add_courseenrollmentattribute.
 > xblock_django:0001_initial
 > student:0001_initial
 > student:0002_text_to_varchar_and_indexes
 > student:0003_auto__add_usertestgroup
 > student:0004_add_email_index
 > student:0005_name_change
 > student:0006_expand_meta_field
 > student:0007_convert_to_utf8
 > student:0008__auto__add_courseregistration
 > student:0009_auto__del_courseregistration__add_courseenrollment
 > student:0010_auto__chg_field_courseenrollment_course_id
 > student:0011_auto__chg_field_courseenrollment_user__del_unique_courseenrollment_use
 > student:0012_auto__add_field_userprofile_gender__add_field_userprofile_date_of_birt
 > student:0013_auto__chg_field_userprofile_meta
 > student:0014_auto__del_courseenrollment
 > student:0015_auto__add_courseenrollment__add_unique_courseenrollment_user_course_id
 > student:0016_auto__add_field_courseenrollment_date__chg_field_userprofile_country
 > student:0017_rename_date_to_created
 > student:0018_auto
 > student:0019_create_approved_demographic_fields_fall_2012
 > student:0020_add_test_center_user
 > student:0021_remove_askbot
Couldn't remove askbot because of (1091, "Can't DROP 'website'; check that column/key exists") -- it was probably never here to begin with.
 > student:0022_auto__add_courseenrollmentallowed__add_unique_courseenrollmentallowed_
 > student:0023_add_test_center_registration
 > student:0024_add_allow_certificate
 > student:0025_auto__add_field_courseenrollmentallowed_auto_enroll
 > student:0026_auto__remove_index_student_testcenterregistration_accommodation_request
-- skipping delete_index of student_testcenterregistration.accommodation_request (index does not exist)
 > student:0027_add_active_flag_and_mode_to_courseware_enrollment
 > student:0028_auto__add_userstanding
 > student:0029_add_lookup_table_between_user_and_anonymous_student_id
 > student:0029_remove_pearson
 > student:0030_auto__chg_field_anonymoususerid_anonymous_user_id
 > student:0031_drop_student_anonymoususerid_temp_archive
 - Migration 'student:0031_drop_student_anonymoususerid_temp_archive' is marked for no-dry-run.
 > student:0032_add_field_UserProfile_country_add_field_UserProfile_city
 > student:0032_auto__add_loginfailures
 > student:0033_auto__add_passwordhistory
 > student:0034_auto__add_courseaccessrole
 > student:0035_access_roles
 - Migration 'student:0035_access_roles' is marked for no-dry-run.
 ! Error found during real run of migration! Aborting.

 ! Since you have a database that does not support running
 ! schema-altering statements in transactions, we have had 
 ! to leave it in an interim state between migrations.

! You *might* be able to recover with:   (migration cannot be dry-run; cannot discover commands)
 ! The South developers regret this has happened, and would
 ! like to gently persuade you to consider a slightly
 ! easier-to-deal-with DBMS (one that supports DDL transactions)
 ! NOTE: The error which caused the migration to fail is further up.
Error in migration: student:0035_access_roles
failed: [ip_address] => (item=cms) => {"changed": true, "cmd": ["/edx/bin/edxapp-syncdb-cms"], "delta": "0:00:03.828553", "end": "2015-10-28 14:00:10.401151", "item": "cms", "rc": 1, "start": "2015-10-28 14:00:06.572598", "warnings": []}
stderr: 2015-10-28 14:00:08,907 INFO 84848 [dd.dogapi] dog_stats_api.py:66 - Initializing dog api to use statsd: localhost, 8125
Traceback (most recent call last):
  File "manage.py", line 116, in <module>
    execute_from_command_line([sys.argv[0]] + django_args)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 443, in execute_from_command_line
    utility.execute()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/base.py", line 196, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/base.py", line 232, in execute
    output = self.handle(*args, **options)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/base.py", line 371, in handle
    return self.handle_noargs(**options)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/south/management/commands/syncdb.py", line 103, in handle_noargs
    management.call_command('migrate', **options)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 150, in call_command
    return klass.execute(*args, **defaults)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/base.py", line 232, in execute
    output = self.handle(*args, **options)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/south/management/commands/migrate.py", line 111, in handle
    ignore_ghosts = ignore_ghosts,
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/south/migration/__init__.py", line 220, in migrate_app
    success = migrator.migrate_many(target, workplan, database)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/south/migration/migrators.py", line 256, in migrate_many
    result = migrator.__class__.migrate_many(migrator, target, migrations, database)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/south/migration/migrators.py", line 331, in migrate_many
    result = self.migrate(migration, database)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/south/migration/migrators.py", line 133, in migrate
    result = self.run(migration, database)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/south/migration/migrators.py", line 114, in run
    return self.run_migration(migration, database)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/south/migration/migrators.py", line 84, in run_migration
    migration_function()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/south/migration/migrators.py", line 60, in <lambda>
    return (lambda: direction(orm))
  File "/edx/app/edxapp/edx-platform/common/djangoapps/student/migrations/0035_access_roles.py", line 34, in forwards
    store = modulestore()
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/modulestore/django.py", line 202, in modulestore
    contentstore(),
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/contentstore/django.py", line 28, in contentstore
    _CONTENTSTORE[name] = class_(**options)
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/contentstore/mongo.py", line 38, in __init__
    **kwargs
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 241, in __init__
    raise TypeError("port must be an instance of int")
TypeError: port must be an instance of int
stdout: Syncing...
Creating tables ...
Installing custom SQL ...
Installing indexes ...
Installed 0 object(s) from 0 fixture(s)
Migrating...
Running migrations for contentstore:
 - Migrating forwards to 0003_auto__add_pushnotificationconfig.
 > contentstore:0001_initial
 > contentstore:0002_auto__del_field_videouploadconfig_status_whitelist
 > contentstore:0003_auto__add_pushnotificationconfig
 - Loading initial data for contentstore.
Installed 0 object(s) from 0 fixture(s)
Running migrations for course_creators:
 - Migrating forwards to 0001_initial.
 > course_creators:0001_initial
 - Loading initial data for course_creators.
Installed 0 object(s) from 0 fixture(s)
Running migrations for student:
 - Migrating forwards to 0051_auto__add_courseenrollmentattribute.
 > student:0035_access_roles
 - Migration 'student:0035_access_roles' is marked for no-dry-run.
 ! Error found during real run of migration! Aborting.

 ! Since you have a database that does not support running
 ! schema-altering statements in transactions, we have had 
 ! to leave it in an interim state between migrations.

! You *might* be able to recover with:   (migration cannot be dry-run; cannot discover commands)
 ! The South developers regret this has happened, and would
 ! like to gently persuade you to consider a slightly
 ! easier-to-deal-with DBMS (one that supports DDL transactions)
 ! NOTE: The error which caused the migration to fail is further up.
Error in migration: student:0035_access_roles

FATAL: all hosts have already failed -- aborting
```

I then tried modifying vagrant-fullstack.yml and changed migrate_db to 'no' since I assumed (correct?) this is a clean install and there's no need to do that. This time I got the following error:

```
TASK: [edxapp | gather {{ item }} static assets with paver] ******************* 
failed: [ip_address] => (item=lms) => {"changed": true, "cmd": ["/edx/bin/edxapp-update-assets-lms"], "delta": "0:01:38.594183", "end": "2015-10-28 10:37:47.442415", "item": "lms", "rc": 1, "start": "2015-10-28 10:36:08.848232", "warnings": []}
stderr: warning: unable to access '/root/.config/git/attributes': Permission denied
2015-10-28 10:36:10,976 INFO 85683 [dd.dogapi] dog_stats_api.py:66 - Initializing dog api to use statsd: localhost, 8125
find: `/edx/app/edxapp/themes/': No such file or directory
stdout: ---> pavelib.assets.update_assets
---> pavelib.prereqs.install_ruby_prereqs
---> pavelib.prereqs.install_node_prereqs
python manage.py lms --settings=aws preprocess_assets
xmodule_assets common/static/xmodule
---> pavelib.assets.compile_coffeescript
node_modules/.bin/coffee --compile `find /edx/app/edxapp/edx-platform/lms /edx/app/edxapp/edx-platform/cms /edx/app/edxapp/edx-platform/common /edx/app/edxapp/themes/ -type f -name "*.coffee"`
---> pavelib.assets.compile_sass
sass --update --cache-location /tmp/sass-cache --default-encoding utf-8 --style compressed --quiet --load-path common/static --load-path common/static/sass --load-path lms/static/sass --load-path lms/static/certificates/sass --load-path /edx/app/edxapp/themes/static/sass --load-path cms/static/sass --load-path common/static/sass lms/static/sass:lms/static/css lms/static/certificates/sass:lms/static/certificates/css /edx/app/edxapp/themes/static/sass cms/static/sass:cms/static/css common/static/sass:common/static/css


Captured Task Output:
---------------------

---> pavelib.assets.update_assets
---> pavelib.prereqs.install_ruby_prereqs
---> pavelib.prereqs.install_node_prereqs
python manage.py lms --settings=aws preprocess_assets
xmodule_assets common/static/xmodule
---> pavelib.assets.compile_coffeescript
node_modules/.bin/coffee --compile `find /edx/app/edxapp/edx-platform/lms /edx/app/edxapp/edx-platform/cms /edx/app/edxapp/edx-platform/common /edx/app/edxapp/themes/ -type f -name "*.coffee"`
---> pavelib.assets.compile_sass
sass --update --cache-location /tmp/sass-cache --default-encoding utf-8 --style compressed --quiet --load-path common/static --load-path common/static/sass --load-path lms/static/sass --load-path lms/static/certificates/sass --load-path /edx/app/edxapp/themes/static/sass --load-path cms/static/sass --load-path common/static/sass lms/static/sass:lms/static/css lms/static/certificates/sass:lms/static/certificates/css /edx/app/edxapp/themes/static/sass cms/static/sass:cms/static/css common/static/sass:common/static/css

Build failed running pavelib.assets.update_assets: Subprocess return code: 1
failed: [ip_address] => (item=cms) => {"changed": true, "cmd": ["/edx/bin/edxapp-update-assets-cms"], "delta": "0:00:18.227627", "end": "2015-10-28 10:38:05.898188", "item": "cms", "rc": 1, "start": "2015-10-28 10:37:47.670561", "warnings": []}
stderr: 2015-10-28 10:37:50,159 INFO 85756 [dd.dogapi] dog_stats_api.py:66 - Initializing dog api to use statsd: localhost, 8125
stdout: ---> pavelib.assets.update_assets
---> pavelib.prereqs.install_ruby_prereqs
---> pavelib.prereqs.install_node_prereqs
python manage.py cms --settings=aws preprocess_assets
xmodule_assets common/static/xmodule
---> pavelib.assets.compile_coffeescript
node_modules/.bin/coffee --compile `find /edx/app/edxapp/edx-platform/lms /edx/app/edxapp/edx-platform/cms /edx/app/edxapp/edx-platform/common /edx/app/edxapp/themes/ -type f -name "*.coffee"`
---> pavelib.assets.compile_sass
sass --update --cache-location /tmp/sass-cache --default-encoding utf-8 --style compressed --quiet --load-path common/static --load-path common/static/sass --load-path lms/static/sass --load-path lms/static/certificates/sass --load-path /edx/app/edxapp/themes/static/sass --load-path cms/static/sass --load-path common/static/sass lms/static/sass:lms/static/css lms/static/certificates/sass:lms/static/certificates/css /edx/app/edxapp/themes/static/sass cms/static/sass:cms/static/css common/static/sass:common/static/css


Captured Task Output:
---------------------

---> pavelib.assets.update_assets
---> pavelib.prereqs.install_ruby_prereqs
---> pavelib.prereqs.install_node_prereqs
python manage.py cms --settings=aws preprocess_assets
xmodule_assets common/static/xmodule
---> pavelib.assets.compile_coffeescript
node_modules/.bin/coffee --compile `find /edx/app/edxapp/edx-platform/lms /edx/app/edxapp/edx-platform/cms /edx/app/edxapp/edx-platform/common /edx/app/edxapp/themes/ -type f -name "*.coffee"`
---> pavelib.assets.compile_sass
sass --update --cache-location /tmp/sass-cache --default-encoding utf-8 --style compressed --quiet --load-path common/static --load-path common/static/sass --load-path lms/static/sass --load-path lms/static/certificates/sass --load-path /edx/app/edxapp/themes/static/sass --load-path cms/static/sass --load-path common/static/sass lms/static/sass:lms/static/css lms/static/certificates/sass:lms/static/certificates/css /edx/app/edxapp/themes/static/sass cms/static/sass:cms/static/css common/static/sass:common/static/css

Build failed running pavelib.assets.update_assets: Subprocess return code: 1

FATAL: all hosts have already failed -- aborting
```

**Comment by shaidar** [comment]
This has been resolved with the help of @singingwolfboy. The issue was that I wasn't using the right version of ansible. There's a forked version of ansible since the main one has a bug and once I used the one listed in [edx/configuration requirements](https://github.com/edx/configuration/blob/master/requirements.txt), a clean cypress install worked.

**Comment by srapelly** [comment]
I get this error only If overwrite the default password - to some password., i'm overrwriting the default password in server_vars.yml, then i'm getting this error.

EDXAPP_XQUEUE_DJANGO_AUTH: 
   username: 'lms' 
   password: '{{ DATABASE_PASSWORD }}' 

EDXAPP_MONGO_PASSWORD: "{{ DATABASE_PASSWORD }}" 
EDXAPP_MYSQL_PASSWORD: "{{ DATABASE_PASSWORD }}" 

Please help me, edx installation always works with default password 'password'?
