### ISSUE TITLE
Problem with running devstack lms/studio

### ISSUE THREAD

**Issue by 3nabhs** [openedx-unsupported/configuration#2447]
Hey,
I used to run devstack perfectly fine till today. After resetting my pc (it ran for like 2 weeks now so there were probably tons of different updates) my devstack decided to not work anymore.
I can easily run the virtual machine, and log in with vagrant ssh. But when I try to turn on lms, or studio with command

```
paver devstack lms/studio
```

I get this:

```
---> pavelib.servers.devstack
---> pavelib.prereqs.install_prereqs
---> pavelib.prereqs.install_ruby_prereqs
Ruby prereqs unchanged, skipping...
---> pavelib.prereqs.install_node_prereqs
Node prereqs unchanged, skipping...
---> pavelib.prereqs.install_python_prereqs
Python prereqs unchanged, skipping...
python manage.py cms --settings=devstack reindex_course --setup
Traceback (most recent call last):
  File "manage.py", line 116, in <module>
    execute_from_command_line([sys.argv[0]] + django_args)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 443, in execute_from_command_line
    utility.execute()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/base.py", line 196, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/base.py", line 232, in execute
    output = self.handle(*args, **options)
  File "/edx/app/edxapp/edx-platform/cms/djangoapps/contentstore/management/commands/reindex_course.py", line 76, in handle
    store = modulestore()
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/modulestore/django.py", line 206, in modulestore
    contentstore(),
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/contentstore/django.py", line 28, in contentstore
    _CONTENTSTORE[name] = class_(**options)
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/contentstore/mongo.py", line 39, in __init__
    **kwargs
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 378, in __init__
    raise ConnectionFailure(str(e))
pymongo.errors.ConnectionFailure: [Errno 111] Connection refused


Captured Task Output:
---------------------

---> pavelib.servers.devstack
---> pavelib.prereqs.install_prereqs
---> pavelib.prereqs.install_ruby_prereqs
---> pavelib.prereqs.install_node_prereqs
---> pavelib.prereqs.install_python_prereqs
python manage.py cms --settings=devstack reindex_course --setup

Build failed running pavelib.servers.devstack: Subprocess return code: 1
```

Now, keep in mind that I do work over proxy, and I have it configured in my Vagrantfile. It did work before, don't know why it would crash now ;/. From what I can understand there's problem with mongo here, but i have no idea how to fix this.

**Comment by 3nabhs** [comment]
Ok, it seems that it was a mongo problem. I've managed to find answer on the internet and here's how to repair it.
Just log on to your vagrant and run those commands:

```
sudo rm /edx/var/mongo/mongodb/mongod.lock
sudo -u mongodb mongod --dbpath /edx/var/mongo/mongodb --repair --repairpath /edx/var/mongo/mongodb
sudo start mongod
```

Then you need to reload your vagrant instance and you're good to go. 
I do not really understand how it could get destroyed over the night, but the fix is pretty straightforward, so it is not a problem I guess.

**Comment by delabi** [comment]
Worked for me!

**Comment by karan1276** [comment]
This works, but i have to do it everytime i turn devstack on.

**Comment by karan1276** [comment]
Last line gave me error, run below instead:
`sudo service mongod start`

**Comment by zubair-arbi** [comment]
@3nabhs @karan1276 you can fix the pymongo `ConnectionFailure` by running following commands:
```
vagrant up
vagrant ssh

sudo rm /edx/var/mongo/mongodb/mongod.lock
sudo mongod -repair --config /etc/mongod.conf
sudo chown -R mongodb:mongodb /edx/var/mongo/.
sudo service mongod start
```
After running these commands the pymongo will start working again and you don't need to reload your box.

Also if you properly shutdown your vagrant box by running `vagrant halt` then on next `vagrant up` pymongo will work just fine.

**Comment by ahmed-faraz46** [comment]
worked for me (y) (y)

**Comment by Mukesh80530** [comment]
edxapp@precise64:~/edx-platform$ paver devstack lms 
---> pavelib.servers.devstack
---> pavelib.prereqs.install_prereqs
---> pavelib.prereqs.install_node_prereqs
npm install

/usr/lib/node_modules/npm/bin/npm-cli.js:79
      let notifier = require('update-notifier')({pkg})
          ^^^^^^^^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3


Captured Task Output:
---------------------

---> pavelib.servers.devstack
---> pavelib.prereqs.install_prereqs
---> pavelib.prereqs.install_node_prereqs
npm install

Build failed running pavelib.servers.devstack: Subprocess return code: 8
can anyone help me
