### ISSUE TITLE
Ansible Install fails on RabbitMQ

### ISSUE THREAD

**Issue by asia653** [openedx-unsupported/configuration#250]
OS: Ubuntu 12.04 x64

TASK: [rabbitmq | remove guest user] *****************************************\* 
failed: [localhost] => {"cmd": ["/usr/sbin/rabbitmqctl", "-q", "-n", "rabbit", "list_users"], "failed": true, "item": "", "rc": 2}
stderr: Error: unable to connect to node rabbit@localhost: nodedown
# DIAGNOSTICS

nodes in question: [rabbit@localhost]

hosts, their running nodes and ports:
- localhost: [{rabbit,39680},{rabbitmqctl26036,38523}]

current node details:
- node name: rabbitmqctl26036@localhost
- home dir: /var/lib/rabbitmq
- cookie hash: /SlUT7vhXv2QW/B4ApbS5Q==

msg: Error: unable to connect to node rabbit@localhost: nodedown
# DIAGNOSTICS

nodes in question: [rabbit@localhost]

hosts, their running nodes and ports:
- localhost: [{rabbit,39680},{rabbitmqctl26036,38523}]

current node details:
- node name: rabbitmqctl26036@localhost
- home dir: /var/lib/rabbitmq
- cookie hash: /SlUT7vhXv2QW/B4ApbS5Q==

FATAL: all hosts have already failed -- aborting

PLAY RECAP *******************************************************************\* 
           to retry, use: --limit @/root/edx_sandbox.retry

localhost                  : ok=132  changed=31   unreachable=0    failed=1

**Comment by jarv** [comment]
I was unable to reproduce this myself by installing on a precise server from scratch.  I think it's a race condition where rabbitmq is not coming up all the way so I added a wait task https://github.com/edx/configuration/commit/aa6445cb994d302f95bfb9eb29f009ef8ad18bee

Can you pull master, re-test and let me know if that fixes it?

**Comment by asia653** [comment]
Different error message. Perhaps need more specific instructions. Do you guys update/upgrade before starting the script instructions?

TASK: [gather lms static assets with rake] ***********************************\* 
failed: [localhost] => {"changed": true, "cmd": " SERVICE_VARIANT=lms rake lms:gather_assets:aws ", "delta": "0:00:08.602144", "end": "2013-09-13 17:10:18.428600", "item": "", "rc": 1, "start": "2013-09-13 17:10:09.826456"}
stderr: mkdir -p /opt/wwc/edx-platform/.ws_migrations_complete
./manage.py lms --settings aws preprocess_assets --traceback 
xmodule_assets common/static/xmodule
Traceback (most recent call last):
  File "./manage.py", line 95, in <module>
    execute_from_command_line([sys.argv[0]] + django_args)
  File "/opt/edx/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 443, in execute_from_command_line
    utility.execute()
  File "/opt/edx/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/edx/local/lib/python2.7/site-packages/django/core/management/base.py", line 196, in run_from_argv
    self.execute(_args, *_options.**dict**)
  File "/opt/edx/local/lib/python2.7/site-packages/django/core/management/base.py", line 231, in execute
    self.validate()
  File "/opt/edx/local/lib/python2.7/site-packages/django/core/management/base.py", line 266, in validate
    num_errors = get_validation_errors(s, app)
  File "/opt/edx/local/lib/python2.7/site-packages/django/core/management/validation.py", line 30, in get_validation_errors
    for (app_name, error) in get_app_errors().items():
  File "/opt/edx/local/lib/python2.7/site-packages/django/db/models/loading.py", line 158, in get_app_errors
    self._populate()
  File "/opt/edx/local/lib/python2.7/site-packages/django/db/models/loading.py", line 64, in _populate
    self.load_app(app_name, True)
  File "/opt/edx/local/lib/python2.7/site-packages/django/db/models/loading.py", line 88, in load_app
    models = import_module('.models', app_name)
  File "/opt/edx/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/opt/wwc/edx-platform/lms/djangoapps/shoppingcart/models.py", line 22, in <module>
    from verify_student.models import SoftwareSecurePhotoVerification
  File "/opt/wwc/edx-platform/lms/djangoapps/verify_student/models.py", line 75, in <module>
    class PhotoVerification(StatusModel):
  File "/opt/wwc/edx-platform/lms/djangoapps/verify_student/models.py", line 116, in PhotoVerification
    DAYS_GOOD_FOR = settings.VERIFY_STUDENT["DAYS_GOOD_FOR"]
TypeError: string indices must be integers, not str
asset preprocessing failed!
node_modules/.bin/coffee --compile `find . -name *.coffee` 

FATAL: all hosts have already failed -- aborting

PLAY RECAP *******************************************************************\* 
           to retry, use: --limit @/root/edx_sandbox.retry

**Comment by feanil** [comment]
This error is actually due to a bug that was fixed in master today.  Can you please try again and build from master instead of release(which is currently the default).

**Comment by asia653** [comment]
Hey feanil,

I used:
sudo ansible all -c local -i "localhost," --limit "localhost:127.0.0.1"  \
-m git -a "repo=https://github.com/edx/configuration dest=/var/tmp/configuration"

Which pulls from master(correct me if I'm wrong).

git status -> On branch master

**Comment by jbau** [comment]
I think the fix is in edx-platform/master  (provides better defaults for VERIFY_STUDENT)

**Comment by feanil** [comment]
Yes, sorry for the confusion, as Jason said.  The fix is in the master of the edx-platfrom not in master of the configuration repo.

**Comment by asia653** [comment]
i have no clue how to do that. But I guess the issue can be closed if it is fixed! thanks guys
