### ISSUE TITLE
TASK: [gather lms static assets with rake]

### ISSUE THREAD

**Issue by plejik-zz** [openedx-unsupported/configuration#258]
```
failed: [localhost] => {"changed": true, "cmd": " SERVICE_VARIANT=lms rake     lms:gather_assets:aws ", "delta": "0:00:08.257899", "end": "2013-09-14 14:34:49.368114",     "item": "", "rc": 1, "start": "2013-09-14 14:34:41.110215"}
stderr: mkdir -p /opt/wwc/edx-platform/.ws_migrations_complete
./manage.py lms --settings aws preprocess_assets --traceback 
xmodule_assets common/static/xmodule
Traceback (most recent call last):
  File "./manage.py", line 95, in <module>
execute_from_command_line([sys.argv[0]] + django_args)
  File "/opt/edx/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 443, in execute_from_command_line
utility.execute()
  File "/opt/edx/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 382, in execute
self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/edx/local/lib/python2.7/site-packages/django/core/management/base.py", line 196, in run_from_argv
self.execute(*args, **options.__dict__)
  File "/opt/edx/local/lib/python2.7/site-packages/django/core/management/base.py", line 231, in execute
self.validate()
  File "/opt/edx/local/lib/python2.7/site-packages/django/core/management/base.py", line 266, in validate
num_errors = get_validation_errors(s, app)
  File "/opt/edx/local/lib/python2.7/site-packages/django/core/management/validation.py", line 30, in get_validation_errors
for (app_name, error) in get_app_errors().items():
  File "/opt/edx/local/lib/python2.7/site-packages/django/db/models/loading.py", line 158, in get_app_errors
self._populate()
  File "/opt/edx/local/lib/python2.7/site-packages/django/db/models/loading.py", line 64, in _populate
self.load_app(app_name, True)
  File "/opt/edx/local/lib/python2.7/site-packages/django/db/models/loading.py", line 88, in load_app
models = import_module('.models', app_name)
  File "/opt/edx/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
__import__(name)
  File "/opt/wwc/edx-platform/lms/djangoapps/shoppingcart/models.py", line 22, in <module>
from verify_student.models import SoftwareSecurePhotoVerification
  File "/opt/wwc/edx-platform/lms/djangoapps/verify_student/models.py", line 75, in <module>
class PhotoVerification(StatusModel):
  File "/opt/wwc/edx-platform/lms/djangoapps/verify_student/models.py", line 116, in PhotoVerification
DAYS_GOOD_FOR = settings.VERIFY_STUDENT["DAYS_GOOD_FOR"]
TypeError: string indices must be integers, not str
asset preprocessing failed!
node_modules/.bin/coffee --compile `find . -name *.coffee` 

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/root/edx_sandbox.retry

localhost                  : ok=114  changed=23   unreachable=0    failed=1   
```

This    mkdir -p /opt/wwc/edx-platform/.ws_migrations_complete folder exist, so maybe i need to install some requirements ?
Thanks

**Comment by plejik-zz** [comment]
Solved 
Upgrade pip from 1.0 in repo to 1.4 or higher
Securely download https://raw.github.com/pypa/pip/master/contrib/get-pip.py
python get-pip.py
