### ISSUE TITLE
TASK: [gather lms static assets with rake] 2

### ISSUE THREAD

**Issue by plejik-zz** [openedx-unsupported/configuration#259]
``failed: [localhost] => {"changed": true, "cmd": " SERVICE_VARIANT=lms rake lms:gather_assets:aws ", "delta": "0:00:06.363841", "end": "2013-09-14 16:31:00.706506", "item": "", "rc": 1, "start": "2013-09-14 16:30:54.342665"}
stderr: mkdir -p /opt/wwc/edx-platform/.ws_migrations_complete
./manage.py lms --settings aws preprocess_assets --traceback 
xmodule_assets common/static/xmodule
Traceback (most recent call last):
  File "./manage.py", line 95, in <module>
    execute_from_command_line([sys.argv[0]] + django_args)
  File "/opt/edx/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 443, in execute_from_command_line
    utility.execute()
  File "/opt/edx/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/edx/local/lib/python2.7/site-packages/django/core/management/base.py", line 196, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/opt/edx/local/lib/python2.7/site-packages/django/core/management/base.py", line 231, in execute
    self.validate()
  File "/opt/edx/local/lib/python2.7/site-packages/django/core/management/base.py", line 266, in validate
    num_errors = get_validation_errors(s, app)
  File "/opt/edx/local/lib/python2.7/site-packages/django/core/management/validation.py", line 30, in get_validation_errors
    for (app_name, error) in get_app_errors().items():
  File "/opt/edx/local/lib/python2.7/site-packages/django/db/models/loading.py", line 158, in get_app_errors
    self._populate()
  File "/opt/edx/local/lib/python2.7/site-packages/django/db/models/loading.py", line 64, in _populate
    self.load_app(app_name, True)
  File "/opt/edx/local/lib/python2.7/site-packages/django/db/models/loading.py", line 88, in load_app
    models = import_module('.models', app_name)
  File "/opt/edx/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/opt/wwc/edx-platform/lms/djangoapps/shoppingcart/models.py", line 22, in <module>
    from verify_student.models import SoftwareSecurePhotoVerification
  File "/opt/wwc/edx-platform/lms/djangoapps/verify_student/models.py", line 75, in <module>
    class PhotoVerification(StatusModel):
  File "/opt/wwc/edx-platform/lms/djangoapps/verify_student/models.py", line 116, in PhotoVerification
    DAYS_GOOD_FOR = settings.VERIFY_STUDENT["DAYS_GOOD_FOR"]
TypeError: string indices must be integers, not str
asset preprocessing failed!
node_modules/.bin/coffee --compile `find . -name *.coffee`

FATAL: all hosts have already failed -- aborting

command  rake lms:gather_assets:aws witch i find at code work fine if i run it without asible but asible-playbook always give this error. What i can do ?

**Comment by jarv** [comment]
I believe these issues should be resolved in the latest release, please retry and let us know if you have any problems.  Docs for installing the new devstack here - https://github.com/edx/configuration/wiki/edX-Developer-Stack
