### ISSUE TITLE
TASK: [gather lms static assets with rake] Fresh install 

### ISSUE THREAD

**Issue by plejik-zz** [openedx-unsupported/configuration#261]
I download latest version of edx code and install on clean install Ubuntu 12.04
    failed: [localhost] => {"changed": true, "cmd": " SERVICE_VARIANT=lms rake lms:gather_assets:aws ", "delta": "0:00:06.656451", "end": "2013-09-15 16:42:19.488543", "item": "", "rc": 1, "start": "2013-09-15 16:42:12.832092"}
    stderr: mkdir -p /opt/wwc/edx-platform/.ws_migrations_complete
    ./manage.py lms --settings aws preprocess_assets --traceback 
    xmodule_assets common/static/xmodule
    Traceback (most recent call last):
      File "./manage.py", line 95, in <module>
        execute_from_command_line([sys.argv[0]] + django_args)
      File "/opt/edx/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 443, in execute_from_command_line
        utility.execute()
      File "/opt/edx/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 382, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
      File "/opt/edx/local/lib/python2.7/site-packages/django/core/management/base.py", line 196, in run_from_argv
        self.execute(_args, *_options.**dict**)
      File "/opt/edx/local/lib/python2.7/site-packages/django/core/management/base.py", line 231, in execute
        self.validate()
      File "/opt/edx/local/lib/python2.7/site-packages/django/core/management/base.py", line 266, in validate
        num_errors = get_validation_errors(s, app)
      File "/opt/edx/local/lib/python2.7/site-packages/django/core/management/validation.py", line 30, in get_validation_errors
        for (app_name, error) in get_app_errors().items():
      File "/opt/edx/local/lib/python2.7/site-packages/django/db/models/loading.py", line 158, in get_app_errors
        self._populate()
      File "/opt/edx/local/lib/python2.7/site-packages/django/db/models/loading.py", line 64, in _populate
        self.load_app(app_name, True)
      File "/opt/edx/local/lib/python2.7/site-packages/django/db/models/loading.py", line 88, in load_app
        models = import_module('.models', app_name)
      File "/opt/edx/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
        __import__(name)
      File "/opt/wwc/edx-platform/lms/djangoapps/shoppingcart/models.py", line 22, in <module>
        from verify_student.models import SoftwareSecurePhotoVerification
      File "/opt/wwc/edx-platform/lms/djangoapps/verify_student/models.py", line 75, in <module>
        class PhotoVerification(StatusModel):
      File "/opt/wwc/edx-platform/lms/djangoapps/verify_student/models.py", line 116, in PhotoVerification
        DAYS_GOOD_FOR = settings.VERIFY_STUDENT["DAYS_GOOD_FOR"]
    TypeError: string indices must be integers, not str
    asset preprocessing failed!  
    node_modules/.bin/coffee --compile `find . -name *.coffee` 

```
FATAL: all hosts have already failed -- aborting
```

Can someone help with that problem.
I can only found that its, maybe, droped on rake lms.envs.aws config loading.
Thanks

**Comment by jbau** [comment]
I think your edx-platform wasn't late enough.  That error is fixed by this commit:
https://github.com/edx/edx-platform/commit/2f230836e0f6a87b359e582413f3fedbb9c7900c

**Comment by plejik-zz** [comment]
Strange i do it one day ago and yeap, i look at lms/envs/aws.py and there was old code, now i delete all witch connected to edx and try again. Write when try it again

**Comment by plejik-zz** [comment]
I have some problem
First delete all in /var/tmp/configuration /opt/wwc/edx-platform /opt/edx 
then do like here: https://github.com/edx/configuration/wiki#installing-edx-on-a-single-ubuntu-1204-precise-server 
BUT i have this error and still old code in less /opt/wwc/edx-platform/lms/envs/aws.py(i delete it before)
    VERIFY_STUDENT = AUTH_TOKENS.get("VERIFY_STUDENT", "")
Maybe can someone help with update through asimble

**Comment by plejik-zz** [comment]
I have one more epic episode
Can me someone explain 
first 
   `rm -rf /opt/wwc/edx-platform/`
then
`git clone https://github.com/edx/edx-platform /opt/wwc/edx-platform`
give right for www-data (like it be before )
than 
   `less /opt/wwc/edx-platform/lms/envs/aws.py`
     `....`
    `VERIFY_STUDENT = AUTH_TOKENS.get("VERIFY_STUDENT", VERIFY_STUDENT)`
Ok then 
`ansible-playbook -c local --limit "localhost:127.0.0.1" ./edx_sandbox.yml -i "localhost,"`
I give me my error which i have (look post early) and 
`less /opt/wwc/edx-platform/lms/envs/aws.py`
`VERIFY_STUDENT = AUTH_TOKENS.get("VERIFY_STUDENT", "")`

What the hell is going on?

**Comment by yrchen** [comment]
Using master branch of your edx-platform repo will fix this problem. #250

**Comment by plejik-zz** [comment]
Okay, will now try it

**Comment by plejik-zz** [comment]
So i try 
`ansible all -c local -i "localhost," --limit "localhost:127.0.0.1"  -m git -a "repo=https://github.com/edx/edx-platform  dest=/opt/wwc/edx-platform"`
I run in edx-platform
   rake lms:envs:aws
Yes its change aws.py and run,  but why i cant start it from master/configure(if i understand right - release) and start it like in manual and use it for create some courses for real task, not only for playing with it?
And, if you do not mind, where i can see some info about release or something like that because i see comment like
`and build from master instead of release(which is currently the default).`
or the way to use master. 
Than i can use it and during the using in real project i ll trying find bugs and error if its necessary

**Comment by jarv** [comment]
I believe these issues should be resolved in the latest release, please retry and let us know if you have any problems.  Docs for installing the new devstack here - https://github.com/edx/configuration/wiki/edX-Developer-Stack
