### ISSUE TITLE
Update script can not download AWS 

### ISSUE THREAD

**Issue by mstfldmr** [openedx-unsupported/configuration#2797]
ed-platform update command can not download the file https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz. I can download it using my browser.

`$sudo /edx/bin/update edx-platform master` 

```
TASK: [aws | install aws python packages] ************************************* 
failed: [localhost] => (item=https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz) => {"cmd": "/usr/local/bin/pip install -i https://pypi.python.org/simple https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz", "failed": true, "item": "https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz"}
msg: stdout: Collecting https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz
  Downloading https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz (460kB)

:stderr: Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 211, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip/commands/install.py", line 294, in run
    requirement_set.prepare_files(finder)
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 334, in prepare_files
    functools.partial(self._prepare_file, finder))
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 321, in _walk_req_to_install
    more_reqs = handler(req_to_install)
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 491, in _prepare_file
    session=self.session)
  File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 825, in unpack_url
    session,
  File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 673, in unpack_http_url
    from_path, content_type = _download_http_url(link, session, temp_dir)
  File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 886, in _download_http_url
    _download_url(resp, link, content_file)
  File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 621, in _download_url
    for chunk in progress_indicator(resp_read(4096), 4096):
  File "/usr/local/lib/python2.7/dist-packages/pip/utils/ui.py", line 133, in iter
    for x in it:
  File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 586, in resp_read
    decode_content=False):
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/response.py", line 307, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/response.py", line 267, in read
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
ReadTimeoutError: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Read timed out.
You are using pip version 7.1.2, however version 8.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

changed: [localhost] => (item=awscli==1.4.2)
changed: [localhost] => (item=boto=="2.34.0")

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
INFO:ansible.callback_plugins.datadog_tasks_timing:aws | install aws python packages ----------------------------------------------- 87.49s
INFO:ansible.callback_plugins.datadog_tasks_timing:server_utils | Install system packages ------------------------------------------ 13.56s
INFO:ansible.callback_plugins.datadog_tasks_timing:aws | install system packages --------------------------------------------------- 12.98s
INFO:ansible.callback_plugins.datadog_tasks_timing:aws | gather ec2 facts for use in other roles ----------------------------------- 10.42s
INFO:ansible.callback_plugins.datadog_tasks_timing:common | Install role-independent useful system packages ------------------------ 10.00s
INFO:ansible.callback_plugins.datadog_tasks_timing:common | Update CA Certificates -------------------------------------------------- 6.62s
INFO:ansible.callback_plugins.datadog_tasks_timing:common | pip install virtualenv -------------------------------------------------- 5.91s
INFO:ansible.callback_plugins.datadog_tasks_timing:common | Create common directories ----------------------------------------------- 2.46s
INFO:ansible.callback_plugins.datadog_tasks_timing:common | Copy the templates to their respestive destination ---------------------- 1.85s
INFO:ansible.callback_plugins.datadog_tasks_timing:aws | create all service directories --------------------------------------------- 1.10s
INFO:ansible.callback_plugins.datadog_tasks_timing:
Playbook edxapp finished: Tue Feb 23 09:39:26 2016, 49 total tasks.  0:02:38 elapsed. 

           to retry, use: --limit @/home/vagrant/edxapp.retry

localhost                  : ok=22   changed=3    unreachable=0    failed=1
```

**Comment by nedbat** [comment]
Sorry we have left this issue untended for so long.  GitHub issues are not meant for support questions.  Please use the [mailing list](https://groups.google.com/forum/#!forum/openedx-ops) or [Slack channels](https://open.edx.org/blog/open-edx-slack) to get help.
