### ISSUE TITLE
When i  run the "sudo ansible-playbook -c local --limit "localhost:127.0.0.1" \ ./edx_sandbox.yml -i "localhost,""  

### ISSUE THREAD

**Issue by fmyzjs** [openedx-unsupported/configuration#295]
TASK: [xqueue | syncdb and migrate] ******************************************\* 
failed: [localhost] => {"changed": true, "cmd": "sudo -u xqueue SERVICE_VARIANT=xqueue /opt/xqueue/virtualenvs/xqueue/bin/django-admin.py syncdb --migrate --noinput --settings=xqueue.aws_settings --pythonpath=/opt/wwc/xqueue ", "delta": "0:00:00.248935", "end": "2013-09-29 13:53:04.441978", "item": "", "rc": 1, "start": "2013-09-29 13:53:04.193043"}
stderr: Traceback (most recent call last):
  File "/opt/xqueue/virtualenvs/xqueue/bin/django-admin.py", line 5, in <module>
    management.execute_from_command_line()
  File "/opt/xqueue/virtualenvs/xqueue/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 443, in execute_from_command_line
    utility.execute()
  File "/opt/xqueue/virtualenvs/xqueue/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/xqueue/virtualenvs/xqueue/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 261, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/opt/xqueue/virtualenvs/xqueue/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 69, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/opt/xqueue/virtualenvs/xqueue/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    **import**(name)
  File "/opt/xqueue/virtualenvs/xqueue/local/lib/python2.7/site-packages/south/management/commands/**init**.py", line 13, in <module>
    from south.management.commands.syncdb import Command as SyncCommand
  File "/opt/xqueue/virtualenvs/xqueue/local/lib/python2.7/site-packages/south/management/commands/syncdb.py", line 17, in <module>
    from south.db import dbs
  File "/opt/xqueue/virtualenvs/xqueue/local/lib/python2.7/site-packages/south/db/**init**.py", line 81, in <module>
    db = dbs[DEFAULT_DB_ALIAS]
KeyError: 'default'

FATAL: all hosts have already failed -- aborting

PLAY RECAP *******************************************************************\* 
           to retry, use: --limit @/root/edx_sandbox.retry

localhost                  : ok=217  changed=63   unreachable=0    failed=1

**Comment by pchiu33** [comment]
Confirmed. With "master" branch though..

**Comment by jarv** [comment]
I see this as well, will have an update shortly.

**Comment by jarv** [comment]
fixed in https://github.com/edx/configuration/pull/297 which was just merged to master.
