### ISSUE TITLE
Error xqueue | syncdb and migrate: KeyError: 'default'

### ISSUE THREAD

**Issue by rafaelgou** [openedx-unsupported/configuration#314]
I'm facing the following error on Ubuntu 12.04. Using instructions from the wiki ([here](https://github.com/edx/configuration/wiki#installing-edx-on-a-single-ubuntu-1204-precise-server)), on a fresh server install.

``` bsh
TASK: [xqueue | syncdb and migrate] ******************************************* 
failed: [localhost] => {"changed": true, "cmd": "sudo -u xqueue SERVICE_VARIANT=xqueue /opt/xqueue/virtualenvs/xqueue/bin/django-admin.py syncdb --migrate --noinput --settings=xqueue.aws_settings --pythonpath=/opt/wwc/xqueue ", "delta": "0:00:00.224409", "end": "2013-09-28 01:06:03.675387", "item": "", "rc": 1, "start": "2013-09-28 01:06:03.450978"}
stderr: Traceback (most recent call last):
  File "/opt/xqueue/virtualenvs/xqueue/bin/django-admin.py", line 5, in <module>
    management.execute_from_command_line()
  File "/opt/xqueue/virtualenvs/xqueue/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 443, in execute_from_command_line
    utility.execute()
  File "/opt/xqueue/virtualenvs/xqueue/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/xqueue/virtualenvs/xqueue/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 261, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/opt/xqueue/virtualenvs/xqueue/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 69, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/opt/xqueue/virtualenvs/xqueue/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/opt/xqueue/virtualenvs/xqueue/local/lib/python2.7/site-packages/south/management/commands/__init__.py", line 13, in <module>
    from south.management.commands.syncdb import Command as SyncCommand
  File "/opt/xqueue/virtualenvs/xqueue/local/lib/python2.7/site-packages/south/management/commands/syncdb.py", line 17, in <module>
    from south.db import dbs
  File "/opt/xqueue/virtualenvs/xqueue/local/lib/python2.7/site-packages/south/db/__init__.py", line 81, in <module>
    db = dbs[DEFAULT_DB_ALIAS]
KeyError: 'default'

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/root/edx_sandbox.retry

localhost                  : ok=217  changed=62   unreachable=0    failed=1   
```

Any clue?

Thanks in advance!

**Comment by rafaelgou** [comment]
I'd made a full fresh install and... it worked. See that there was some updates on the code since the last try, so I really don't know if I took a buggy code or it was some issue on my environment. 

I'm gonna close, but I'm sorry I can't add some more info to trace that bug.
