### ISSUE TITLE
Error File contains no section headers

### ISSUE THREAD

**Issue by dattranvan22** [openedx-unsupported/configuration#3450]
I install edx platform on ubuntu 14.04 server. I have a error as:
```
failed: [localhost] => (item=ecommerce) => {"failed": true, "item": 
"ecommerce", "parsed": false}
BECOME-SUCCESS-qqxwsnqjuwdlqiceypuxqjqqgmxksnea
Traceback (most recent call last):
  File 
"/root/.ansible/tmp/ansible-tmp-1478350312.01-17978379956461/mysql_db", 
line 2117, in <module>
    main()
  File 
"/root/.ansible/tmp/ansible-tmp-1478350312.01-17978379956461/mysql_db", 
line 302, in main
    mycnf_creds = load_mycnf()
  File 
"/root/.ansible/tmp/ansible-tmp-1478350312.01-17978379956461/mysql_db", 
line 241, in load_mycnf
    config.readfp(open(mycnf))
  File "/usr/lib/python2.7/ConfigParser.py", line 324, in readfp
    self._read(fp, filename)
  File "/usr/lib/python2.7/ConfigParser.py", line 512, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
ConfigParser.MissingSectionHeaderError: File contains no section headers.
file: /root/.my.cnf, line: 1
'.my.cnf\n'

failed: [localhost] => (item=dashboard) => {"failed": true, "item": 
"dashboard", "parsed": false}
BECOME-SUCCESS-vxezvkbolyoathwhyrotycfupjghebez
Traceback (most recent call last):
  File 
"/root/.ansible/tmp/ansible-tmp-1478350312.14-165170842867263/mysql_db", 
line 2117, in <module>
    main()
  File 
"/root/.ansible/tmp/ansible-tmp-1478350312.14-165170842867263/mysql_db", 
line 302, in main
    mycnf_creds = load_mycnf()
  File 
"/root/.ansible/tmp/ansible-tmp-1478350312.14-165170842867263/mysql_db", 
line 241, in load_mycnf
    config.readfp(open(mycnf))
  File "/usr/lib/python2.7/ConfigParser.py", line 324, in readfp
    self._read(fp, filename)
  File "/usr/lib/python2.7/ConfigParser.py", line 512, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
ConfigParser.MissingSectionHeaderError: File contains no section headers.
file: /root/.my.cnf, line: 1
'.my.cnf\n'

failed: [localhost] => (item=xqueue) => {"failed": true, "item": "xqueue", 
"parsed": false}
BECOME-SUCCESS-hqexthgdkdtyrruddejmgfjrkzragxmi
Traceback (most recent call last):
  File 
"/root/.ansible/tmp/ansible-tmp-1478350312.25-150304816421409/mysql_db", 
line 2117, in <module>
    main()
  File 
"/root/.ansible/tmp/ansible-tmp-1478350312.25-150304816421409/mysql_db", 
line 302, in main
    mycnf_creds = load_mycnf()
  File 
"/root/.ansible/tmp/ansible-tmp-1478350312.25-150304816421409/mysql_db", 
line 241, in load_mycnf
    config.readfp(open(mycnf))
  File "/usr/lib/python2.7/ConfigParser.py", line 324, in readfp
    self._read(fp, filename)
  File "/usr/lib/python2.7/ConfigParser.py", line 512, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
ConfigParser.MissingSectionHeaderError: File contains no section headers.
file: /root/.my.cnf, line: 1
'.my.cnf\n'

failed: [localhost] => (item=edxapp) => {"failed": true, "item": "edxapp", 
"parsed": false}
BECOME-SUCCESS-vwjpxaflomslrbixcjryggpmmsmvvjdn
Traceback (most recent call last):
  File 
"/root/.ansible/tmp/ansible-tmp-1478350312.47-75162552994014/mysql_db", 
line 2117, in <module>
    main()
  File 
"/root/.ansible/tmp/ansible-tmp-1478350312.47-75162552994014/mysql_db", 
line 302, in main
    mycnf_creds = load_mycnf()
  File 
"/root/.ansible/tmp/ansible-tmp-1478350312.47-75162552994014/mysql_db", 
line 241, in load_mycnf
    config.readfp(open(mycnf))
  File "/usr/lib/python2.7/ConfigParser.py", line 324, in readfp
    self._read(fp, filename)
  File "/usr/lib/python2.7/ConfigParser.py", line 512, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
ConfigParser.MissingSectionHeaderError: File contains no section headers.
file: /root/.my.cnf, line: 1
'.my.cnf\n'

failed: [localhost] => (item=edxapp_csmh) => {"failed": true, "item": 
"edxapp_csmh", "parsed": false}
BECOME-SUCCESS-xhirlmujmhekpscnzxlqifrbvggtuqty
Traceback (most recent call last):
  File 
"/root/.ansible/tmp/ansible-tmp-1478350312.7-164768907979484/mysql_db", 
line 2117, in <module>
    main()
  File 
"/root/.ansible/tmp/ansible-tmp-1478350312.7-164768907979484/mysql_db", 
line 302, in main
    mycnf_creds = load_mycnf()
  File 
"/root/.ansible/tmp/ansible-tmp-1478350312.7-164768907979484/mysql_db", 
line 241, in load_mycnf
    config.readfp(open(mycnf))
  File "/usr/lib/python2.7/ConfigParser.py", line 324, in readfp
    self._read(fp, filename)
  File "/usr/lib/python2.7/ConfigParser.py", line 512, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
ConfigParser.MissingSectionHeaderError: File contains no section headers.
file: /root/.my.cnf, line: 1
'.my.cnf\n'

skipping: [localhost]
skipping: [localhost]
failed: [localhost] => (item=analytics-api) => {"failed": true, "item": 
"analytics-api", "parsed": false}
BECOME-SUCCESS-hmuytfpesxmcmohondqlwyykvbwpccpd
Traceback (most recent call last):
  File 
"/root/.ansible/tmp/ansible-tmp-1478350312.83-189800360794445/mysql_db", 
line 2117, in <module>
    main()
  File 
"/root/.ansible/tmp/ansible-tmp-1478350312.83-189800360794445/mysql_db", 
line 302, in main
    mycnf_creds = load_mycnf()
  File 
"/root/.ansible/tmp/ansible-tmp-1478350312.83-189800360794445/mysql_db", 
line 241, in load_mycnf
    config.readfp(open(mycnf))
  File "/usr/lib/python2.7/ConfigParser.py", line 324, in readfp
    self._read(fp, filename)
  File "/usr/lib/python2.7/ConfigParser.py", line 512, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
ConfigParser.MissingSectionHeaderError: File contains no section headers.
file: /root/.my.cnf, line: 1
'.my.cnf\n'

failed: [localhost] => (item=reports) => {"failed": true, "item": 
"reports", "parsed": false}
BECOME-SUCCESS-wsricuycumvrosbiakpfsecyowhorepq
Traceback (most recent call last):
  File 
"/root/.ansible/tmp/ansible-tmp-1478350313.0-139721930142716/mysql_db", 
line 2117, in <module>
    main()
  File 
"/root/.ansible/tmp/ansible-tmp-1478350313.0-139721930142716/mysql_db", 
line 302, in main
    mycnf_creds = load_mycnf()
  File 
"/root/.ansible/tmp/ansible-tmp-1478350313.0-139721930142716/mysql_db", 
line 241, in load_mycnf
    config.readfp(open(mycnf))
  File "/usr/lib/python2.7/ConfigParser.py", line 324, in readfp
    self._read(fp, filename)
  File "/usr/lib/python2.7/ConfigParser.py", line 512, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
ConfigParser.MissingSectionHeaderError: File contains no section headers.
file: /root/.my.cnf, line: 1
'.my.cnf\n'

skipping: [localhost]
skipping: [localhost]

FATAL: all hosts have already failed -- aborting
```

**Comment by nedbat** [comment]
This repo is not the right place to get support.  See http://open.edx.org/getting-help for options.
