### ISSUE TITLE
Error on TASK: [gather lms static assets with rake] 

### ISSUE THREAD

**Issue by wrshiromi** [openedx-unsupported/configuration#362]
I’m trying to install open edX platform by following “Installing edX on a single Ubuntu 12.04 (Precise) server” in this page https://github.com/edx/configuration/wiki#installing-edx-on-a-single-ubuntu-1204-virtual-machine-with-vagrant
However,  when I invoked the following command, I received the error:

**Command**

```
sudo ansible-playbook -c local --limit "localhost:127.0.0.1" /var/tmp/configuration/playbooks/edx_sandbox.yml \
-i "localhost," -e 'cms_nginx_port=80  lms_preview_nginx_port=80  c_lms_base=example.com \
c_preview_lms_base=preview.example.com'
```

**Error:**

```
TASK: [gather lms static assets with rake] ************************************ 
failed: [localhost] => {"changed": true, "cmd": " SERVICE_VARIANT=lms rake lms:gather_assets:aws ", "delta": "0:00:30.913455", "end": "2013-10-23 13:30:42.350326", "item": "", "rc": 1, "start": "2013-10-23 13:30:11.436871"}
stderr: mkdir -p /opt/wwc/edx-platform/.ws_migrations_complete
./manage.py lms --settings aws preprocess_assets --traceback 
xmodule_assets common/static/xmodule
2013-10-23 13:30:17,544 INFO 5041 [dd.dogapi] dog_stats_api.py:66 - Initializing dog api to use statsd: localhost, 8125
Traceback (most recent call last):
  File "./manage.py", line 91, in <module>
    startup.run()
  File "/opt/wwc/edx-platform/lms/startup.py", line 26, in run
    modulestore(store_name)
  File "/opt/wwc/edx-platform/common/lib/xmodule/xmodule/modulestore/django.py", line 113, in modulestore
    settings.MODULESTORE[name].get('OPTIONS', {})
  File "/opt/wwc/edx-platform/common/lib/xmodule/xmodule/modulestore/django.py", line 70, in create_modulestore_instance
    **_options
  File "/opt/wwc/edx-platform/common/lib/xmodule/xmodule/modulestore/mixed.py", line 37, in __init__
    store['OPTIONS']
  File "/opt/wwc/edx-platform/common/lib/xmodule/xmodule/modulestore/django.py", line 70, in create_modulestore_instance
    **_options
  File "/opt/wwc/edx-platform/common/lib/xmodule/xmodule/modulestore/mongo/base.py", line 287, in __init__
    do_connection(**doc_store_config)
TypeError: do_connection() takes at least 3 arguments (0 given)
asset preprocessing failed!
node_modules/.bin/coffee --compile `find . -name *.coffee` 

FATAL: all hosts have already failed -- aborting
```

line 261 In /opt/wwc/edx-platform/common/lib/xmodule/xmodule/modulestore/mongo/base.py explains as follows:

```
        :param doc_store_config: must have a host, db, and collection entries. Other common entries: port, tz_aware.
```

and line 271 to 273 has definition for do_connection() as follows.

```
        def do_connection(
            db, collection, host, port=27017, tz_aware=True, user=None, password=None, **kwargs
        ):
```

However, on line 287, do_connection() is called as follwos:

```
        do_connection(**doc_store_config)
```

any idea to avoid this error?

**Comment by yrchen** [comment]
I meet the same problem, any suggestion?

**Comment by feanil** [comment]
What version of ansible are you running with?  DOC_STORE config was added
to platform about 2 weeks ago along with an update to the configuration
repo to set default values for it.  The default values are set in
`playbooks/roles/edxapp/defaults/main.yml`

**Comment by yrchen** [comment]
@feanil Thank you for your information. I updated my configuration repo and it fixed now.

**Comment by wrshiromi** [comment]
Could you tell me more details how to solve the issue? my playbooks/roles/edxapp/defaults/main.yml does not have  DOC_STORE; should I update ansible after I installed requirement.txt?

```
sudo apt-get install -y python-pip git-core build-essential python-dev libxml2-dev libxslt-dev
cd /var/tmp
git clone -b release https://github.com/edx/configuration
cd /var/tmp/configuration
sudo pip install -r requirements.txt
```

*\* Now, update ansible**
and then,

```
cd /var/tmp/configuration/playbooks
ansible-playbook -c local --limit "localhost:127.0.0.1" /var/tmp/configuration/playbooks/edx_sandbox.yml \
-i "localhost," -e 'cms_nginx_port=80  lms_preview_nginx_port=80  c_lms_base=example.com \
c_preview_lms_base=preview.example.com'
```

**Comment by yrchen** [comment]
I checked the master and release branch, the default values of "DOC_STORE_CONFIG" are already been set in
`playbooks/roles/edxapp/defaults/main.yml`.

https://github.com/edx/configuration/blob/master/playbooks/roles/edxapp/defaults/main.yml
https://github.com/edx/configuration/blob/release/playbooks/roles/edxapp/defaults/main.yml

**Comment by feanil** [comment]
Those are the defaults, they will only work for you if you have an instance
of mysql running locally with no password for the root mysql user.

**Comment by wrshiromi** [comment]
Thanks for your help.
I have cloned https://github.com/edx/configuration this morning; however, the installation has been aborted with the following errors. Are there anything I should modify before I invoke ansible-playbook command?

```
TASK: [ora | install python post-requirements] ******************************** 
failed: [localhost] => {"cmd": "/opt/edx-ora/virtualenvs/edx-ora/bin/pip install -r /opt/wwc/edx-ora/requirements.txt", "failed": true, "item": ""}
msg: stdout: Downloading/unpacking Django==1.4.3 (from -r /opt/wwc/edx-ora/base_requirements.txt (line 1))
  Running setup.py egg_info for package Django

Downloading/unpacking dogstatsd-python==0.2 (from -r /opt/wwc/edx-ora/base_requirements.txt (line 2))
  Downloading dogstatsd-python-0.2.tar.gz
  Running setup.py egg_info for package dogstatsd-python

Requirement already satisfied (use --upgrade to upgrade): path.py==3.0 in /opt/edx-ora/virtualenvs/edx-ora/lib/python2.7/site-packages (from -r /opt/wwc/edx-ora/base_requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): pip in /opt/edx-ora/virtualenvs/edx-ora/lib/python2.7/site-packages (from -r /opt/wwc/edx-ora/base_requirements.txt (line 4))
Downloading/unpacking South==0.7.6 (from -r /opt/wwc/edx-ora/base_requirements.txt (line 5))
  Running setup.py egg_info for package South

Downloading/unpacking reportlab==2.6 (from -r /opt/wwc/edx-ora/base_requirements.txt (line 6))
  Running setup.py egg_info for package reportlab
    ################################################
    #Attempting install of _rl_accel, sgmlop & pyHnj
    #extensions from '/opt/edx-ora/virtualenvs/edx-ora/build/reportlab/src/rl_addons/rl_accel'
    ################################################
    ################################################
    #Attempting install of _renderPM
    #extensions from '/opt/edx-ora/virtualenvs/edx-ora/build/reportlab/src/rl_addons/renderPM'
    # installing with freetype version 21
    ################################################
    Downloading standard T1 font curves
    Finished download of standard T1 font curves


    ########## SUMMARY INFO #########
    ################################################
    #Attempting install of _rl_accel, sgmlop & pyHnj
    #extensions from '/opt/edx-ora/virtualenvs/edx-ora/build/reportlab/src/rl_addons/rl_accel'
    ################################################
    ################################################
    #Attempting install of _renderPM
    #extensions from '/opt/edx-ora/virtualenvs/edx-ora/build/reportlab/src/rl_addons/renderPM'
    # installing with freetype version 21
    ################################################
    Downloading standard T1 font curves
    Finished download of standard T1 font curves
Downloading/unpacking requests==1.1.0 (from -r /opt/wwc/edx-ora/base_requirements.txt (line 7))
  Running setup.py egg_info for package requests

Requirement already satisfied (use --upgrade to upgrade): pytz==2012h in /opt/edx-ora/virtualenvs/edx-ora/lib/python2.7/site-packages (from -r /opt/wwc/edx-ora/base_requirements.txt (line 8))
Downloading/unpacking MySQL-python==1.2.4 (from -r /opt/wwc/edx-ora/base_requirements.txt (line 9))
  Running setup.py egg_info for package MySQL-python
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.28.tar.gz
    Extracting in /tmp/tmpTn9yZ1
    Now working in /tmp/tmpTn9yZ1/distribute-0.6.28
    Building a Distribute egg in /opt/edx-ora/virtualenvs/edx-ora/build/MySQL-python
    /opt/edx-ora/virtualenvs/edx-ora/build/MySQL-python/distribute-0.6.28-py2.7.egg

Downloading/unpacking boto==2.6.0 (from -r /opt/wwc/edx-ora/base_requirements.txt (line 10))
  Running setup.py egg_info for package boto

    warning: no files found matching 'boto/mturk/test/*.doctest'
    warning: no files found matching 'boto/mturk/test/.gitignore'
Requirement already satisfied (use --upgrade to upgrade): lxml==3.0.1 in /opt/edx-ora/virtualenvs/edx-ora/lib/python2.7/site-packages (from -r /opt/wwc/edx-ora/base_requirements.txt (line 11))
Downloading/unpacking django-celery==3.0.11 (from -r /opt/wwc/edx-ora/base_requirements.txt (line 12))
  Running setup.py egg_info for package django-celery

    no previously-included directories found matching 'bin/*.pyc'
    no previously-included directories found matching 'tests/*.pyc'
    no previously-included directories found matching 'docs/*.pyc'
    no previously-included directories found matching 'extra/*.pyc'
    no previously-included directories found matching 'djcelery/*.pyc'
    no previously-included directories found matching 'docs/.build'
    no previously-included directories found matching 'examples/*.pyc'
Downloading/unpacking celery-with-redis==3.0 (from -r /opt/wwc/edx-ora/base_requirements.txt (line 13))
  Downloading celery-with-redis-3.0.tar.gz
  Running setup.py egg_info for package celery-with-redis

Downloading/unpacking django-nose==1.1 (from -r /opt/wwc/edx-ora/base_requirements.txt (line 14))
  Downloading django-nose-1.1.tar.gz
  Running setup.py egg_info for package django-nose

    warning: no previously-included files matching '*.py[co]' found under directory 'django_nose'
    warning: no previously-included files matching '*.py[co]' found under directory 'testapp'
Obtaining ease from git+https://github.com/edx/ease.git@965a61b0701bb93bebdcd7173c3538008a1ea009#egg=ease (from -r /opt/wwc/edx-ora/base_requirements.txt (line 15))
  Cloning https://github.com/edx/ease.git (to 965a61b0701bb93bebdcd7173c3538008a1ea009) to /opt/edx-ora/virtualenvs/edx-ora/src/ease
  Could not find a tag or branch '965a61b0701bb93bebdcd7173c3538008a1ea009', assuming commit.
  Running setup.py egg_info for package ease

    package init file 'ease/data/nltk_data/__init__.py' not found (or not a regular file)
Requirement already satisfied (use --upgrade to upgrade): scipy==0.11.0 in /opt/edx-ora/virtualenvs/edx-ora/lib/python2.7/site-packages (from -r /opt/wwc/edx-ora/requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): coverage==3.5.3 in /opt/edx-ora/virtualenvs/edx-ora/lib/python2.7/site-packages (from -r /opt/wwc/edx-ora/requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): sphinx==1.1.3 in /opt/edx-ora/virtualenvs/edx-ora/lib/python2.7/site-packages (from -r /opt/wwc/edx-ora/requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): django-sphinx-autodoc==0.2 in /opt/edx-ora/virtualenvs/edx-ora/lib/python2.7/site-packages (from -r /opt/wwc/edx-ora/requirements.txt (line 5))
Downloading/unpacking matplotlib==1.2.0 (from -r /opt/wwc/edx-ora/requirements.txt (line 6))
  You are installing an externally hosted file. Future versions of pip will default to disallowing externally hosted files.
  You are installing a potentially insecure and unverifiable file. Future versions of pip will default to disallowing insecure files.
  Error timed out while getting https://downloads.sourceforge.net/project/matplotlib/matplotlib/matplotlib-1.2.0/matplotlib-1.2.0.tar.gz (from https://pypi.python.org/simple/matplotlib/)
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/opt/edx-ora/virtualenvs/edx-ora/local/lib/python2.7/site-packages/pip/basecommand.py", line 134, in main
    status = self.run(options, args)
  File "/opt/edx-ora/virtualenvs/edx-ora/local/lib/python2.7/site-packages/pip/commands/install.py", line 236, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/opt/edx-ora/virtualenvs/edx-ora/local/lib/python2.7/site-packages/pip/req.py", line 1092, in prepare_files
    self.unpack_url(url, location, self.is_download)
  File "/opt/edx-ora/virtualenvs/edx-ora/local/lib/python2.7/site-packages/pip/req.py", line 1238, in unpack_url
    retval = unpack_http_url(link, location, self.download_cache, self.download_dir)
  File "/opt/edx-ora/virtualenvs/edx-ora/local/lib/python2.7/site-packages/pip/download.py", line 602, in unpack_http_url
    resp = _get_response_from_url(target_url, link)
  File "/opt/edx-ora/virtualenvs/edx-ora/local/lib/python2.7/site-packages/pip/download.py", line 638, in _get_response_from_url
    resp = urlopen(target_url)
  File "/opt/edx-ora/virtualenvs/edx-ora/local/lib/python2.7/site-packages/pip/download.py", line 176, in __call__
    response = self.get_opener(scheme=scheme).open(url)
  File "/usr/lib/python2.7/urllib2.py", line 406, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 519, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 438, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 625, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 400, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 418, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1207, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1180, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1030, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 407, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 365, in _read_status
    line = self.fp.readline()
  File "/usr/lib/python2.7/socket.py", line 447, in readline
    data = self._sock.recv(self._rbufsize)
timeout: timed out

Storing complete log in /root/.pip/pip.log


FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/wruser/edx_sandbox.retry

localhost                  : ok=268  changed=208  unreachable=0    failed=1   

```

**Comment by feanil** [comment]
Looks like pypi timed-out for you.  make sure you can get to the url that
timed out https://downloads.sourceforge.net/.... and then you  can probably
just restart the build.

**Comment by wrshiromi** [comment]
Thank you. 
Based on the following extracted error message, I downloaded https://downloads.sourceforge.net/project/matplotlib/matplotlib/matplotlib-1.2.0/matplotlib-1.2.0.tar.gz on my machine...
Cold you tell me where I should locate this file and extract it?

```
[...]
Downloading/unpacking matplotlib==1.2.0 (from -r /opt/wwc/edx-ora/requirements.txt (line 6))
  You are installing an externally hosted file. Future versions of pip will default to disallowing externally hosted files.
  You are installing a potentially insecure and unverifiable file. Future versions of pip will default to disallowing insecure files.
  Error timed out while getting https://downloads.sourceforge.net/project/matplotlib/matplotlib/matplotlib-1.2.0/matplotlib-1.2.0.tar.gz (from https://pypi.python.org/simple/matplotlib/)
Cleaning up...
[...]
```

**Comment by feanil** [comment]
Downloading it locally wasn't necessary, I just wanted you to make sure you could reach pypi, you can probably just restart the ansible run.

**Comment by wrshiromi** [comment]
I could install without fail!
Thanks a lot!

**Comment by feanil** [comment]
awesome.
