### ISSUE TITLE
Ficus.1 certs process restarts constantly

### ISSUE THREAD

**Issue by nedbat** [openedx-unsupported/configuration#3717]
/edx/var/log/supervisor/certs-stdout.log shows this over and over:
```
2017-02-27 17:31:43,261 CRITICAL 8266 [openedx_certificates.queue_xqueue] queue_xqueue.py:62 - Unable to get queue length: No JSON object could be decoded
2017-02-27 17:31:44,899 INFO 8271 [requests.packages.urllib3.connectionpool] connectionpool.py:180 - Starting new HTTP connection (1): localhost
```
certs-stderr.log shows:
```
PdfReadWarning: Xref table not zero-indexed. ID numbers for objects will not be corrected. [pdf.py:1503]
Traceback (most recent call last):
  File "/edx/app/certs/certificates/certificate_agent.py", line 197, in <module>
    main()
  File "/edx/app/certs/certificates/certificate_agent.py", line 64, in main
    if manager.get_length() == 0:
  File "/edx/app/certs/certificates/openedx_certificates/queue_xqueue.py", line 57, in get_length
    response = json.loads(request.text)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```
Changing /edx/app/xqueue/xqueue.env.json from 
```
    "RABBIT_TLS": true,
```
to
```
    "RABBIT_TLS": false,
```
fixes the problem.

Should we default this to false?
XQUEUE_RABBITMQ_TLS is the Ansible variable.

@bdero This was originally your PR: opinions?
@sambapete provided the clue.
@edx/devops other ramifications?

**Comment by bdero** [comment]
@nedbat Yes you are right, sorry about this - I'm not sure why I had it set to true, it really should default to False. I've opened a PR to fix it here: #3718
