### ISSUE TITLE
Devstack install fails on master (ecommerce migration error)

### ISSUE THREAD

**Issue by msegado** [openedx-unsupported/configuration#3747]
Steps to replicate:
```sh
$ curl -OL https://raw.githubusercontent.com/edx/configuration/master/util/install/install_stack.sh
$ bash install_stack.sh devstack master
```

This fails with the following ecommerce migration error:
```
(...)
==> default: TASK [ecommerce : Migrate] *****************************************************
==> default: fatal: [localhost]: FAILED! => {"changed": true, "cmd": "DB_MIGRATION_USER='migrate' DB_MIGRATION_PASS='password' /edx/app/ecommerce/venvs/ecommerce/bin/python ./manage.py migrate --noinput", "delta": "0:00:35.183908", "end": "2017-03-09 22:22:48.275018", "failed": true, "rc": 1, "start": "2017-03-09 22:22:13.091110", "stderr": "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.\n  return meta(name, bases, d)\n\nTraceback (most recent call last):\n  File \"./manage.py\", line 10, in <module>\n    execute_from_command_line(sys.argv)\n  File \"/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/django/core/management/__init__.py\", line 353, in execute_from_command_line\n    utility.execute()\n  File \"/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/django/core/management/__init__.py\", line 345, in execute\n    self.fetch_command(subcommand).run_from_argv(self.argv)\n  File \"/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/django/core/management/base.py\", line 348, in run_from_argv\n    self.execute(*args, **cmd_options)\n  File \"/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/django/core/management/base.py\", line 399, in execute\n    output = self.handle(*args, **options)\n  File \"/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py\", line 200, in handle\n    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)\n  File \"/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/django/db/migrations/executor.py\", line 92, in migrate\n    self._migrate_all_forwards(plan, full_plan, fake=fake, fake_initial=fake_initial)\n  File \"/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/django/db/migrations/executor.py\", line 121, in _migrate_all_forwards\n    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)\n  File \"/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/django/db/migrations/executor.py\", line 198, in apply_migration\n    state = migration.apply(state, schema_editor)\n  File \"/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/django/db/migrations/migration.py\", line 123, in apply\n    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)\n  File \"/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/django/db/migrations/operations/models.py\", line 59, in database_forwards\n    schema_editor.create_model(model)\n  File \"/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/django/db/backends/base/schema.py\", line 284, in create_model\n    self.execute(sql, params or None)\n  File \"/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/django/db/backends/base/schema.py\", line 110, in execute\n    cursor.execute(sql, params)\n  File \"/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/django/db/backends/utils.py\", line 79, in execute\n    return super(CursorDebugWrapper, self).execute(sql, params)\n  File \"/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/django/db/backends/utils.py\", line 64, in execute\n    return self.cursor.execute(sql, params)\n  File \"/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/django/db/utils.py\", line 95, in __exit__\n    six.reraise(dj_exc_type, dj_exc_value, traceback)\n  File \"/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/django/db/backends/utils.py\", line 62, in execute\n    return self.cursor.execute(sql)\n  File \"/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py\", line 112, in execute\n    return self.cursor.execute(query, args)\n  File \"/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/MySQLdb/cursors.py\", line 205, in execute\n    self.errorhandler(self, exc, value)\n  File \"/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/MySQLdb/connections.py\", line 36, in defaulterrorhandler\n    raise errorclass, errorvalue\ndjango.db.utils.OperationalError: (1050, \"Table 'thumbnail_kvstore' already exists\")", "stdout": "2017-03-09 22:22:17,130 WARNING 7893 [py.warnings] /edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/django/db/models/fields/subclassing.py:22 - /edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.\n  return meta(name, bases, d)\n\nOperations to perform:\n  Apply all migrations: refund, sailthru, flatpages, sites, analytics, voucher, invoice, partner, offer, catalogue, contenttypes, thumbnail, core, wishlists, sessions, auth, address, waffle, payment, customer, referrals, promotions, admin, social_auth, shipping, theming, reviews, courses, basket, order\nRunning migrations:\n  Rendering model states... DONE\n  Applying admin.0002_logentry_remove_auto_add... OK\n  Applying auth.0007_alter_validators_add_error_messages... OK\n  Applying basket.0008_auto_20170215_2224... OK\n  Applying basket.0009_auto_20170215_2229... OK\n  Applying catalogue.0021_auto_20170215_2224... OK\n  Applying catalogue.0022_auto_20170215_2229... OK\n  Applying catalogue.0023_auto_20170215_2234... OK\n  Applying catalogue.0024_fix_enrollment_code_slug... OK\n  Applying core.0023_siteconfiguration_send_refund_notifications... OK\n  Applying core.0024_auto_20170208_1520... OK\n  Applying core.0025_auto_20170214_0003... OK\n  Applying core.0026_auto_20170215_2234... OK\n  Applying customer.0003_auto_20170215_2229... OK\n  Applying invoice.0004_auto_20170215_2234... OK\n  Applying offer.0008_range_course_catalog... OK\n  Applying offer.0009_range_enterprise_customer... OK\n  Applying offer.0010_auto_20170215_2224... OK\n  Applying offer.0011_auto_20170215_2324... OK\n  Applying order.0012_auto_20170215_2224... OK\n  Applying order.0013_auto_20170215_2229... OK\n  Applying payment.0013_sdncheckfailure... OK\n  Applying payment.0014_sdncheckfailure_site... OK\n  Applying payment.0015_auto_20170215_2229... OK\n  Applying payment.0016_auto_20170227_1402... OK\n  Applying referrals.0004_auto_20170215_2234... OK\n  Applying reviews.0002_update_email_length... OK\n  Applying reviews.0003_auto_20160802_1358... OK\n  Applying sites.0002_alter_domain_unique... OK\n  Applying thumbnail.0001_initial...", "stdout_lines": ["2017-03-09 22:22:17,130 WARNING 7893 [py.warnings] /edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/django/db/models/fields/subclassing.py:22 - /edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.", "  return meta(name, bases, d)", "", "Operations to perform:", "  Apply all migrations: refund, sailthru, flatpages, sites, analytics, voucher, invoice, partner, offer, catalogue, contenttypes, thumbnail, core, wishlists, sessions, auth, address, waffle, payment, customer, referrals, promotions, admin, social_auth, shipping, theming, reviews, courses, basket, order", "Running migrations:", "  Rendering model states... DONE", "  Applying admin.0002_logentry_remove_auto_add... OK", "  Applying auth.0007_alter_validators_add_error_messages... OK", "  Applying basket.0008_auto_20170215_2224... OK", "  Applying basket.0009_auto_20170215_2229... OK", "  Applying catalogue.0021_auto_20170215_2224... OK", "  Applying catalogue.0022_auto_20170215_2229... OK", "  Applying catalogue.0023_auto_20170215_2234... OK", "  Applying catalogue.0024_fix_enrollment_code_slug... OK", "  Applying core.0023_siteconfiguration_send_refund_notifications... OK", "  Applying core.0024_auto_20170208_1520... OK", "  Applying core.0025_auto_20170214_0003... OK", "  Applying core.0026_auto_20170215_2234... OK", "  Applying customer.0003_auto_20170215_2229... OK", "  Applying invoice.0004_auto_20170215_2234... OK", "  Applying offer.0008_range_course_catalog... OK", "  Applying offer.0009_range_enterprise_customer... OK", "  Applying offer.0010_auto_20170215_2224... OK", "  Applying offer.0011_auto_20170215_2324... OK", "  Applying order.0012_auto_20170215_2224... OK", "  Applying order.0013_auto_20170215_2229... OK", "  Applying payment.0013_sdncheckfailure... OK", "  Applying payment.0014_sdncheckfailure_site... OK", "  Applying payment.0015_auto_20170215_2229... OK", "  Applying payment.0016_auto_20170227_1402... OK", "  Applying referrals.0004_auto_20170215_2234... OK", "  Applying reviews.0002_update_email_length... OK", "  Applying reviews.0003_auto_20160802_1358... OK", "  Applying sites.0002_alter_domain_unique... OK", "  Applying thumbnail.0001_initial..."], "warnings": []}
==> default: 
==> default: RUNNING HANDLER [mongo : restart mongo] ****************************************
==> default: 
==> default: RUNNING HANDLER [forum : restart the forum service] ****************************
==> default: 	to retry, use: --limit @/edx/app/edx_ansible/edx_ansible/playbooks/vagrant-devstack.retry
==> default: 
==> default: PLAY RECAP *********************************************************************
==> default: localhost                  : ok=223  changed=84   unreachable=0    failed=1   
==> default: INFO:/edx/app/edx_ansible/edx_ansible/playbooks/callback_plugins/task_timing: migrate ----------------------------------------------------------------------- 475.95s
==> default: INFO:/edx/app/edx_ansible/edx_ansible/playbooks/callback_plugins/task_timing: Take security updates during ansible runs ------------------------------------- 130.63s
==> default: INFO:/edx/app/edx_ansible/edx_ansible/playbooks/callback_plugins/task_timing: checkout edx-platform repo into /edx/app/edxapp/edx-platform ------------------ 124.30s
==> default: INFO:/edx/app/edx_ansible/edx_ansible/playbooks/callback_plugins/task_timing: install python requirements ---------------------------------------------------- 90.53s
==> default: INFO:/edx/app/edx_ansible/edx_ansible/playbooks/callback_plugins/task_timing: Migrate ------------------------------------------------------------------------ 35.64s
==> default: INFO:/edx/app/edx_ansible/edx_ansible/playbooks/callback_plugins/task_timing: Install node dependencies ------------------------------------------------------ 31.78s
==> default: INFO:/edx/app/edx_ansible/edx_ansible/playbooks/callback_plugins/task_timing: Install application requirements ----------------------------------------------- 29.39s
==> default: INFO:/edx/app/edx_ansible/edx_ansible/playbooks/callback_plugins/task_timing: compiling all py files in the edx-platform repo -------------------------------- 22.40s
==> default: INFO:/edx/app/edx_ansible/edx_ansible/playbooks/callback_plugins/task_timing: install node dependencies ------------------------------------------------------ 14.41s
==> default: INFO:/edx/app/edx_ansible/edx_ansible/playbooks/callback_plugins/task_timing: update rubygems ---------------------------------------------------------------- 12.07s
==> default: INFO:/edx/app/edx_ansible/edx_ansible/playbooks/callback_plugins/task_timing:
==> default: Playbook Configure instance(s) finished: 2017-03-09 22:22:48.292394, 349 total tasks.  0:18:59.743373 elapsed. 
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

The python stack trace (from the stderr log in the output above) shows a problem with the `thumbnail_kvstore` table:
```
  Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 200, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 92, in migrate
    self._migrate_all_forwards(plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 121, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 198, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/django/db/migrations/migration.py", line 123, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/django/db/migrations/operations/models.py", line 59, in database_forwards
    schema_editor.create_model(model)
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 284, in create_model
    self.execute(sql, params or None)
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 110, in execute
    cursor.execute(sql, params)
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 112, in execute
    return self.cursor.execute(query, args)
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
    django.db.utils.OperationalError: (1050, "Table 'thumbnail_kvstore' already exists")
```

Refs from `/edx/bin/show-repo-heads` in the devstack VM:
- edx/configuration@4ae4e057
- edx/edx-platform@0c30c06a78
- edx/ecommerce@cecf03c
- edx/ecommerce-worker@0664f43
- edx/edx-demo-course@743b552
- edx/cs_comments_service@1acbf22
- edx/notifier@c334599
- edx/programs@8200475

**Comment by msegado** [comment]
A workaround from @robrap (via Slack) for anyone else who runs into this before it's fixed:

> export CONFIGURATION_VERSION=jlajoie/set-forums-version
>
> This turns off ecommerce deployment. It also changes forums deployment to a branch, and that is no longer needed.

**Comment by robrap** [comment]
@clintonb Do you know if this is related to the thumbnail instructions here?: https://openedx.atlassian.net/wiki/display/COMM/Ginkgo
These instructions did not solve the issue for @jlajoie.
Is there a ticket for this?

**Comment by clintonb** [comment]
What is the result of running `./manage.py migrate thumbnail --fake --settings=ecommerce.settings.production`?

**Comment by jlajoie** [comment]
So the steps I took for a clean devstack build were:

1. curl the Vagrantfile
2. Run `vagrant plugin install vagrant-vbguest`
3. Run `vagrant up --provider virtualbox`
4. The above command fails with `"Table 'thumbnail_kvstore' already exists"`
5. Run `vagrant ssh`
6. Run `sudo vi /etc/passwd` and set the `ecommerce` user to use `/bin/bash` instead of `/bin/false`
7. Run `sudo su ecommerce`
8. Run `cd /edx/app/ecommerce/ecommerce`
9. Run `./manage.py migrate thumbnail --fake` which does succeed
10. Exit out of the vagrant image and run `vagrant provision`, which proceeds to fail

The last step errors out, though I don't have a capture of the above vagrant provision but I can reproduce if needed. I'm not positive if step 10 was the right way to go about re-running.

**Comment by clintonb** [comment]
I need to see the failure output in order to debug. I suspect this may be due to switching `settings/devstack.py` to be focused on Docker-based devstack; but, can't say for certain without log output.

**Comment by clintonb** [comment]
One potential quick fix for this is to add a task to run the fake migrate. Ideally, we should regenerate the DB dump for devstack so that this command does not need to be run. I have neither the knowledge nor time to take on the DB dump.

**Comment by robrap** [comment]
@edx/devops How do you feel about the above quick fix and then is removing later once the DB dump has been regenerated?

**Comment by robrap** [comment]
@clintonb Is there a ticket I can follow?  I'd like to know when I can update my devstack.  Thanks.

**Comment by clintonb** [comment]
@robrap I'm not actively working on this. I still haven't seen a stack trace showing that faking the migration fails. There is no ticket as far as I know.

**Comment by robrap** [comment]
Ok.  No worries.  I'll play around with this.  Thanks @clintonb.

**Comment by robrap** [comment]
@msegado If you need it, you can use `export CONFIGURATION_VERSION=robrap/devstack-workaround` as a temporary workaround for the issue while we work on a more permanent fix.

**Comment by msegado** [comment]
Thanks @robrap and all; closing since this seems to have been fixed by #3756.

**Comment by nedbat** [comment]
@clintonb @robrap I didn't think this affected fresh Ficus installs, but it seems to.  What is the root cause of the table pre-existing?

**Comment by clintonb** [comment]
@nedbat See the E-Commerce Service release notes at https://openedx.atlassian.net/wiki/display/COMM/Ginkgo. The `thumbnail` app previously did not use Django migrations. Now it does.

**Comment by nedbat** [comment]
@clintonb was that change made after the Ficus branch was started (Jan 10th)?  Why is it affecting new Ficus installs? Or do we think those are spurious reports?

**Comment by clintonb** [comment]
These changes were merged in February: https://github.com/edx/ecommerce/pull/1157. I'm not sure why Ficus would be affected.
