### ISSUE TITLE
 paver devstack lms  failed

### ISSUE THREAD

**Issue by somilguptadrc** [openedx-unsupported/configuration#3966]
/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/social/apps/django_app/default/models.py:104: RemovedInDjango19Warning: Model class social.apps.django_app.default.models.Code doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class Code(models.Model, DjangoCodeMixin):

2017-07-04 02:06:21,724 WARNING 25592 [py.warnings] base.py:116 - /edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/social/apps/django_app/default/models.py:104: RemovedInDjango19Warning: Model class social.apps.django_app.default.models.Code doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class Code(models.Model, DjangoCodeMixin):

2017-07-04 02:06:22,540 INFO 25592 [urllib3.connectionpool] connectionpool.py:257 - Starting new HTTP connection (1): localhost
2017-07-04 02:06:22,542 INFO 25592 [elasticsearch] base.py:63 - HEAD http://localhost:9200/courseware_index [status:200 request:0.002s]
No handlers could be found for logger "elasticsearch.trace"
2017-07-04 02:06:22,543 INFO 25592 [elasticsearch] base.py:63 - HEAD http://localhost:9200/courseware_index [status:200 request:0.001s]
2017-07-04 02:06:22,545 INFO 25592 [elasticsearch] base.py:63 - HEAD http://localhost:9200/courseware_index/courseware_content [status:200 request:0.002s]
2017-07-04 02:06:22,548 WARNING 25592 [elasticsearch] base.py:82 - GET /courseware_index/_mapping/courseware_content [status:404 request:0.002s]
Traceback (most recent call last):
  File "manage.py", line 116, in <module>
    execute_from_command_line([sys.argv[0]] + django_args)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/edx/app/edxapp/edx-platform/cms/djangoapps/contentstore/management/commands/reindex_course.py", line 97, in handle
    ) if index_exists and doc_type_exists else {}
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/elasticsearch/client/indices.py", line 313, in get_mapping
    '_mapping', doc_type), params=params)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/elasticsearch/transport.py", line 307, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 93, in perform_request
    self._raise_error(response.status, raw_data)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 105, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.NotFoundError: TransportError(404, u'{"_index":"courseware_index","_type":"_mapping","_id":"courseware_content","exists":false}')

Captured Task Output:
---------------------

---> pavelib.servers.devstack
---> pavelib.prereqs.install_prereqs
---> pavelib.prereqs.install_node_prereqs
---> pavelib.prereqs.install_python_prereqs
---> pavelib.prereqs.uninstall_python_packages
pip freeze > /edx/app/edxapp/edx-platform/test_root/log/pip_freeze.log
python manage.py cms --settings=devstack reindex_course --setup

Build failed running pavelib.servers.devstack: Subprocess return code: 1

**Comment by clemente** [comment]
I also found this, after updating my branch to the latest code and doing update_db and fixing a django-social-auth-migration.
Some other info to debug this:

http://127.0.0.1:9200/courseware_index/_mapping/courseware_content returns 404, but http://127.0.0.1:9200/courseware_index/_mapping/ works and returns:

    {"courseware_index":{"courseware_content":{"properties":{"content":{"properties":{"capa_content":{"type":"string"},"display_name":{"type":"string"},"html_content":{"type":"string"},"transcript_en":{"type":"string"}}},"content_groups":{"type":"string","index":"not_analyzed","norms":{"enabled":false},"index_options":"docs"},"content_type":{"type":"string","index":"not_analyzed","norms":{"enabled":false},"index_options":"docs"},"course":{"type":"string","index":"not_analyzed","norms":{"enabled":false},"index_options":"docs"},"course_name":{"type":"string","index":"not_analyzed","norms":{"enabled":false},"index_options":"docs"},"id":{"type":"string","index":"not_analyzed","norms":{"enabled":false},"index_options":"docs"},"location":{"type":"string","index":"not_analyzed","norms":{"enabled":false},"index_options":"docs"},"org":{"type":"string","index":"not_analyzed","norms":{"enabled":false},"index_options":"docs"},"problem_types":{"type":"string","index":"not_analyzed","norms":{"enabled":false},"index_options":"docs"},"start_date":{"type":"date","format":"dateOptionalTime"}}},"course_info":{"properties":{"content":{"properties":{"display_name":{"type":"string"},"number":{"type":"string"},"overview":{"type":"string"}}},"course":{"type":"string","index":"not_analyzed","norms":{"enabled":false},"index_options":"docs"},"id":{"type":"string","index":"not_analyzed","norms":{"enabled":false},"index_options":"docs"},"image_url":{"type":"string","index":"not_analyzed","norms":{"enabled":false},"index_options":"docs"},"modes":{"type":"string","index":"not_analyzed","norms":{"enabled":false},"index_options":"docs"},"number":{"type":"string","index":"not_analyzed","norms":{"enabled":false},"index_options":"docs"},"org":{"type":"string","index":"not_analyzed","norms":{"enabled":false},"index_options":"docs"},"start":{"type":"string","index":"not_analyzed","norms":{"enabled":false},"index_options":"docs"}}}}}

ElasticSearch is working, because http://localhost:9200/courseware_index/_search?pretty=true&q=*:* returns the data of the demo course.

I tried to disable ElasticSearch through lms.env.json and cms.env.json but it didn't disable the initial reindex.

As a workaround, I went to `edx-platform/pavelib/servers.py`and commented the following line:

    sh(django_cmd('cms', settings, 'reindex_course', '--setup'))

This stopped the ElasticSearch errors.
