### ISSUE TITLE
ImportError: No module named settings.local

### ISSUE THREAD

**Issue by gytlinux** [openedx-unsupported/configuration#4759]
https://openedx.atlassian.net/wiki/spaces/OpenOPS/pages/146440579/Native+Open+edX+Ubuntu+16.04+64+bit+Installation
Install  ginkgo.master,ECommerce is running wrong after installation:

[2018-09-06 12:11:18 +0000] [14572] [INFO] Worker exiting (pid: 14572)
[2018-09-06 12:11:18 +0000] [14574] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/gunicorn/arbiter.py
", line 557, in spawn_worker    worker.init_process()
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/gunicorn/workers/gg
event.py", line 190, in init_process    super(GeventWorker, self).init_process()
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/gunicorn/workers/ba
se.py", line 126, in init_process    self.load_wsgi()
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/gunicorn/workers/ba
se.py", line 136, in load_wsgi    self.wsgi = self.app.wsgi()
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/gunicorn/app/base.p
y", line 67, in wsgi    self.callable = self.load()
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/gunicorn/app/wsgiap
p.py", line 65, in load    return self.load_wsgiapp()
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/gunicorn/app/wsgiap
p.py", line 52, in load_wsgiapp    return util.import_app(self.app_uri)
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/gunicorn/util.py", 
line 357, in import_app    __import__(module)
  File "/edx/app/ecommerce/ecommerce/ecommerce/wsgi.py", line 29, in <module>
    application = get_wsgi_application()
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/django/core/wsgi.py
", line 13, in get_wsgi_application    django.setup(set_prefix=False)
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/django/__init__.py"
, line 22, in setup    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/django/conf/__init_
_.py", line 53, in __getattr__    self._setup(name)
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/django/conf/__init_
_.py", line 41, in _setup    self._wrapped = Settings(settings_module)
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/django/conf/__init_
_.py", line 97, in __init__    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named settings.local

What is the reason, because the installation is not successful? Is there anything else that needs to be set up?

**Comment by nedbat** [comment]
We can't provide support in GitHub issues.  See https://openedx.org/getting-help for Slack and mailing lists.
