### ISSUE TITLE
Renaming from mitxmako to edxmako causes gathering static assets to fail

### ISSUE THREAD

**Issue by hanwentao** [openedx-unsupported/configuration#523]
I ran the latest release branch of configuration (3e03770), and it failed.

```
TASK: [edxapp | gather  static assets with rake] ******************************
failed: [localhost] => (item=lms) => {"changed": true, "cmd": "SERVICE_VARIANT=lms rake lms:gather_assets:aws ", "delta": "0:00:10.661481", "end": "2013-12-04 15:12:38.34689
7", "item": "lms", "rc": 1, "start": "2013-12-04 15:12:27.685416"}
stderr: mkdir -p /edx/app/edxapp/edx-platform/.ws_migrations_complete
./manage.py lms --settings aws preprocess_assets --traceback
xmodule_assets common/static/xmodule
2013-12-04 10:12:29,430 INFO 28509 [dd.dogapi] dog_stats_api.py:66 - Initializing dog api to use statsd: localhost, 8125
Traceback (most recent call last):
  File "./manage.py", line 91, in <module>
    startup.run()
  File "/edx/app/edxapp/edx-platform/lms/startup.py", line 26, in run
    modulestore(store_name)
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/modulestore/django.py", line 113, in modulestore
    settings.MODULESTORE[name].get('OPTIONS', {})
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/modulestore/django.py", line 70, in create_modulestore_instance
    **_options
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/modulestore/mixed.py", line 37, in __init__
    store['OPTIONS']
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/modulestore/django.py", line 52, in create_modulestore_instance
    _options[key] = load_function(_options[key])
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/modulestore/django.py", line 38, in load_function
    return getattr(import_module(module_path), name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named mitxmako.shortcuts
asset preprocessing failed!
node_modules/.bin/coffee --compile `find lms/ cms/ common/ -type f -name *.coffee`
changed: [localhost] => (item=cms)

FATAL: all hosts have already failed -- aborting
```

**Comment by hanwentao** [comment]
Sorry, I think it's an issue in the master branch of edx-platform project.
