### ISSUE TITLE
Following Ubuntu 12.04 installation on AWS fails at TASK: [edxapp | gather  static assets with rake]

### ISSUE THREAD

**Issue by rmurray68** [openedx-unsupported/configuration#546]
Using Amazon AWS
Public Internet facing (No VPC) 
AMI: ubuntu-precise-12.04-amd64-server-20131003 (ami-a73264ce)

Following Procedure for Ubuntu 12.04 installation: https://github.com/edx/configuration/wiki/edX-Ubuntu-12.04-Installation
(Followed explicitly, no changes to procedure)

Fails with:
TASK: [edxapp | gather  static assets with rake] *****************************\* 
failed: [localhost] => (item=lms) => {"changed": true, "cmd": "SERVICE_VARIANT=lms rake lms:gather_assets:aws ", "delta": "0:01:04.883483", "end": "2013-12-13 21:30:12.014876", "item": "lms", "rc": 1, "start": "2013-12-13 21:29:07.131393"}
stderr: mkdir -p /edx/app/edxapp/edx-platform/.ws_migrations_complete
xmodule_assets common/static/xmodule./manage.py lms --settings aws preprocess_assets --traceback 

2013-12-13 16:29:09,330 INFO 32039 [dd.dogapi] dog_stats_api.py:66 - Initializing dog api to use statsd: localhost, 8125
node_modules/.bin/coffee --compile `find lms/ cms/ common/ -type f -name *.coffee` 
sass --style compressed --load-path ./common/static/sass --update -E utf-8 _/static
./manage.py lms --settings aws collectstatic --traceback --noinput > /dev/null
2013-12-13 16:29:45,091 INFO 32075 [dd.dogapi] dog_stats_api.py:66 - Initializing dog api to use statsd: localhost, 8125
Traceback (most recent call last):
  File "./manage.py", line 95, in <module>
    execute_from_command_line([sys.argv[0]] + django_args)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 443, in execute_from_command_line
    utility.execute()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/base.py", line 196, in run_from_argv
    self.execute(_args, **options.**dict**)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/base.py", line 232, in execute
    output = self.handle(_args, *_options)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/base.py", line 371, in handle
    return self.handle_noargs(**options)
  File "/edx/app/edxapp/venvs/edxapp/src/django-staticfiles/staticfiles/management/commands/collectstatic.py", line 169, in handle_noargs
    collected = self.collect()
  File "/edx/app/edxapp/venvs/edxapp/src/django-staticfiles/staticfiles/management/commands/collectstatic.py", line 126, in collect
    for original_path, processed_path, processed in processor:
  File "/edx/app/edxapp/venvs/edxapp/src/django-staticfiles/staticfiles/storage.py", line 279, in post_process
    content = pattern.sub(converter, content)
  File "/edx/app/edxapp/venvs/edxapp/src/django-staticfiles/staticfiles/storage.py", line 218, in converter
    hashed_url = self.url(unquote(joined_result), force=True)
  File "/edx/app/edxapp/venvs/edxapp/src/django-staticfiles/staticfiles/storage.py", line 164, in url
    hashed_name = self.hashed_name(clean_name).replace('\', '/')
  File "/edx/app/edxapp/venvs/edxapp/src/django-staticfiles/staticfiles/storage.py", line 127, in hashed_name
    (clean_name, self))
ValueError: The file 'v6/k3k702ZOKiLJc3WVjuplzKRDOzjiPcYnFooOUGCOsRk.woff' could not be found with <pipeline.storage.PipelineCachedStorage object at 0x3f4a310>.
collectstatic failed!
stdout:   overwrite cms/static/sass/style-app-extend1.css
  overwrite cms/static/sass/style-app.css
  overwrite cms/static/sass/style-xmodule.css
  overwrite lms/static/sass/application-extend1.css
  overwrite lms/static/sass/application-extend2.css
  overwrite lms/static/sass/application.css
  overwrite lms/static/sass/course.css
  overwrite lms/static/sass/ie.css
failed: [localhost] => (item=cms) => {"changed": true, "cmd": "SERVICE_VARIANT=cms rake cms:gather_assets:aws ", "delta": "0:00:43.273887", "end": "2013-12-13 21:30:55.477573", "item": "cms", "rc": 1, "start": "2013-12-13 21:30:12.203686"}
stderr: ./manage.py cms --settings aws preprocess_assets --traceback 
xmodule_assets common/static/xmodule
2013-12-13 16:30:13,950 INFO 32123 [dd.dogapi] dog_stats_api.py:66 - Initializing dog api to use statsd: localhost, 8125
sass --style compressed --load-path ./common/static/sass --update -E utf-8 _/static
node_modules/.bin/coffee --compile `find lms/ cms/ common/ -type f -name *.coffee` 
./manage.py cms --settings aws collectstatic --traceback --noinput > /dev/null
2013-12-13 16:30:33,170 INFO 32161 [dd.dogapi] dog_stats_api.py:66 - Initializing dog api to use statsd: localhost, 8125
Traceback (most recent call last):
  File "./manage.py", line 95, in <module>
    execute_from_command_line([sys.argv[0]] + django_args)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 443, in execute_from_command_line
    utility.execute()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/base.py", line 196, in run_from_argv
    self.execute(_args, **options.**dict**)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/base.py", line 232, in execute
    output = self.handle(_args, *_options)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/base.py", line 371, in handle
    return self.handle_noargs(**options)
  File "/edx/app/edxapp/venvs/edxapp/src/django-staticfiles/staticfiles/management/commands/collectstatic.py", line 169, in handle_noargs
    collected = self.collect()
  File "/edx/app/edxapp/venvs/edxapp/src/django-staticfiles/staticfiles/management/commands/collectstatic.py", line 126, in collect
    for original_path, processed_path, processed in processor:
  File "/edx/app/edxapp/venvs/edxapp/src/django-staticfiles/staticfiles/storage.py", line 279, in post_process
    content = pattern.sub(converter, content)
  File "/edx/app/edxapp/venvs/edxapp/src/django-staticfiles/staticfiles/storage.py", line 218, in converter
    hashed_url = self.url(unquote(joined_result), force=True)
  File "/edx/app/edxapp/venvs/edxapp/src/django-staticfiles/staticfiles/storage.py", line 164, in url
    hashed_name = self.hashed_name(clean_name).replace('\', '/')
  File "/edx/app/edxapp/venvs/edxapp/src/django-staticfiles/staticfiles/storage.py", line 127, in hashed_name
    (clean_name, self))
ValueError: The file 'v6/k3k702ZOKiLJc3WVjuplzKRDOzjiPcYnFooOUGCOsRk.woff' could not be found with <pipeline.storage.PipelineCachedStorage object at 0x2e47850>.
collectstatic failed!
stdout:   overwrite lms/static/sass/application-extend1.css
  overwrite lms/static/sass/application-extend2.css
  overwrite lms/static/sass/application.css
  overwrite lms/static/sass/course.css

FATAL: all hosts have already failed -- aborting

PLAY RECAP *******************************************************************\* 
           to retry, use: --limit @/home/ubuntu/edx_sandbox.retry

localhost                  : ok=120  changed=104  unreachable=0    failed=1   

ubuntu@ip-10-124-67-151:/var/tmp/configuration/playbooks$

**Comment by jarv** [comment]
You can workaround this issue for now by ussing commit https://github.com/edx/edx-platform/commit/ee292fdf17bfb1d028403a74bfa0bc1932354d60, will update as soon as we have a fixed merged.

**Comment by rmurray68** [comment]
Using the commit described, it does move past that part in the playbook now.
But....
It seems to be having a challenge with "install nltk data using rendered shell script"
- It has dropped my ssh connection more than once. Feels like a timeout issue
- I am now trying "screen" so that the session keeps running if I disconnect

Has anyone seen this new symptom?

**Comment by jarv** [comment]
The original issue is now fixed on edx-platform master so I'm going to close this. For your other issue can you give us the full ansible play output? Please open up a new issue (to keep it separate) if you continue to have issues.
