### ISSUE TITLE
time out error when ok=106,changed=22

### ISSUE THREAD

**Issue by lg2578** [openedx-unsupported/configuration#610]
Downloading from URL http://localhost:4040/root/pypi/+f/7075e08ef06155e07002189b837cde85/Django-1.4.8.tar.gz#md5=7075e08ef06155e07002189b837cde85 (from http://localhost:4040/root/pypi/+simple/Django/)
Cleaning up...

  Removing temporary dir /edx/app/edxapp/venvs/edxapp/build...
Exception:
Traceback (most recent call last):
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pip/basecommand.py", line 134, in main
    status = self.run(options, args)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pip/commands/install.py", line 236, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pip/req.py", line 1092, in prepare_files
    self.unpack_url(url, location, self.is_download)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pip/req.py", line 1238, in unpack_url
    retval = unpack_http_url(link, location, self.download_cache, self.download_dir)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pip/download.py", line 622, in unpack_http_url
    download_hash = _download_url(resp, link, temp_location)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pip/download.py", line 495, in _download_url
    chunk = resp.read(4096)
  File "/usr/lib/python2.7/socket.py", line 380, in read
    data = self._sock.recv(left)
  File "/usr/lib/python2.7/httplib.py", line 561, in read
    s = self.fp.read(amt)
  File "/usr/lib/python2.7/socket.py", line 380, in read
    data = self._sock.recv(left)
timeout: timed out

**Comment by pku9104038** [comment]
did you resolve this problem?
i have meet this problem too, my solution is change the mirror site of pypi will be helpful.
