### ISSUE TITLE
six is not in the edxapp base requirements

### ISSUE THREAD

**Issue by sgunadhya** [openedx-unsupported/configuration#641]
I get this error 

Obtaining ddt from git+https://github.com/edx/ddt.git@afef6647edb488afc471b0239ef8c4b0669e5fdf#egg=ddt (from -r /edx/app/edxapp/edx-platform/requireme
nts/edx/github.txt (line 27))
  Cloning https://github.com/edx/ddt.git (to afef6647edb488afc471b0239ef8c4b0669e5fdf) to /edx/app/edxapp/venvs/edxapp/src/ddt
  Could not find a tag or branch 'afef6647edb488afc471b0239ef8c4b0669e5fdf', assuming commit.
  Running setup.py egg_info for package ddt
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/edx/app/edxapp/venvs/edxapp/src/ddt/setup.py", line 5, in <module>
        from ddt import **version**
      File "ddt.py", line 4, in <module>
        import six
    ImportError: No module named six
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

during the task
TASK: [edxapp | install python base-requirements] *****************************

**Comment by sgunadhya** [comment]
This is not relevant to configuration
