### ISSUE TITLE
Error while deleting course from sysadmin panel

### ISSUE THREAD

**Issue by sushanthpy** [openedx-unsupported/configuration#645]
Hi Team,

Getting below error while deleting a course from sysadmin, i have provided course id also but it shows strange error message Must pass in a course_id when calling get_items() with MixedModuleStore.

Jan 15 14:43:36 li654-38 [service_variant=lms][django.request][env:sandbox] ERROR [li654-38  6351] [base.py:215] - Internal Server Error: /sysadmin/courses
Traceback (most recent call last):
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, _callback_args, *_callback_kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/views/generic/base.py", line 48, in view
    return self.dispatch(request, _args, *_kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/decorators.py", line 25, in _wrapper
    return bound_func(_args, *_kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, _args, *_kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/decorators.py", line 21, in bound_func
    return func(self, _args2, *_kwargs2)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/decorators.py", line 25, in _wrapper
    return bound_func(_args, *_kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
    return view_func(request, _args, *_kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/decorators.py", line 21, in bound_func
    return func(self, _args2, *_kwargs2)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/decorators.py", line 25, in _wrapper
    return bound_func(_args, *_kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 75, in _cache_controlled
    response = viewfunc(request, _args, *_kw)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/decorators.py", line 21, in bound_func
    return func(self, _args2, *_kwargs2)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/decorators.py", line 25, in _wrapper
    return bound_func(_args, *_kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/views/decorators/http.py", line 147, in inner
    response = func(request, _args, *_kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/decorators.py", line 21, in bound_func
    return func(self, _args2, *_kwargs2)
  File "/edx/app/edxapp/edx-platform/lms/djangoapps/dashboard/sysadmin.py", line 76, in dispatch
    return super(SysadminDashboardView, self).dispatch(_args, *_kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in dispatch
    return handler(request, _args, *_kwargs)
  File "/edx/app/edxapp/edx-platform/lms/djangoapps/dashboard/sysadmin.py", line 555, in post
    delete_course(self.def_ms, content_store, loc, commit)
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/modulestore/store_utilities.py", line 267, in delete_course
    modules = modulestore.get_items([source_location.tag, source_location.org , source_location.course, None, None, None])
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/modulestore/mixed.py", line 75, in get_items
    raise Exception("Must pass in a course_id when calling get_items() with MixedModuleStore")
Exception: Must pass in a course_id when calling get_items() with MixedModuleStore

**Comment by edx-secure** [comment]
Hi Sushanth,

This looks like an issue with edx-platform not with configuration.  Please
report it on the edx-platform github project.

**Comment by sushanthpy** [comment]
Thank you for the response. reported.
