### ISSUE TITLE
TASK: [edxapp | gather  static assets with rake] ERROR

### ISSUE THREAD

**Issue by pku9104038** [openedx-unsupported/configuration#679]
failed: [localhost] => (item=lms) => {"changed": true, "cmd": "SERVICE_VARIANT=lms rake lms:gather_assets:aws ", "delta": "0:00:11.894950", "end": "2014-01-23 16:18:15.164879", "item": "lms", "rc": 1, "start": "2014-01-23 16:18:03.269929"}
stderr: mkdir -p /edx/app/edxapp/edx-platform/.ws_migrations_complete
./manage.py lms --settings aws preprocess_assets --traceback 
xmodule_assets common/static/xmodule
Traceback (most recent call last):
  File "./manage.py", line 90, in <module>
    startup = importlib.import_module(edx_args.startup)
  File "/usr/lib/python2.7/importlib/**init**.py", line 37, in import_module
    **import**(name)
  File "/edx/app/edxapp/edx-platform/lms/startup.py", line 8, in <module>
    settings.INSTALLED_APPS  # pylint: disable=W0104
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/functional.py", line 184, in inner
    self._setup()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/conf/__init__.py", line 42, in _setup
    self._wrapped = Settings(settings_module)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/conf/__init__.py", line 135, in **init**
    logging_config_func(self.LOGGING)
  File "/usr/lib/python2.7/logging/config.py", line 777, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/lib/python2.7/logging/config.py", line 575, in configure
    '%r: %s' % (name, e))
ValueError: Unable to configure handler 'newrelic': Cannot resolve 'lms.lib.newrelic_logging.NewRelicHandler': cannot import name profile_trace
asset preprocessing failed!
node_modules/.bin/coffee --compile `find lms/ cms/ common/ -type f -name *.coffee` 
failed: [localhost] => (item=cms) => {"changed": true, "cmd": "SERVICE_VARIANT=cms rake cms:gather_assets:aws ", "delta": "0:00:07.991368", "end": "2014-01-23 16:18:23.266279", "item": "cms", "rc": 1, "start": "2014-01-23 16:18:15.274911"}
stderr: ./manage.py cms --settings aws preprocess_assets --traceback 
xmodule_assets common/static/xmodule
Traceback (most recent call last):
  File "./manage.py", line 90, in <module>
    startup = importlib.import_module(edx_args.startup)
  File "/usr/lib/python2.7/importlib/**init**.py", line 37, in import_module
    **import**(name)
  File "/edx/app/edxapp/edx-platform/cms/startup.py", line 7, in <module>
    settings.INSTALLED_APPS  # pylint: disable=W0104
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/functional.py", line 184, in inner
    self._setup()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/conf/__init__.py", line 42, in _setup
    self._wrapped = Settings(settings_module)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/conf/__init__.py", line 135, in **init**
    logging_config_func(self.LOGGING)
  File "/usr/lib/python2.7/logging/config.py", line 777, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/lib/python2.7/logging/config.py", line 575, in configure
    '%r: %s' % (name, e))
ValueError: Unable to configure handler 'newrelic': Cannot resolve 'lms.lib.newrelic_logging.NewRelicHandler': cannot import name profile_trace
asset preprocessing failed!
node_modules/.bin/coffee --compile `find lms/ cms/ common/ -type f -name *.coffee`

**Comment by hkim823** [comment]
are you still having issues?  what were you running exactly and in which stack when this occured?

**Comment by hkim823** [comment]
Closing due to lack of response
