### ISSUE TITLE
ora: TypeError: 'bool' object is not iterable

### ISSUE THREAD

**Issue by xcompass** [openedx-unsupported/configuration#735]
When response to self evaluation to an ora question, got the following stack trace in cmstderr.log. Failed both on local and sandbox.

![screen shot 2014-02-03 at 3 09 38 pm](https://f.cloud.github.com/assets/465548/2071392/52ca4f12-8d28-11e3-875a-c85f88b89cf9.png)

```
2014-02-03 18:04:36,715 ERROR 5227 [contentstore.views.preview] preview.py:83 - error processing ajax call
Traceback (most recent call last):
  File "/edx/app/edxapp/edx-platform/cms/djangoapps/contentstore/views/preview.py", line 67, in preview_handler
    resp = instance.handle(handler, req, suffix)
  File "/edx/app/edxapp/venvs/edxapp/src/xblock/xblock/core.py", line 283, in handle
    return self.runtime.handle(self, handler_name, request, suffix)
  File "/edx/app/edxapp/venvs/edxapp/src/xblock/xblock/runtime.py", line 645, in handle
    results = handler(request, suffix)
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/x_module.py", line 442, in xmodule_handler
    response_data = self.handle_ajax(suffix, request_post)
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/combined_open_ended_module.py", line 449, in handle_ajax
    return_value = self.child_module.handle_ajax(dispatch, data)
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/open_ended_grading_classes/combined_open_ended_modulev1.py", line 894, in handle_ajax
    return self.update_task_states_ajax(return_html)
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/open_ended_grading_classes/combined_open_ended_modulev1.py", line 762, in update_task_states_ajax
    changed = self.update_task_states()
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/open_ended_grading_classes/combined_open_ended_modulev1.py", line 753, in update_task_states
    self.setup_next_task()
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/open_ended_grading_classes/combined_open_ended_modulev1.py", line 504, in setup_next_task
    instance_state=current_task_state)
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/open_ended_grading_classes/openendedchild.py", line 156, in __init__
    self.setup_response(system, location, definition, descriptor)
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/open_ended_grading_classes/open_ended_module.py", line 80, in setup_response
    success, message = self.send_to_grader(self.latest_answer(), system)
TypeError: 'bool' object is not iterable
2014-02-03 18:04:36,718 ERROR 5227 [root] exceptions.py:9 - Uncaught exception from <class 'django.core.handlers.wsgi.WSGIHandler'>
Traceback (most recent call last):
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/edx/app/edxapp/edx-platform/cms/djangoapps/contentstore/views/preview.py", line 67, in preview_handler
    resp = instance.handle(handler, req, suffix)
  File "/edx/app/edxapp/venvs/edxapp/src/xblock/xblock/core.py", line 283, in handle
    return self.runtime.handle(self, handler_name, request, suffix)
  File "/edx/app/edxapp/venvs/edxapp/src/xblock/xblock/runtime.py", line 645, in handle
    results = handler(request, suffix)
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/x_module.py", line 442, in xmodule_handler
    response_data = self.handle_ajax(suffix, request_post)
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/combined_open_ended_module.py", line 449, in handle_ajax
    return_value = self.child_module.handle_ajax(dispatch, data)
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/open_ended_grading_classes/combined_open_ended_modulev1.py", line 894, in handle_ajax
    return self.update_task_states_ajax(return_html)
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/open_ended_grading_classes/combined_open_ended_modulev1.py", line 762, in update_task_states_ajax
    changed = self.update_task_states()
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/open_ended_grading_classes/combined_open_ended_modulev1.py", line 753, in update_task_states
    self.setup_next_task()
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/open_ended_grading_classes/combined_open_ended_modulev1.py", line 504, in setup_next_task
    instance_state=current_task_state)
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/open_ended_grading_classes/openendedchild.py", line 156, in __init__
    self.setup_response(system, location, definition, descriptor)
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/open_ended_grading_classes/open_ended_module.py", line 80, in setup_response
    success, message = self.send_to_grader(self.latest_answer(), system)
TypeError: 'bool' object is not iterable
2014-02-03 18:04:36,720 ERROR 5227 [django.request] base.py:215 - Internal Server Error: /preview/xblock/i4x:;_;_UBC;_PAN101;_combinedopenended;_0a5c3225d28e45378c0407b71855e26f/handler/xmodule_handler/save_assessment
Traceback (most recent call last):
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/edx/app/edxapp/edx-platform/cms/djangoapps/contentstore/views/preview.py", line 67, in preview_handler
    resp = instance.handle(handler, req, suffix)
File "/edx/app/edxapp/venvs/edxapp/src/xblock/xblock/core.py", line 283, in handle
    return self.runtime.handle(self, handler_name, request, suffix)
  File "/edx/app/edxapp/venvs/edxapp/src/xblock/xblock/runtime.py", line 645, in handle
    results = handler(request, suffix)
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/x_module.py", line 442, in xmodule_handler
    response_data = self.handle_ajax(suffix, request_post)
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/combined_open_ended_module.py", line 449, in handle_ajax
    return_value = self.child_module.handle_ajax(dispatch, data)
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/open_ended_grading_classes/combined_open_ended_modulev1.py", line 894, in handle_ajax
    return self.update_task_states_ajax(return_html)
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/open_ended_grading_classes/combined_open_ended_modulev1.py", line 762, in update_task_states_ajax
    changed = self.update_task_states()
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/open_ended_grading_classes/combined_open_ended_modulev1.py", line 753, in update_task_states
    self.setup_next_task()
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/open_ended_grading_classes/combined_open_ended_modulev1.py", line 504, in setup_next_task
    instance_state=current_task_state)
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/open_ended_grading_classes/openendedchild.py", line 156, in __init__
    self.setup_response(system, location, definition, descriptor)
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/open_ended_grading_classes/open_ended_module.py", line 80, in setup_response
    success, message = self.send_to_grader(self.latest_answer(), system)
TypeError: 'bool' object is not iterable
```

**Comment by dhasthagheer** [comment]
I am getting same error. Is this issue solved?

**Comment by hkim823** [comment]
this is an old issue, closing this for now, if it's sitll an issue please update and let us know
