### ISSUE TITLE
_mysql_exceptions - Access denied for user 'edxapp001'@'localhost

### ISSUE THREAD

**Issue by sasasaftic** [openedx-unsupported/configuration#773]
When I run (on edx installed with these instructions https://github.com/edx/configuration/wiki/edX-Ubuntu-12.04-Installation):

```
sudo /edx/bin/update edx-platform master
```

I get this error:

```
failed: [localhost] => {"changed": true, "cmd": " /edx/app/edxapp/venvs/edxapp/bin/python manage.py lms syncdb --migrate --noinput --settings=aws_migrate ", "delta": "0:00:04.234532", "end": "2014-02-11 10:27:08.130702", "item": "", "rc": 1, "start": "2014-02-11 10:27:03.896170"}
stderr: 2014-02-11 04:27:05,828 INFO 27992 [dd.dogapi] dog_stats_api.py:66 - Initializing dog api to use statsd: localhost, 8125
Traceback (most recent call last):
  File "manage.py", line 95, in <module>
    execute_from_command_line([sys.argv[0]] + django_args)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 443, in execute_from_command_line
    utility.execute()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/base.py", line 196, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/base.py", line 231, in execute
    self.validate()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/base.py", line 266, in validate
    num_errors = get_validation_errors(s, app)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/validation.py", line 103, in get_validation_errors
    connection.validation.validate_field(e, opts, f)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/backends/mysql/validation.py", line 14, in validate_field
    db_version = self.connection.get_server_version()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 415, in get_server_version
    self.cursor().close()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 319, in cursor
    cursor = util.CursorWrapper(self._cursor(), self)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 387, in _cursor
    self.connection = Database.connect(**kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 187, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
_mysql_exceptions.OperationalError: (1045, "Access denied for user 'edxapp001'@'localhost' (using password: YES)")

FATAL: all hosts have already failed -- aborting
```

P.s. installation was successful - then I tried above command for my (forked) edx-platform repo and it failed. When I tried to restore it back (using above command) I still get this error.

**Comment by edx-secure** [comment]
I'll give this a try, can you also test on a fresh machine with the newest
release.  The release branch should now be updated.

**Comment by mercefan** [comment]
Same happened here with a fresh machine when updating discern, xqueue, ease and ora.
Failed also when updating edx-platform trying to compile all py files.

**Comment by mercefan** [comment]
Forget about the failed when updating edx-platform trying to compile all py files.

But, when update edx-plaftorm master, happens similar problem:

TASK: [edxapp | gather  static assets with rake] *****************************\* 
failed: [localhost] => (item=lms) => {"changed": true, "cmd": "SERVICE_VARIANT=lms rake lms:gather_assets:aws ", "delta": "0:00:19.164128", "end": "2014-02-13 08:50:08.861112", "item": "lms", "rc": 1, "start": "2014-02-13 08:49:49.696984"}
stderr: mkdir -p /edx/app/edxapp/edx-platform/.ws_migrations_complete
./manage.py lms --settings aws preprocess_assets --traceback 
xmodule_assets common/static/xmodule
2014-02-13 03:49:53,126 INFO 17313 [dd.dogapi] dog_stats_api.py:66 - Initializing dog api to use statsd: localhost, 8125
node_modules/.bin/coffee --compile `find lms/ cms/ common/ -type f -name *.coffee` 
Traceback (most recent call last):
  File "./manage.py", line 95, in <module>
    execute_from_command_line([sys.argv[0]] + django_args)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 443, in execute_from_command_line
    utility.execute()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/base.py", line 196, in run_from_argv
    self.execute(_args, *_options.**dict**)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/base.py", line 231, in execute
    self.validate()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/base.py", line 266, in validate
    num_errors = get_validation_errors(s, app)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/validation.py", line 103, in get_validation_errors
    connection.validation.validate_field(e, opts, f)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/backends/mysql/validation.py", line 14, in validate_field
    db_version = self.connection.get_server_version()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 415, in get_server_version
    self.cursor().close()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/backends/**init**.py", line 319, in cursor
    cursor = util.CursorWrapper(self._cursor(), self)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 387, in _cursor
    self.connection = Database.connect(**kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(_args, *_kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 187, in **init**
    super(Connection, self).**init**(_args, *_kwargs2)
_mysql_exceptions.OperationalError: (1045, "Access denied for user 'edxapp001'@'localhost' (using password: YES)")
asset preprocessing failed!
failed: [localhost] => (item=cms) => {"changed": true, "cmd": "SERVICE_VARIANT=cms rake cms:gather_assets:aws ", "delta": "0:00:16.925966", "end": "2014-02-13 08:50:26.418247", "item": "cms", "rc": 1, "start": "2014-02-13 08:50:09.492281"}
stderr: ./manage.py cms --settings aws preprocess_assets --traceback 
xmodule_assets common/static/xmodule
2014-02-13 03:50:12,036 INFO 17746 [dd.dogapi] dog_stats_api.py:66 - Initializing dog api to use statsd: localhost, 8125
Traceback (most recent call last):
  File "./manage.py", line 95, in <module>
    execute_from_command_line([sys.argv[0]] + django_args)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 443, in execute_from_command_line
    utility.execute()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/base.py", line 196, in run_from_argv
    self.execute(_args, *_options.**dict**)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/base.py", line 231, in execute
    self.validate()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/base.py", line 266, in validate
    num_errors = get_validation_errors(s, app)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/validation.py", line 103, in get_validation_errors
    connection.validation.validate_field(e, opts, f)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/backends/mysql/validation.py", line 14, in validate_field
    db_version = self.connection.get_server_version()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 415, in get_server_version
    self.cursor().close()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/backends/**init**.py", line 319, in cursor
    cursor = util.CursorWrapper(self._cursor(), self)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 387, in _cursor
    self.connection = Database.connect(**kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(_args, *_kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 187, in **init**
    super(Connection, self).**init**(_args, *_kwargs2)
_mysql_exceptions.OperationalError: (1045, "Access denied for user 'edxapp001'@'localhost' (using password: YES)")
asset preprocessing failed!
node_modules/.bin/coffee --compile `find lms/ cms/ common/ -type f -name *.coffee` 

FATAL: all hosts have already failed -- aborting

**Comment by mercefan** [comment]
It seems that is solved by adding an edxapp001 user to mysql with the password = password.
It worked for me.

**Comment by mercefan** [comment]
updating went well, but when trying to load either cms or lms page, I got an Internal Server Error. When reading the log files, it said:

cmstderr.log: DataBaseError: (1146, "Table 'edxapp.dark_lang_darklangconfig' doesn't exist")
lmstderr.log: DataBaseError: (1146, "Table 'edxapp.splash_splashconfig' doesn't exist")

among other errors for Undefined

**Comment by edx-secure** [comment]
Those are migrations that were not run against your server.  You'll have to
run the migrations before the error goes away.

**Comment by mercefan** [comment]
I wrote migrate_db: yes at server_vars.yml in /edx/etc/ but, when updating edx-platform, it seems to skipping that step:

TASK: [edxapp | writing celery worker supervisor script] *********************\* 
skipping: [localhost]

TASK: [edxapp | syncdb and migrate] ******************************************\* 
skipping: [localhost]

TASK: [edxapp | syncdb and migrate] ******************************************\* 
skipping: [localhost]

TASK: [edxapp | db migrate] **************************************************\* 
skipping: [localhost]

TASK: [edxapp | db migrate] **************************************************\* 
skipping: [localhost]

Any idea how to solve it? Thank you in advance.

**Comment by sasasaftic** [comment]
So I tried it again on a fresh machine. After installation I did 

```
sudo rm -rf /edx/app/edxapp/edx-platform
```

And

```
sudo /edx/bin/update edx-platform master
```

That went well.

But then I changed edx_platform_repo in /edx/etc/server-vars.yml
and run again:

```
sudo /edx/bin/update edx-platform master
```

And I get the same error but with different user (previous edxapp001 was now root)

```
_mysql_exceptions.OperationalError: (1045, "Access denied for user 'root'@'localhost' (using password: YES)")
```

**Comment by feanil** [comment]
@sasasaftic   Can you post your server-vars.yml?

**Comment by mercefan** [comment]
Finally it worked making the migrations and adding those users to the database.

**Comment by sasasaftic** [comment]
@feanil 
I change:

```
EDXAPP_LMS_NGINX_PORT: '80'
always_run: false
changed_when: null
delegate_to: null
failed_when: null
ignore_errors: false
item: ''
migrate_db: 'yes'
openid_workaround: true
playbook_dir: .
register: null
```

to:

```
EDXAPP_LMS_NGINX_PORT: '80'
always_run: false
changed_when: null
delegate_to: null
failed_when: null
ignore_errors: false
item: ''
migrate_db: 'yes'
openid_workaround: true
playbook_dir: .
register: null
edx_platform_repo: "git@gitlab.xx.xx:sasasaftic/edx-platform.git"
```

Where xx.xx are replaced with gitlab that I'm using here at work. I added all the ssh-key that are required and I'm able to do git clone from gitlab (as root, myuser and edxapp user).

**Comment by feanil** [comment]
Did you manually run the migrations?

**Comment by sasasaftic** [comment]
When I did 

```
sudo -u www-data /edx/app/edxapp/venvs/edxapp/bin/python ./manage.py lms syncdb --migrate --settings aws
```

I got:

```
south.exceptions.GhostMigrations: 

 ! These migrations are in the database but not on disk:
    <student: 0032_auto__add_loginfailures>
    <bulk_email: 0009_force_unique_course_ids>
    <verify_student: 0002_auto__add_field_softwaresecurephotoverification_window>
    <verify_student: 0003_auto__add_field_softwaresecurephotoverification_display>
 ! I'm not trusting myself; either fix this yourself by fiddling
 ! with the south_migrationhistory table, or pass --delete-ghost-migrations
 ! to South to have it delete ALL of these records (this may not be good).
```

So I did:

```
sudo -u www-data /edx/app/edxapp/venvs/edxapp/bin/python ./manage.py lms migrate --delete-ghost-migrations --settings aws
```

And then:

```
sudo -u www-data /edx/app/edxapp/venvs/edxapp/bin/python ./manage.py lms syncdb --migrate --settings aws
```

After that I tried once more:

```
sudo /edx/bin/update edx-platform master
```

with the same error.

Then I tried:

```
sudo service nginx stop
sudo service supervisor stop
sudo service supervisor.devpi stop
sudo pkill -u www-data
sudo service nginx start
sudo service supervisor start
sudo service supervisor.devpi start
```

And after that I was able to see edx lms and studio - did not test yet if I can make new courses, etc..

**Comment by sasasaftic** [comment]
I'm closing this issue. It's working now. I changed my repo to work without need for migrations.
