### ISSUE TITLE
MySQL-python RuntimeError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by lalves** [openedx-unsupported/configuration#924]
Hi Guys,

I'm trying to install through the script: 
wget https://raw.github.com/edx/configuration/master/util/install/vagrant.sh -O - | bash

When the task related to install the Mysql-python package starts I got this error:
  File "distribute_setup.py", line 116, in _build_egg

```
raise IOError('Could not build the egg.')
```

IOError: Could not build the egg.

---

Cleaning up...
Command python setup.py egg_info failed with error code 1 in /edx/app/discern/venvs/discern/build/MySQL-python

Then, I tried to install the package alone inside virtualenv and I got the same error. So, I searched a little bit around this and the only solution I found was to change to package version from  install MySQL-python==1.2.4 to install MySQL-python==1.2.5

So, I think you should change the package version.

Best.

**Comment by hkim823** [comment]
Can you post the full failure in a gist so we can get a better idea exactly where this is happening?

**Comment by lalves** [comment]
Is there a log that can I recover this?

best!

**Comment by hkim823** [comment]
Best thing is to run it again, re create your steps, and post that in a gist.

**Comment by bys** [comment]
@hkim823 @lalves 
i am also got this error when i install edx with "edX Ubuntu 12.04 Installation" (manual)
Command python setup.py egg_info failed with error code 1 in /edx/app/discern/venvs/discern/build/MySQL-python
1- i change to " /edx/app/discern/venvs/discern " but there is no dir called : build
2- after add this dir(build/MySQL-python) the error occour again.

THIS is log(error log is very long):

---

---

---

  File "/tmp/tmp8j5B46/distribute-0.6.28/pkg_resources.py", line 2128, in **init**

```
self.project_name = safe_name(project_name or 'Unknown')
```

  File "/tmp/tmp8j5B46/distribute-0.6.28/pkg_resources.py", line 1139, in safe_name

```
return re.sub('[^A-Za-z0-9.]+', '-', name)
```

  File "/edx/app/discern/venvs/discern/lib/python2.7/re.py", line 151, in sub

```
return _compile(pattern, flags).sub(repl, string, count)
```

RuntimeError: maximum recursion depth exceeded

/edx/app/discern/venvs/discern/build/MySQL-python/distribute-0.6.28-py2.7.egg

Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/edx/app/discern/venvs/discern/build/MySQL-python/setup.py", line 7, in <module>

```
use_setuptools()
```

  File "distribute_setup.py", line 145, in use_setuptools

```
return _do_download(version, download_base, to_dir, download_delay)
```

  File "distribute_setup.py", line 125, in _do_download

```
_build_egg(egg, tarball, to_dir)
```

  File "distribute_setup.py", line 116, in _build_egg

```
raise IOError('Could not build the egg.')
```

IOError: Could not build the egg.

---

Cleaning up...
  Removing temporary dir /edx/app/discern/venvs/discern/build...
Command python setup.py egg_info failed with error code 1 in /edx/app/discern/venvs/discern/build/MySQL-python
Exception information:
Traceback (most recent call last):
  File "/edx/app/discern/venvs/discern/local/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/edx/app/discern/venvs/discern/local/lib/python2.7/site-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/edx/app/discern/venvs/discern/local/lib/python2.7/site-packages/pip/req.py", line 1229, in prepare_files
    req_to_install.run_egg_info()
  File "/edx/app/discern/venvs/discern/local/lib/python2.7/site-packages/pip/req.py", line 325, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/edx/app/discern/venvs/discern/local/lib/python2.7/site-packages/pip/util.py", line 697, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command python setup.py egg_info failed with error code 1 in /edx/app/discern/venvs/discern/build/MySQL-python

**Comment by lalves** [comment]
Hi @bys I had the same problem.. if you try to install manually via pip the version 1.2.5 and run the script installer again, it should work fine!

So, this is the same log error.. You can check this out @hkim823

**Comment by hkim823** [comment]
Although we do have plans to move the version up to 1.2.5 in the near future, I am right now not able to reproduce this error building edX from scratch on a fresh Ubuntu box.  For now I'm going to close this issue,
